[package]
name = "dartr"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
dartr_syntax.workspace = true
dartr_parser.workspace = true
rayon.workspace = true

[dev-dependencies]
dartr_difftest = { path = "../dartr_difftest" }
