// Dart source: pkg/_fe_analyzer_shared/lib/src/experiments/flags.dart
//
// GENERATED FILE. DO NOT EDIT. Run `python3 tools/codegen/gen_experimental_flags.py`.

//! Dart `ExperimentalFlag`: the experimental flags shared between the CFE
//! and the analyzer.

/// Dart `defaultLanguageVersion`.
pub const DEFAULT_LANGUAGE_VERSION: (u32, u32) = (3, 13);

/// Dart `ExperimentalFlag`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ExperimentalFlag {
    AnonymousMethods,
    Augmentations,
    ClassModifiers,
    ConstFunctions,
    ConstantUpdate2018,
    ConstructorTearoffs,
    ControlFlowCollections,
    DataAssets,
    DigitSeparators,
    DotShorthands,
    EnhancedEnums,
    EnhancedParts,
    ExtensionMethods,
    GenericMetadata,
    GetterSetterError,
    InferenceUpdate1,
    InferenceUpdate2,
    InferenceUpdate3,
    InferenceUpdate4,
    InferenceUsingBounds,
    InlineClass,
    Macros,
    NamedArgumentsAnywhere,
    NativeAssets,
    NonNullable,
    NonfunctionTypeAliases,
    NullAwareElements,
    Patterns,
    PrimaryConstructors,
    PrivateNamedParameters,
    RecordUse,
    Records,
    SealedClass,
    SetLiterals,
    SoundFlowAnalysis,
    SpreadCollections,
    StaticExtensions,
    SuperParameters,
    TestExperiment,
    ThisPromotion,
    TripleShift,
    UnnamedLibraries,
    UnquotedImports,
    Variance,
    WildcardVariables,
}

impl ExperimentalFlag {
    /// All flags, in declaration order (`ExperimentalFlag.values`).
    pub const VALUES: &[ExperimentalFlag] = &[
        ExperimentalFlag::AnonymousMethods,
        ExperimentalFlag::Augmentations,
        ExperimentalFlag::ClassModifiers,
        ExperimentalFlag::ConstFunctions,
        ExperimentalFlag::ConstantUpdate2018,
        ExperimentalFlag::ConstructorTearoffs,
        ExperimentalFlag::ControlFlowCollections,
        ExperimentalFlag::DataAssets,
        ExperimentalFlag::DigitSeparators,
        ExperimentalFlag::DotShorthands,
        ExperimentalFlag::EnhancedEnums,
        ExperimentalFlag::EnhancedParts,
        ExperimentalFlag::ExtensionMethods,
        ExperimentalFlag::GenericMetadata,
        ExperimentalFlag::GetterSetterError,
        ExperimentalFlag::InferenceUpdate1,
        ExperimentalFlag::InferenceUpdate2,
        ExperimentalFlag::InferenceUpdate3,
        ExperimentalFlag::InferenceUpdate4,
        ExperimentalFlag::InferenceUsingBounds,
        ExperimentalFlag::InlineClass,
        ExperimentalFlag::Macros,
        ExperimentalFlag::NamedArgumentsAnywhere,
        ExperimentalFlag::NativeAssets,
        ExperimentalFlag::NonNullable,
        ExperimentalFlag::NonfunctionTypeAliases,
        ExperimentalFlag::NullAwareElements,
        ExperimentalFlag::Patterns,
        ExperimentalFlag::PrimaryConstructors,
        ExperimentalFlag::PrivateNamedParameters,
        ExperimentalFlag::RecordUse,
        ExperimentalFlag::Records,
        ExperimentalFlag::SealedClass,
        ExperimentalFlag::SetLiterals,
        ExperimentalFlag::SoundFlowAnalysis,
        ExperimentalFlag::SpreadCollections,
        ExperimentalFlag::StaticExtensions,
        ExperimentalFlag::SuperParameters,
        ExperimentalFlag::TestExperiment,
        ExperimentalFlag::ThisPromotion,
        ExperimentalFlag::TripleShift,
        ExperimentalFlag::UnnamedLibraries,
        ExperimentalFlag::UnquotedImports,
        ExperimentalFlag::Variance,
        ExperimentalFlag::WildcardVariables,
    ];

    /// Dart `ExperimentalFlag.name` (the command line name).
    pub fn name(self) -> &'static str {
        match self {
            ExperimentalFlag::AnonymousMethods => "anonymous-methods",
            ExperimentalFlag::Augmentations => "augmentations",
            ExperimentalFlag::ClassModifiers => "class-modifiers",
            ExperimentalFlag::ConstFunctions => "const-functions",
            ExperimentalFlag::ConstantUpdate2018 => "constant-update-2018",
            ExperimentalFlag::ConstructorTearoffs => "constructor-tearoffs",
            ExperimentalFlag::ControlFlowCollections => "control-flow-collections",
            ExperimentalFlag::DataAssets => "data-assets",
            ExperimentalFlag::DigitSeparators => "digit-separators",
            ExperimentalFlag::DotShorthands => "dot-shorthands",
            ExperimentalFlag::EnhancedEnums => "enhanced-enums",
            ExperimentalFlag::EnhancedParts => "enhanced-parts",
            ExperimentalFlag::ExtensionMethods => "extension-methods",
            ExperimentalFlag::GenericMetadata => "generic-metadata",
            ExperimentalFlag::GetterSetterError => "getter-setter-error",
            ExperimentalFlag::InferenceUpdate1 => "inference-update-1",
            ExperimentalFlag::InferenceUpdate2 => "inference-update-2",
            ExperimentalFlag::InferenceUpdate3 => "inference-update-3",
            ExperimentalFlag::InferenceUpdate4 => "inference-update-4",
            ExperimentalFlag::InferenceUsingBounds => "inference-using-bounds",
            ExperimentalFlag::InlineClass => "inline-class",
            ExperimentalFlag::Macros => "macros",
            ExperimentalFlag::NamedArgumentsAnywhere => "named-arguments-anywhere",
            ExperimentalFlag::NativeAssets => "native-assets",
            ExperimentalFlag::NonNullable => "non-nullable",
            ExperimentalFlag::NonfunctionTypeAliases => "nonfunction-type-aliases",
            ExperimentalFlag::NullAwareElements => "null-aware-elements",
            ExperimentalFlag::Patterns => "patterns",
            ExperimentalFlag::PrimaryConstructors => "primary-constructors",
            ExperimentalFlag::PrivateNamedParameters => "private-named-parameters",
            ExperimentalFlag::RecordUse => "record-use",
            ExperimentalFlag::Records => "records",
            ExperimentalFlag::SealedClass => "sealed-class",
            ExperimentalFlag::SetLiterals => "set-literals",
            ExperimentalFlag::SoundFlowAnalysis => "sound-flow-analysis",
            ExperimentalFlag::SpreadCollections => "spread-collections",
            ExperimentalFlag::StaticExtensions => "static-extensions",
            ExperimentalFlag::SuperParameters => "super-parameters",
            ExperimentalFlag::TestExperiment => "test-experiment",
            ExperimentalFlag::ThisPromotion => "this-promotion",
            ExperimentalFlag::TripleShift => "triple-shift",
            ExperimentalFlag::UnnamedLibraries => "unnamed-libraries",
            ExperimentalFlag::UnquotedImports => "unquoted-imports",
            ExperimentalFlag::Variance => "variance",
            ExperimentalFlag::WildcardVariables => "wildcard-variables",
        }
    }

    /// Dart `ExperimentalFlag.isEnabledByDefault`.
    pub fn is_enabled_by_default(self) -> bool {
        match self {
            ExperimentalFlag::AnonymousMethods => false,
            ExperimentalFlag::Augmentations => false,
            ExperimentalFlag::ClassModifiers => true,
            ExperimentalFlag::ConstFunctions => false,
            ExperimentalFlag::ConstantUpdate2018 => true,
            ExperimentalFlag::ConstructorTearoffs => true,
            ExperimentalFlag::ControlFlowCollections => true,
            ExperimentalFlag::DataAssets => false,
            ExperimentalFlag::DigitSeparators => true,
            ExperimentalFlag::DotShorthands => true,
            ExperimentalFlag::EnhancedEnums => true,
            ExperimentalFlag::EnhancedParts => false,
            ExperimentalFlag::ExtensionMethods => true,
            ExperimentalFlag::GenericMetadata => true,
            ExperimentalFlag::GetterSetterError => true,
            ExperimentalFlag::InferenceUpdate1 => true,
            ExperimentalFlag::InferenceUpdate2 => true,
            ExperimentalFlag::InferenceUpdate3 => true,
            ExperimentalFlag::InferenceUpdate4 => false,
            ExperimentalFlag::InferenceUsingBounds => true,
            ExperimentalFlag::InlineClass => true,
            ExperimentalFlag::Macros => false,
            ExperimentalFlag::NamedArgumentsAnywhere => true,
            ExperimentalFlag::NativeAssets => true,
            ExperimentalFlag::NonNullable => true,
            ExperimentalFlag::NonfunctionTypeAliases => true,
            ExperimentalFlag::NullAwareElements => true,
            ExperimentalFlag::Patterns => true,
            ExperimentalFlag::PrimaryConstructors => true,
            ExperimentalFlag::PrivateNamedParameters => true,
            ExperimentalFlag::RecordUse => true,
            ExperimentalFlag::Records => true,
            ExperimentalFlag::SealedClass => true,
            ExperimentalFlag::SetLiterals => true,
            ExperimentalFlag::SoundFlowAnalysis => true,
            ExperimentalFlag::SpreadCollections => true,
            ExperimentalFlag::StaticExtensions => false,
            ExperimentalFlag::SuperParameters => true,
            ExperimentalFlag::TestExperiment => false,
            ExperimentalFlag::ThisPromotion => false,
            ExperimentalFlag::TripleShift => true,
            ExperimentalFlag::UnnamedLibraries => true,
            ExperimentalFlag::UnquotedImports => false,
            ExperimentalFlag::Variance => false,
            ExperimentalFlag::WildcardVariables => true,
        }
    }

    /// Dart `ExperimentalFlag.isExpired`.
    pub fn is_expired(self) -> bool {
        match self {
            ExperimentalFlag::AnonymousMethods => false,
            ExperimentalFlag::Augmentations => false,
            ExperimentalFlag::ClassModifiers => true,
            ExperimentalFlag::ConstFunctions => false,
            ExperimentalFlag::ConstantUpdate2018 => true,
            ExperimentalFlag::ConstructorTearoffs => true,
            ExperimentalFlag::ControlFlowCollections => true,
            ExperimentalFlag::DataAssets => false,
            ExperimentalFlag::DigitSeparators => true,
            ExperimentalFlag::DotShorthands => true,
            ExperimentalFlag::EnhancedEnums => true,
            ExperimentalFlag::EnhancedParts => false,
            ExperimentalFlag::ExtensionMethods => true,
            ExperimentalFlag::GenericMetadata => true,
            ExperimentalFlag::GetterSetterError => true,
            ExperimentalFlag::InferenceUpdate1 => true,
            ExperimentalFlag::InferenceUpdate2 => true,
            ExperimentalFlag::InferenceUpdate3 => true,
            ExperimentalFlag::InferenceUpdate4 => false,
            ExperimentalFlag::InferenceUsingBounds => true,
            ExperimentalFlag::InlineClass => true,
            ExperimentalFlag::Macros => false,
            ExperimentalFlag::NamedArgumentsAnywhere => true,
            ExperimentalFlag::NativeAssets => true,
            ExperimentalFlag::NonNullable => true,
            ExperimentalFlag::NonfunctionTypeAliases => true,
            ExperimentalFlag::NullAwareElements => true,
            ExperimentalFlag::Patterns => true,
            ExperimentalFlag::PrimaryConstructors => false,
            ExperimentalFlag::PrivateNamedParameters => true,
            ExperimentalFlag::RecordUse => false,
            ExperimentalFlag::Records => true,
            ExperimentalFlag::SealedClass => true,
            ExperimentalFlag::SetLiterals => true,
            ExperimentalFlag::SoundFlowAnalysis => true,
            ExperimentalFlag::SpreadCollections => true,
            ExperimentalFlag::StaticExtensions => false,
            ExperimentalFlag::SuperParameters => true,
            ExperimentalFlag::TestExperiment => false,
            ExperimentalFlag::ThisPromotion => false,
            ExperimentalFlag::TripleShift => true,
            ExperimentalFlag::UnnamedLibraries => true,
            ExperimentalFlag::UnquotedImports => false,
            ExperimentalFlag::Variance => false,
            ExperimentalFlag::WildcardVariables => true,
        }
    }

    /// Dart `ExperimentalFlag.experimentEnabledVersion` (major, minor).
    pub fn experiment_enabled_version(self) -> (u32, u32) {
        match self {
            ExperimentalFlag::AnonymousMethods => (3, 13),
            ExperimentalFlag::Augmentations => (3, 13),
            ExperimentalFlag::ClassModifiers => (3, 0),
            ExperimentalFlag::ConstFunctions => (3, 13),
            ExperimentalFlag::ConstantUpdate2018 => (2, 0),
            ExperimentalFlag::ConstructorTearoffs => (2, 15),
            ExperimentalFlag::ControlFlowCollections => (2, 0),
            ExperimentalFlag::DataAssets => (3, 13),
            ExperimentalFlag::DigitSeparators => (3, 6),
            ExperimentalFlag::DotShorthands => (3, 10),
            ExperimentalFlag::EnhancedEnums => (2, 17),
            ExperimentalFlag::EnhancedParts => (3, 13),
            ExperimentalFlag::ExtensionMethods => (2, 6),
            ExperimentalFlag::GenericMetadata => (2, 14),
            ExperimentalFlag::GetterSetterError => (3, 9),
            ExperimentalFlag::InferenceUpdate1 => (2, 18),
            ExperimentalFlag::InferenceUpdate2 => (3, 2),
            ExperimentalFlag::InferenceUpdate3 => (3, 4),
            ExperimentalFlag::InferenceUpdate4 => (3, 13),
            ExperimentalFlag::InferenceUsingBounds => (3, 7),
            ExperimentalFlag::InlineClass => (3, 3),
            ExperimentalFlag::Macros => (3, 13),
            ExperimentalFlag::NamedArgumentsAnywhere => (2, 17),
            ExperimentalFlag::NativeAssets => (3, 10),
            ExperimentalFlag::NonNullable => (2, 12),
            ExperimentalFlag::NonfunctionTypeAliases => (2, 13),
            ExperimentalFlag::NullAwareElements => (3, 8),
            ExperimentalFlag::Patterns => (3, 0),
            ExperimentalFlag::PrimaryConstructors => (3, 13),
            ExperimentalFlag::PrivateNamedParameters => (3, 12),
            ExperimentalFlag::RecordUse => (3, 13),
            ExperimentalFlag::Records => (3, 0),
            ExperimentalFlag::SealedClass => (3, 0),
            ExperimentalFlag::SetLiterals => (2, 0),
            ExperimentalFlag::SoundFlowAnalysis => (3, 9),
            ExperimentalFlag::SpreadCollections => (2, 0),
            ExperimentalFlag::StaticExtensions => (3, 13),
            ExperimentalFlag::SuperParameters => (2, 17),
            ExperimentalFlag::TestExperiment => (3, 13),
            ExperimentalFlag::ThisPromotion => (3, 13),
            ExperimentalFlag::TripleShift => (2, 14),
            ExperimentalFlag::UnnamedLibraries => (2, 19),
            ExperimentalFlag::UnquotedImports => (3, 13),
            ExperimentalFlag::Variance => (3, 13),
            ExperimentalFlag::WildcardVariables => (3, 7),
        }
    }

    /// Dart `ExperimentalFlag.experimentReleasedVersion` (major, minor).
    pub fn experiment_released_version(self) -> (u32, u32) {
        match self {
            ExperimentalFlag::AnonymousMethods => (3, 13),
            ExperimentalFlag::Augmentations => (3, 6),
            ExperimentalFlag::ClassModifiers => (3, 0),
            ExperimentalFlag::ConstFunctions => (3, 13),
            ExperimentalFlag::ConstantUpdate2018 => (2, 0),
            ExperimentalFlag::ConstructorTearoffs => (2, 15),
            ExperimentalFlag::ControlFlowCollections => (2, 0),
            ExperimentalFlag::DataAssets => (3, 13),
            ExperimentalFlag::DigitSeparators => (3, 6),
            ExperimentalFlag::DotShorthands => (3, 9),
            ExperimentalFlag::EnhancedEnums => (2, 17),
            ExperimentalFlag::EnhancedParts => (3, 6),
            ExperimentalFlag::ExtensionMethods => (2, 6),
            ExperimentalFlag::GenericMetadata => (2, 14),
            ExperimentalFlag::GetterSetterError => (3, 9),
            ExperimentalFlag::InferenceUpdate1 => (2, 18),
            ExperimentalFlag::InferenceUpdate2 => (3, 2),
            ExperimentalFlag::InferenceUpdate3 => (3, 4),
            ExperimentalFlag::InferenceUpdate4 => (3, 13),
            ExperimentalFlag::InferenceUsingBounds => (3, 7),
            ExperimentalFlag::InlineClass => (3, 3),
            ExperimentalFlag::Macros => (3, 3),
            ExperimentalFlag::NamedArgumentsAnywhere => (2, 17),
            ExperimentalFlag::NativeAssets => (3, 9),
            ExperimentalFlag::NonNullable => (2, 10),
            ExperimentalFlag::NonfunctionTypeAliases => (2, 13),
            ExperimentalFlag::NullAwareElements => (3, 8),
            ExperimentalFlag::Patterns => (3, 0),
            ExperimentalFlag::PrimaryConstructors => (3, 12),
            ExperimentalFlag::PrivateNamedParameters => (3, 12),
            ExperimentalFlag::RecordUse => (3, 13),
            ExperimentalFlag::Records => (3, 0),
            ExperimentalFlag::SealedClass => (3, 0),
            ExperimentalFlag::SetLiterals => (2, 0),
            ExperimentalFlag::SoundFlowAnalysis => (3, 9),
            ExperimentalFlag::SpreadCollections => (2, 0),
            ExperimentalFlag::StaticExtensions => (3, 13),
            ExperimentalFlag::SuperParameters => (2, 17),
            ExperimentalFlag::TestExperiment => (3, 13),
            ExperimentalFlag::ThisPromotion => (3, 13),
            ExperimentalFlag::TripleShift => (2, 14),
            ExperimentalFlag::UnnamedLibraries => (2, 19),
            ExperimentalFlag::UnquotedImports => (3, 13),
            ExperimentalFlag::Variance => (3, 13),
            ExperimentalFlag::WildcardVariables => (3, 7),
        }
    }
}
