#!/usr/bin/env python3
"""Generates the AST node model of crates/dartr_ast from its schema.

Input: crates/dartr_ast/schema/ast.json, extracted from the pinned analyzer
(`pkg/analyzer/lib/src/dart/ast/ast.dart`, `@GenerateNodeImpl` annotations,
and `GeneralizingAstVisitor` of `lib/dart/ast/visitor.g.dart`) with

    (cd tools/oracle && dart run bin/ast_schema.dart > ../../crates/dartr_ast/schema/ast.json)

Output: crates/dartr_ast/src/generated/{nodes,children,visitor,copy}.rs. Run from
the repository root:

    python3 tools/codegen/gen_ast.py

The generated code follows the rules of the Dart generator
(`pkg/analyzer/tool/generators/ast_generator.dart`): `beginToken`,
`endToken`, `firstTokenAfterCommentAndMetadata`, `_childEntities`,
`visitChildren`, `replaceChild` and `removeChild` come from the order and the
kinds of the properties in `childEntitiesOrder`.
"""
import json
import os
import re
import subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SCHEMA = os.path.join(ROOT, 'crates/dartr_ast/schema/ast.json')
OUT = os.path.join(ROOT, 'crates/dartr_ast/src/generated')

HEADER = '''// GENERATED FILE. DO NOT EDIT.
// Generated by tools/codegen/gen_ast.py from crates/dartr_ast/schema/ast.json.
// Dart source: pkg/analyzer/lib/src/dart/ast/ast.dart
'''

RUST_KEYWORDS = {'type': 'type_'}

# Interfaces of ast.dart that are not node categories.
SKIP_INTERFACES = {'SyntheticIdentifier', 'ForLoop'}

# Nodes without `@GenerateNodeImpl`: properties written here, begin/end
# tokens and child entities are hand-written (src/node_impl.rs).
MANUAL = {
    'Comment': [
        {'name': 'references', 'kind': 'node_list', 'nullable': False, 'type': 'CommentReference'},
        {'name': 'tokens', 'kind': 'token_list', 'nullable': False},
        {'name': 'codeBlocks', 'kind': 'other', 'nullable': False, 'dart_type': 'List<MdCodeBlock>'},
        {'name': 'docImports', 'kind': 'other', 'nullable': False, 'dart_type': 'List<DocImport>'},
        {'name': 'docDirectives', 'kind': 'other', 'nullable': False, 'dart_type': 'List<DocDirective>'},
        {'name': 'hasNodoc', 'kind': 'other', 'nullable': False, 'dart_type': 'bool'},
    ],
    'CompilationUnit': [
        {'name': 'beginToken', 'kind': 'token', 'nullable': False, 'not_child': True},
        {'name': 'scriptTag', 'kind': 'node', 'nullable': True, 'type': 'ScriptTag'},
        {'name': 'directives', 'kind': 'node_list', 'nullable': False, 'type': 'Directive'},
        {'name': 'declarations', 'kind': 'node_list', 'nullable': False, 'type': 'CompilationUnitMember'},
        {'name': 'endToken', 'kind': 'token', 'nullable': False, 'not_child': True},
    ],
}

# Nodes that are not part of the syntax tree (`ConstantContextForExpression`
# is created by the constant evaluator, it has no visitor method).
SKIP_NODES = {'ConstantContextForExpression'}

# `other` properties: the Rust type, or None for resolution data, which is
# kept in side tables (see the crate documentation).
OTHER_TYPES = {
    'bool': 'bool',
    'double': 'f64',
    'int?': 'Option<i64>',
    'String': 'Box<str>',
    'ParameterKind': 'ParameterKind',
    'List<MdCodeBlock>': 'Vec<MdCodeBlock>',
    'List<DocImport>': 'Vec<DocImport>',
    'List<DocDirective>': 'Vec<DocDirective>',
    'ExtensionElementImpl': None,
    'MethodElement?': None,
    'List<DartType>': None,
}


def snake(name):
    s = re.sub(r'(?<=[a-z0-9])([A-Z])', r'_\1', name)
    s = re.sub(r'([A-Z]+)([A-Z][a-z])', r'\1_\2', s)
    return s.lower()


def field(name):
    s = snake(name)
    return RUST_KEYWORDS.get(s, s)


def load():
    with open(SCHEMA) as f:
        schema = json.load(f)
    nodes = []
    for n in schema['nodes']:
        if n['name'] in SKIP_NODES:
            continue
        props = n.get('properties')
        if props is None:
            props = MANUAL[n['name']]
        props = [dict(p) for p in props]
        for p in props:
            if p['kind'] == 'other':
                p['rust_type'] = OTHER_TYPES[p['dart_type']]
        n = dict(n)
        n['props'] = [p for p in props if not (p['kind'] == 'other' and p['rust_type'] is None)]
        n['manual'] = n['name'] in MANUAL
        n['dump_name'] = n['impl'][:-4] if n['impl'].endswith('Impl') else n['impl']
        nodes.append(n)
    nodes.sort(key=lambda n: n['name'])
    interfaces = {k: v for k, v in schema['interfaces'].items() if k not in SKIP_INTERFACES}
    for v in interfaces.values():
        v['supertypes'] = [s for s in v['supertypes'] if s not in SKIP_INTERFACES]
        v['all_supertypes'] = [s for s in v['all_supertypes'] if s not in SKIP_INTERFACES]
    return schema, nodes, interfaces


def all_props(n):
    """Properties including the comment and metadata of annotated nodes."""
    pre = []
    if n['annotated']:
        pre = [
            {'name': 'documentationComment', 'kind': 'node', 'nullable': True, 'type': 'Comment', 'annotated_prefix': True},
            {'name': 'metadata', 'kind': 'node_list', 'nullable': False, 'type': 'Annotation', 'annotated_prefix': True},
        ]
    return pre + n['props']


def rust_type(p):
    k = p['kind']
    if k == 'token':
        return 'Option<TokenId>' if p['nullable'] else 'TokenId'
    if k == 'token_list':
        return 'TokenList'
    if k == 'node':
        t = 'Id<%s>' % p['type']
        return 'Option<%s>' % t if p['nullable'] else t
    if k == 'node_list':
        return 'NodeList<%s>' % p['type']
    return p['rust_type']


def gen_nodes(schema, nodes, interfaces):
    concrete = [n['name'] for n in nodes]
    out = [HEADER]
    out.append('''
//! Node structs, node kinds, node categories (the abstract Dart interfaces)
//! and the reflection table.

#![allow(clippy::all)]

use dartr_syntax::TokenId;

use crate::arena::{Concrete, Id, NodeList, NodeType, SubtypeOf, TokenList};
use crate::doc_comment::{DocDirective, DocImport, MdCodeBlock};
use crate::node_impl::ParameterKind;

/// The kind of a node: one value per concrete node class of the analyzer
/// (Dart `XImpl`).
#[derive(Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Debug)]
#[repr(u8)]
pub enum NodeKind {
''')
    for n in nodes:
        out.append('    %s,\n' % n['name'])
    out.append('}\n\n')
    out.append('impl NodeKind {\n')
    out.append('    pub const COUNT: usize = %d;\n\n' % len(nodes))
    out.append('    pub const ALL: [NodeKind; %d] = [\n' % len(nodes))
    for n in nodes:
        out.append('        NodeKind::%s,\n' % n['name'])
    out.append('    ];\n\n')
    out.append('    /// The Dart name of the node class without `Impl` (the `t` of the\n')
    out.append('    /// `ast` dump: `runtimeType` without `Impl`).\n')
    out.append('    pub fn name(self) -> &\'static str {\n        NODE_INFOS[self as usize].name\n    }\n\n')
    out.append('    pub fn info(self) -> &\'static NodeInfo {\n        &NODE_INFOS[self as usize]\n    }\n')
    out.append('}\n\n')

    # Structs.
    for n in nodes:
        out.append('/// Dart `%s`.\n' % n['impl'])
        sup = interfaces.get(n['name'], {}).get('all_supertypes', [])
        if sup:
            out.append('///\n/// Supertypes: %s.\n' % ', '.join('`%s`' % s for s in sup))
        out.append('#[derive(Clone, Debug)]\npub struct %s {\n' % n['name'])
        for p in all_props(n):
            doc = 'Dart `%s`' % p['name']
            if p.get('is_super'):
                doc += ' (declared in a superclass)'
            if p.get('not_child'):
                doc += ' (not a child entity)'
            out.append('    /// %s.\n' % doc)
            out.append('    pub %s: %s,\n' % (field(p['name']), rust_type(p)))
        out.append('}\n\n')
        out.append('impl NodeType for %s {\n' % n['name'])
        out.append('    const NAME: &\'static str = "%s";\n' % n['name'])
        subs = [m['name'] for m in nodes if m['name'] == n['name'] or n['name'] in interfaces.get(m['name'], {}).get('all_supertypes', [])]
        out.append('    #[inline]\n    fn test(kind: NodeKind) -> bool {\n')
        out.append('        matches!(kind, %s)\n    }\n}\n\n' % ' | '.join('NodeKind::%s' % s for s in subs))
        out.append('impl Concrete for %s {\n' % n['name'])
        out.append('    const KIND: NodeKind = NodeKind::%s;\n' % n['name'])
        out.append('    #[inline]\n    fn store(stores: &Stores) -> &Vec<Self> {\n        &stores.%s\n    }\n' % snake(n['name']))
        out.append('    #[inline]\n    fn store_mut(stores: &mut Stores) -> &mut Vec<Self> {\n        &mut stores.%s\n    }\n' % snake(n['name']))
        out.append('}\n\n')
        for s in sup:
            if s in SKIP_INTERFACES:
                continue
            out.append('impl SubtypeOf<%s> for %s {}\n' % (s, n['name']))
        out.append('\n')

    # Abstract categories.
    out.append('// Node categories: the abstract Dart interfaces (`Expression`,\n')
    out.append('// `Statement`, ...). They are only used as type parameters of `Id`.\n\n')
    for name in sorted(interfaces):
        if name in concrete:
            continue
        v = interfaces[name]
        out.append('/// Dart `%s` (abstract).\n' % name)
        out.append('#[derive(Debug)]\npub enum %s {}\n\n' % name)
        subs = [m['name'] for m in nodes if name in interfaces.get(m['name'], {}).get('all_supertypes', [])]
        out.append('impl NodeType for %s {\n' % name)
        out.append('    const NAME: &\'static str = "%s";\n' % name)
        out.append('    #[inline]\n    fn test(kind: NodeKind) -> bool {\n')
        if name == 'AstNode':
            out.append('        let _ = kind;\n        true\n    }\n}\n\n')
        elif subs:
            out.append('        matches!(kind, %s)\n    }\n}\n\n' % ' | '.join('NodeKind::%s' % s for s in subs))
        else:
            out.append('        let _ = kind;\n        false\n    }\n}\n\n')
        for s in v['all_supertypes']:
            out.append('impl SubtypeOf<%s> for %s {}\n' % (s, name))
        out.append('\n')

    # Stores.
    out.append('/// The node storage of an [`crate::Ast`]: one vector per node kind.\n')
    out.append('#[derive(Clone, Debug, Default)]\npub struct Stores {\n')
    for n in nodes:
        out.append('    pub %s: Vec<%s>,\n' % (snake(n['name']), n['name']))
    out.append('}\n\n')

    # Reflection.
    out.append('''/// The kind of a field of a node.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum FieldKind {
    Token,
    TokenList,
    Node,
    NodeList,
    /// A value that is not a child (for example `IntegerLiteral.value`).
    Other,
}

/// A field of a node, in `childEntities` order.
#[derive(Debug)]
pub struct FieldInfo {
    /// The Dart name of the property.
    pub name: &'static str,
    pub kind: FieldKind,
    pub nullable: bool,
    /// The Dart type of a node field or of the elements of a node list.
    pub ty: &'static str,
    /// Tests whether a node kind is a subtype of [ty].
    pub accepts: fn(NodeKind) -> bool,
    /// Whether the field is a child entity (false for
    /// `CompilationUnit.beginToken` and `endToken`).
    pub child: bool,
}

/// Information about a node kind (the schema at run time).
#[derive(Debug)]
pub struct NodeInfo {
    /// Dart name without `Impl`.
    pub name: &'static str,
    pub kind: NodeKind,
    /// Whether the node is a Dart `AnnotatedNode` (the first two fields
    /// are the documentation comment and the metadata).
    pub annotated: bool,
    /// All supertypes (Dart interfaces).
    pub supertypes: &'static [&'static str],
    pub fields: &'static [FieldInfo],
}

fn accepts_none(_: NodeKind) -> bool {
    false
}

pub static NODE_INFOS: [NodeInfo; NodeKind::COUNT] = [
''')
    kind_name = {'token': 'Token', 'token_list': 'TokenList', 'node': 'Node', 'node_list': 'NodeList', 'other': 'Other'}
    for n in nodes:
        out.append('    NodeInfo {\n')
        out.append('        name: "%s",\n' % n['dump_name'])
        out.append('        kind: NodeKind::%s,\n' % n['name'])
        out.append('        annotated: %s,\n' % ('true' if n['annotated'] else 'false'))
        sup = interfaces.get(n['name'], {}).get('all_supertypes', [])
        out.append('        supertypes: &[%s],\n' % ', '.join('"%s"' % s for s in sup))
        out.append('        fields: &[\n')
        for p in all_props(n):
            ty = p.get('type', '')
            acc = '<%s as NodeType>::test' % ty if ty else 'accepts_none'
            out.append('            FieldInfo { name: "%s", kind: FieldKind::%s, nullable: %s, ty: "%s", accepts: %s, child: %s },\n' % (
                p['name'], kind_name[p['kind']], 'true' if p['nullable'] else 'false', ty, acc,
                'false' if p.get('not_child') else 'true'))
        out.append('        ],\n    },\n')
    out.append('];\n')
    return ''.join(out)


def begin_token_body(n, props, indent='        '):
    """Port of `_generateBeginToken`."""
    lines = []
    found = False
    i = 0
    while i < len(props):
        p = props[i]
        name = field(p['name'])
        k = p['kind']
        if k == 'token' and p.get('token_group') is not None:
            g = p['token_group']
            group = []
            while i < len(props) and props[i]['kind'] == 'token' and props[i].get('token_group') == g:
                group.append(props[i])
                i += 1
            args = ', '.join(('self.%s' % field(q['name'])) if q['nullable'] else ('Some(self.%s)' % field(q['name'])) for q in group)
            lines.append('if let Some(result) = lexically_first(&ast.tokens, &[%s]) {' % args)
            lines.append('    return result;')
            lines.append('}')
            continue
        i += 1
        if k == 'token':
            if p['nullable']:
                lines.append('if let Some(%s) = self.%s {' % (name, name))
                lines.append('    return %s;' % name)
                lines.append('}')
            else:
                lines.append('return self.%s;' % name)
                found = True
                break
        elif k == 'token_list':
            lines.append('return ast.token_list(self.%s)[0];' % name)
            found = True
            break
        elif k == 'node':
            if p['nullable']:
                lines.append('if let Some(%s) = self.%s {' % (name, name))
                lines.append('    return ast.begin_token(%s);' % name)
                lines.append('}')
            else:
                lines.append('return ast.begin_token(self.%s);' % name)
                found = True
                break
        elif k == 'node_list':
            lines.append('if let Some(result) = ast.list_begin_token(self.%s) {' % name)
            lines.append('    return result;')
            lines.append('}')
    if not found:
        lines.append('panic!("Expected at least one non-null")')
    return '\n'.join(indent + l for l in lines) + '\n'


def end_token_body(n, props, indent='        '):
    """Port of `_generateEndToken`."""
    lines = []
    found = False
    for p in reversed(props):
        name = field(p['name'])
        k = p['kind']
        if k == 'token':
            if p['nullable']:
                lines.append('if let Some(%s) = self.%s {' % (name, name))
                lines.append('    return %s;' % name)
                lines.append('}')
            else:
                lines.append('return self.%s;' % name)
                found = True
                break
        elif k == 'token_list':
            lines.append('return *ast.token_list(self.%s).last().unwrap();' % name)
            found = True
            break
        elif k == 'node':
            if p['nullable']:
                lines.append('if let Some(%s) = self.%s {' % (name, name))
                lines.append('    return ast.end_token(%s);' % name)
                lines.append('}')
            else:
                lines.append('return ast.end_token(self.%s);' % name)
                found = True
                break
        elif k == 'node_list':
            lines.append('if let Some(result) = ast.list_end_token(self.%s) {' % name)
            lines.append('    return result;')
            lines.append('}')
    if not found:
        lines.append('panic!("Expected at least one non-null")')
    return '\n'.join(indent + l for l in lines) + '\n'


def gen_children(schema, nodes, interfaces):
    out = [HEADER]
    out.append('''
//! Generated node behavior: begin and end tokens, child entities, child
//! nodes, and replacing and removing children.

#![allow(clippy::all)]
#![allow(unreachable_code, unused_variables)]

use dartr_syntax::TokenId;

use crate::arena::{Ast, Entity, NodeId, NodeType};
use crate::generated::nodes::*;
use crate::token::lexically_first;

''')
    for n in nodes:
        props = n['props']
        allp = all_props(n)
        out.append('impl %s {\n' % n['name'])
        if not n['manual']:
            if n['annotated']:
                out.append('    /// Dart `firstTokenAfterCommentAndMetadata`.\n')
                out.append('    pub fn first_token_after_comment_and_metadata(&self, ast: &Ast) -> TokenId {\n')
                out.append(begin_token_body(n, props))
                out.append('    }\n\n')
                out.append('    /// Dart `beginToken` (`_AnnotatedNodeMixin`).\n')
                out.append('    pub fn begin_token(&self, ast: &Ast) -> TokenId {\n')
                out.append('        ast.annotated_begin_token(self.documentation_comment, self.metadata)\n')
                out.append('            .unwrap_or_else(|| self.first_token_after_comment_and_metadata(ast))\n')
                out.append('    }\n\n')
            else:
                out.append('    /// Dart `beginToken`.\n')
                out.append('    pub fn begin_token(&self, ast: &Ast) -> TokenId {\n')
                out.append(begin_token_body(n, props))
                out.append('    }\n\n')
            out.append('    /// Dart `endToken`.\n')
            out.append('    pub fn end_token(&self, ast: &Ast) -> TokenId {\n')
            out.append(end_token_body(n, props))
            out.append('    }\n\n')
        # child entities (before sorting)
        if not (n['manual'] or 'child_entities' in n.get('manual_parts', []) or n['name'] == 'FormalParameterList'):
            out.append('    /// Dart `_childEntities` (in property order, not sorted).\n')
            out.append('    pub(crate) fn child_entities_unsorted(&self, ast: &Ast, out: &mut Vec<Entity>) {\n')
            for p in allp:
                name = field(p['name'])
                k = p['kind']
                if p.get('not_child'):
                    continue
                if k == 'token':
                    if p['nullable']:
                        out.append('        if let Some(t) = self.%s {\n            out.push(Entity::Token(t));\n        }\n' % name)
                    else:
                        out.append('        out.push(Entity::Token(self.%s));\n' % name)
                elif k == 'token_list':
                    out.append('        out.extend(ast.token_list(self.%s).iter().map(|&t| Entity::Token(t)));\n' % name)
                elif k == 'node':
                    if p['nullable']:
                        out.append('        if let Some(c) = self.%s {\n            out.push(Entity::Node(c.raw()));\n        }\n' % name)
                    else:
                        out.append('        out.push(Entity::Node(self.%s.raw()));\n' % name)
                elif k == 'node_list':
                    out.append('        out.extend(ast.list_raw(self.%s).iter().map(|&c| Entity::Node(c)));\n' % name)
            out.append('    }\n\n')
        # visitChildren order
        out.append('    /// The child nodes in Dart `visitChildren` order.\n')
        out.append('    pub(crate) fn for_each_child(&self, ast: &Ast, f: &mut dyn FnMut(NodeId)) {\n')
        rest = allp
        if n['annotated']:
            out.append('        ast.visit_comment_and_annotations(self.documentation_comment, self.metadata, f);\n')
            rest = props
        if n['name'] == 'CompilationUnit':
            out.append('        if let Some(c) = self.script_tag {\n            f(c.raw());\n        }\n')
            out.append('        ast.visit_directives_and_declarations(self.directives, self.declarations, f);\n')
            rest = []
        for p in rest:
            name = field(p['name'])
            k = p['kind']
            if k == 'node':
                if p['nullable']:
                    out.append('        if let Some(c) = self.%s {\n            f(c.raw());\n        }\n' % name)
                else:
                    out.append('        f(self.%s.raw());\n' % name)
            elif k == 'node_list':
                out.append('        for &c in ast.list_raw(self.%s) {\n            f(c);\n        }\n' % name)
        out.append('    }\n\n')
        # _childContainingRange
        out.append('    /// Dart `_childContainingRange`: the child that contains the range.\n')
        out.append('    pub(crate) fn child_containing_range(&self, ast: &Ast, start: u32, end: u32) -> Option<NodeId> {\n')
        for p in allp:
            name = field(p['name'])
            k = p['kind']
            if k == 'node':
                if p['nullable']:
                    out.append('        if let Some(c) = self.%s {\n            if ast.contains_offset(c, start, end) {\n                return Some(c.raw());\n            }\n        }\n' % name)
                else:
                    out.append('        if ast.contains_offset(self.%s, start, end) {\n            return Some(self.%s.raw());\n        }\n' % (name, name))
            elif k == 'node_list':
                out.append('        if let Some(result) = ast.element_containing_range(self.%s, start, end) {\n            return Some(result);\n        }\n' % name)
        out.append('        None\n    }\n\n')
        # replace child
        out.append('    /// Dart `replaceChild`: replaces [old] with [new] (of kind [kind]) in\n')
        out.append('    /// a child slot. Returns false if [old] is not a child.\n')
        out.append('    pub(crate) fn replace_child(&mut self, lists: &mut [NodeId], old: NodeId, new: NodeId, kind: NodeKind) -> bool {\n')
        for p in allp:
            name = field(p['name'])
            k = p['kind']
            if k == 'node':
                t = p['type']
                if p['nullable']:
                    out.append('        if self.%s.map(|c| c.raw()) == Some(old) {\n' % name)
                    out.append('            assert!(<%s as NodeType>::test(kind), "replaceChild: {kind:?} is not a %s");\n' % (t, t))
                    out.append('            self.%s = Some(crate::arena::Id::from_raw(new));\n            return true;\n        }\n' % name)
                else:
                    out.append('        if self.%s.raw() == old {\n' % name)
                    out.append('            assert!(<%s as NodeType>::test(kind), "replaceChild: {kind:?} is not a %s");\n' % (t, t))
                    out.append('            self.%s = crate::arena::Id::from_raw(new);\n            return true;\n        }\n' % name)
            elif k == 'node_list':
                t = p['type']
                out.append('        if let Some(slot) = self.%s.slots_mut(lists).iter_mut().find(|c| **c == old) {\n' % name)
                out.append('            assert!(<%s as NodeType>::test(kind), "replaceChild: {kind:?} is not a %s");\n' % (t, t))
                out.append('            *slot = new;\n            return true;\n        }\n')
        out.append('        false\n    }\n\n')
        # remove child
        out.append('    /// Dart `removeChild`: clears a nullable child slot that holds [old].\n')
        out.append('    pub(crate) fn remove_child(&mut self, lists: &[NodeId], old: NodeId) -> Result<(), String> {\n')
        for p in allp:
            name = field(p['name'])
            k = p['kind']
            if k == 'node':
                if p['nullable']:
                    out.append('        if self.%s.map(|c| c.raw()) == Some(old) {\n            self.%s = None;\n            return Ok(());\n        }\n' % (name, name))
                else:
                    out.append('        if self.%s.raw() == old {\n            return Err("Cannot remove required child \'%s\'.".into());\n        }\n' % (name, p['name']))
            elif k == 'node_list':
                out.append('        if self.%s.slots(lists).contains(&old) {\n' % name)
                out.append('            return Err("Cannot remove child \'%s\' because NodeList cannot be resized.".into());\n        }\n' % p['name'])
        out.append('        Err("The old node is not a child of this node.".into())\n    }\n\n')
        # isInValueExpressionSlot
        if n['name'] not in ('PostfixExpression', 'PrefixExpression'):
            out.append('    /// Dart `isInValueExpressionSlot`.\n')
            out.append('    pub fn is_in_value_expression_slot(&self, ast: &Ast, child: NodeId) -> bool {\n')
            nodeish = [p for p in props if p['kind'] in ('node', 'node_list')]
            vals = [p for p in nodeish if p.get('value_slot')]
            nonvals = [p for p in nodeish if not p.get('value_slot')]
            if not vals:
                out.append('        false\n')
            elif not nonvals:
                out.append('        true\n')
            elif any(p['kind'] == 'node_list' for p in vals):
                conds = []
                for p in nonvals:
                    assert p['kind'] == 'node'
                    if p['nullable']:
                        conds.append('self.%s.map(|c| c.raw()) != Some(child)' % field(p['name']))
                    else:
                        conds.append('self.%s.raw() != child' % field(p['name']))
                out.append('        %s\n' % ' && '.join(conds))
            else:
                conds = []
                for p in vals:
                    if p['nullable']:
                        conds.append('self.%s.map(|c| c.raw()) == Some(child)' % field(p['name']))
                    else:
                        conds.append('self.%s.raw() == child' % field(p['name']))
                out.append('        %s\n' % ' || '.join(conds))
            out.append('    }\n')
        out.append('}\n\n')

    # Dispatch.
    def dispatch(fn_sig, call, ret_mut=False):
        s = []
        s.append('    %s {\n' % fn_sig)
        s.append('        let id: NodeId = id.into();\n')
        s.append('        let slot = self.slot(id);\n')
        s.append('        match self.kind(id) {\n')
        for n in nodes:
            s.append('            NodeKind::%s => %s,\n' % (n['name'], call.format(store=snake(n['name']))))
        s.append('        }\n    }\n\n')
        return ''.join(s)

    out.append('impl Ast {\n')
    out.append('    /// Dart `AstNode.beginToken`.\n')
    out.append(dispatch('pub fn begin_token(&self, id: impl Into<NodeId>) -> TokenId', 'self.stores.{store}[slot].begin_token(self)'))
    out.append('    /// Dart `AstNode.endToken`.\n')
    out.append(dispatch('pub fn end_token(&self, id: impl Into<NodeId>) -> TokenId', 'self.stores.{store}[slot].end_token(self)'))
    out.append('    /// The child entities in property order (Dart `_childEntities`\n')
    out.append('    /// before `syntacticEntities` sorts them).\n')
    s = []
    s.append('    pub(crate) fn child_entities_unsorted(&self, id: NodeId, out: &mut Vec<Entity>) {\n')
    s.append('        let slot = self.slot(id);\n        match self.kind(id) {\n')
    for n in nodes:
        s.append('            NodeKind::%s => self.stores.%s[slot].child_entities_unsorted(self, out),\n' % (n['name'], snake(n['name'])))
    s.append('        }\n    }\n\n')
    out.append(''.join(s))
    out.append('    /// Calls [f] for each child node, in Dart `visitChildren` order.\n')
    out.append(dispatch('pub fn for_each_child(&self, id: impl Into<NodeId>, f: &mut dyn FnMut(NodeId))', 'self.stores.{store}[slot].for_each_child(self, f)'))
    s = []
    s.append('    pub(crate) fn replace_child_raw(&mut self, parent: NodeId, old: NodeId, new: NodeId) -> bool {\n')
    s.append('        let slot = self.slot(parent);\n        let kind = self.kind(new);\n        let lists = &mut self.lists;\n')
    s.append('        match self.kinds[parent.index()] {\n')
    for n in nodes:
        s.append('            NodeKind::%s => self.stores.%s[slot].replace_child(lists, old, new, kind),\n' % (n['name'], snake(n['name'])))
    s.append('        }\n    }\n\n')
    s.append('    pub(crate) fn remove_child_raw(&mut self, parent: NodeId, old: NodeId) -> Result<(), String> {\n')
    s.append('        let slot = self.slot(parent);\n        let lists = &self.lists;\n')
    s.append('        match self.kinds[parent.index()] {\n')
    for n in nodes:
        s.append('            NodeKind::%s => self.stores.%s[slot].remove_child(lists, old),\n' % (n['name'], snake(n['name'])))
    s.append('        }\n    }\n\n')
    s.append('    /// Dart `AstNodeImpl._childContainingRange`.\n')
    s.append('    pub(crate) fn child_containing_range(&self, id: NodeId, start: u32, end: u32) -> Option<NodeId> {\n')
    s.append('        let slot = self.slot(id);\n        match self.kind(id) {\n')
    for n in nodes:
        s.append('            NodeKind::%s => self.stores.%s[slot].child_containing_range(self, start, end),\n' % (n['name'], snake(n['name'])))
    s.append('        }\n    }\n\n')
    s.append('    /// Dart `AstNode.isInValueExpressionSlot`: whether [child] (a child of\n')
    s.append('    /// [parent]) is in a slot that allows a value expression.\n')
    s.append('    pub fn is_in_value_expression_slot(&self, parent: impl Into<NodeId>, child: impl Into<NodeId>) -> bool {\n')
    s.append('        let parent: NodeId = parent.into();\n        let child: NodeId = child.into();\n')
    s.append('        let slot = self.slot(parent);\n        match self.kind(parent) {\n')
    for n in nodes:
        s.append('            NodeKind::%s => self.stores.%s[slot].is_in_value_expression_slot(self, child),\n' % (n['name'], snake(n['name'])))
    s.append('        }\n    }\n')
    out.append(''.join(s))
    out.append('}\n')

    # Generic construction from field values (for tools and tests).
    out.append('''
/// The value of one field, for [`build_node`].
#[derive(Clone, Debug)]
pub enum FieldValue {
    Token(Option<TokenId>),
    TokenList(crate::arena::TokenList),
    Node(Option<NodeId>),
    NodeList(crate::arena::NodeList<AstNode>),
    /// The default value of an `Other` field.
    Default,
}

fn tok(v: &FieldValue) -> Option<TokenId> {
    match v {
        FieldValue::Token(t) => *t,
        _ => panic!("expected a token, got {v:?}"),
    }
}

fn toks(v: &FieldValue) -> crate::arena::TokenList {
    match v {
        FieldValue::TokenList(t) => *t,
        _ => panic!("expected a token list, got {v:?}"),
    }
}

fn node<T: NodeType>(ast: &Ast, v: &FieldValue) -> Option<crate::arena::Id<T>> {
    match v {
        FieldValue::Node(n) => n.map(|n| ast.cast::<T>(n).unwrap_or_else(|| panic!("{:?} is not a {}", ast.kind(n), T::NAME))),
        _ => panic!("expected a node, got {v:?}"),
    }
}

fn list<T: NodeType>(v: &FieldValue) -> crate::arena::NodeList<T> {
    match v {
        FieldValue::NodeList(l) => l.cast(),
        _ => panic!("expected a node list, got {v:?}"),
    }
}

/// Creates a node of [kind] from field values in [`NodeInfo::fields`]
/// order. Panics when a value does not fit its field.
pub fn build_node(ast: &mut Ast, kind: NodeKind, values: &[FieldValue]) -> NodeId {
    assert_eq!(values.len(), kind.info().fields.len(), "{kind:?}: wrong number of fields");
    match kind {
''')
    for n in nodes:
        out.append('        NodeKind::%s => {\n' % n['name'])
        out.append('            let node = %s {\n' % n['name'])
        for i, p in enumerate(all_props(n)):
            name = field(p['name'])
            k = p['kind']
            if k == 'token':
                v = 'tok(&values[%d])' % i
                if not p['nullable']:
                    v += '.expect("%s.%s")' % (n['name'], p['name'])
            elif k == 'token_list':
                v = 'toks(&values[%d])' % i
            elif k == 'node':
                v = 'node(ast, &values[%d])' % i
                if not p['nullable']:
                    v += '.expect("%s.%s")' % (n['name'], p['name'])
            elif k == 'node_list':
                v = 'list(&values[%d])' % i
            else:
                v = 'Default::default()'
            out.append('                %s: %s,\n' % (name, v))
        out.append('            };\n            ast.add(node).raw()\n        }\n')
    out.append('    }\n}\n')
    return ''.join(out)


def gen_visitor(schema, nodes, interfaces):
    out = [HEADER]
    out.append('''// Dart source: pkg/analyzer/lib/dart/ast/visitor.g.dart

//! Visitors: [`AstVisitor`] (one method per node kind; the default visits
//! the children, like Dart `RecursiveAstVisitor`), [`AstVisitorMut`] (the
//! same with a mutable AST), and [`GeneralizingAstVisitor`] (walks the
//! class hierarchy: `visit_method_invocation` -> `visit_invocation_expression`
//! -> `visit_expression` -> `visit_node`).

#![allow(clippy::all)]

use crate::arena::{Ast, Id, NodeId};
use crate::generated::nodes::*;

/// A visitor with one method per node kind (Dart `AstVisitor`).
///
/// Every method calls [`AstVisitor::visit_node`] by default, and
/// `visit_node` visits the children (Dart `RecursiveAstVisitor`). To get
/// Dart `SimpleAstVisitor` (do nothing), override `visit_node` with an
/// empty body. Dart `UnifyingAstVisitor` is `visit_node` alone.
pub trait AstVisitor: Sized {
    /// The default of every method: visits the children of [node].
    fn visit_node(&mut self, ast: &Ast, node: NodeId) {
        ast.visit_children(node, self);
    }
''')
    for n in nodes:
        out.append('\n    fn visit_%s(&mut self, ast: &Ast, node: Id<%s>) {\n        self.visit_node(ast, node.raw());\n    }\n' % (snake(n['name']), n['name']))
    out.append('}\n\n')

    out.append('''/// [`AstVisitor`] with a mutable AST, for visitors that rewrite nodes
/// while they walk (Dart `ResolverVisitor`). The children of a node are read
/// before they are visited, so a method can replace its own node or
/// children.
pub trait AstVisitorMut: Sized {
    /// The default of every method: visits the children of [node].
    fn visit_node(&mut self, ast: &mut Ast, node: NodeId) {
        ast.visit_children_mut(node, self);
    }
''')
    for n in nodes:
        out.append('\n    fn visit_%s(&mut self, ast: &mut Ast, node: Id<%s>) {\n        self.visit_node(ast, node.raw());\n    }\n' % (snake(n['name']), n['name']))
    out.append('}\n\n')

    gen = schema['generalizing']
    names = sorted(set(gen.keys()))
    out.append('''/// Dart `GeneralizingAstVisitor`: the method of a node kind calls the
/// method of its superclass, up to [`GeneralizingAstVisitor::visit_node`],
/// which visits the children.
pub trait GeneralizingAstVisitor: Sized {
    /// Dart `visitNode`: visits the children of [node].
    fn visit_node(&mut self, ast: &Ast, node: NodeId) {
        ast.visit_children_generalizing(node, self);
    }
''')
    for name in names:
        if name in ('Node', 'AstNode'):
            continue
        target = gen[name]
        out.append('\n    fn visit_%s(&mut self, ast: &Ast, node: Id<%s>) {\n' % (snake(name), name))
        if name == 'FunctionDeclaration':
            out.append('        // Dart: a local function is visited as a node.\n')
            out.append('        if ast.parent(node).is_some_and(|p| ast.kind(p) == NodeKind::FunctionDeclarationStatement) {\n')
            out.append('            return self.visit_node(ast, node.raw());\n        }\n')
            out.append('        self.visit_compilation_unit_member(ast, node.upcast())\n')
        elif target is None or target == 'Node':
            out.append('        self.visit_node(ast, node.raw())\n')
        else:
            out.append('        self.visit_%s(ast, node.upcast())\n' % snake(target))
        out.append('    }\n')
    out.append('}\n\n')

    out.append('impl Ast {\n')
    out.append('    /// Dart `AstNode.accept`: calls the method of [v] for the kind of [node].\n')
    out.append('    pub fn accept<V: AstVisitor>(&self, node: impl Into<NodeId>, v: &mut V) {\n')
    out.append('        let node: NodeId = node.into();\n        match self.kind(node) {\n')
    for n in nodes:
        out.append('            NodeKind::%s => v.visit_%s(self, Id::from_raw(node)),\n' % (n['name'], snake(n['name'])))
    out.append('        }\n    }\n\n')
    out.append('    /// [`Ast::accept`] for an [`AstVisitorMut`].\n')
    out.append('    pub fn accept_mut<V: AstVisitorMut>(&mut self, node: impl Into<NodeId>, v: &mut V) {\n')
    out.append('        let node: NodeId = node.into();\n        match self.kind(node) {\n')
    for n in nodes:
        out.append('            NodeKind::%s => v.visit_%s(self, Id::from_raw(node)),\n' % (n['name'], snake(n['name'])))
    out.append('        }\n    }\n\n')
    out.append('    /// [`Ast::accept`] for a [`GeneralizingAstVisitor`].\n')
    out.append('    pub fn accept_generalizing<V: GeneralizingAstVisitor>(&self, node: impl Into<NodeId>, v: &mut V) {\n')
    out.append('        let node: NodeId = node.into();\n        match self.kind(node) {\n')
    for n in nodes:
        out.append('            NodeKind::%s => v.visit_%s(self, Id::from_raw(node)),\n' % (n['name'], snake(n['name'])))
    out.append('        }\n    }\n}\n')
    return ''.join(out)


def gen_copy(schema, nodes, interfaces):
    """Deep copy of a subtree into another `Ast` (driver: src/copy.rs)."""
    out = [HEADER]
    out.append('''// Dart source: pkg/analyzer/lib/src/summary2/detach_nodes.dart (copy instead of detach)

//! Per-kind code of [`crate::copy::AstCopier`]: each function clones the
//! node struct, maps every token through the token map, copies every child
//! node and node list, keeps the other fields (literal values, ...) as
//! cloned, and adds the new node to the destination `Ast` (which sets the
//! parents of the children).

#![allow(clippy::all)]

use crate::arena::NodeId;
use crate::copy::AstCopier;
use crate::generated::nodes::*;

/// Copies node [id] of the source `Ast` of [c] and its subtree into the
/// destination `Ast`. Returns the new node (without a parent).
pub(crate) fn copy_node(c: &mut AstCopier<'_>, id: NodeId) -> NodeId {
    let slot = c.src.slot(id);
    match c.src.kind(id) {
''')
    for n in nodes:
        out.append('        NodeKind::%s => copy_%s(c, slot),\n' % (n['name'], snake(n['name'])))
    out.append('    }\n}\n')
    for n in nodes:
        s = snake(n['name'])
        out.append("\n#[inline(never)]\nfn copy_%s(c: &mut AstCopier<'_>, slot: usize) -> NodeId {\n" % s)
        mut = any(p['kind'] != 'other' for p in all_props(n))
        out.append('    let %snode = c.src.stores.%s[slot].clone();\n' % ('mut ' if mut else '', s))
        for p in all_props(n):
            name = field(p['name'])
            k = p['kind']
            if k == 'token':
                if p['nullable']:
                    out.append('    node.%s = node.%s.map(|t| c.token(t));\n' % (name, name))
                else:
                    out.append('    node.%s = c.token(node.%s);\n' % (name, name))
            elif k == 'token_list':
                out.append('    node.%s = c.token_list(node.%s);\n' % (name, name))
            elif k == 'node':
                if p['nullable']:
                    out.append('    node.%s = node.%s.map(|n| c.node(n));\n' % (name, name))
                else:
                    out.append('    node.%s = c.node(node.%s);\n' % (name, name))
            elif k == 'node_list':
                out.append('    node.%s = c.list(node.%s);\n' % (name, name))
        out.append('    c.dst.add(node).raw()\n}\n')
    return ''.join(out)


def write(name, text):
    path = os.path.join(OUT, name)
    with open(path, 'w') as f:
        f.write(text)
    subprocess.run(['rustfmt', '--edition', '2024', path], check=True)


def main():
    schema, nodes, interfaces = load()
    os.makedirs(OUT, exist_ok=True)
    write('nodes.rs', gen_nodes(schema, nodes, interfaces))
    write('children.rs', gen_children(schema, nodes, interfaces))
    write('visitor.rs', gen_visitor(schema, nodes, interfaces))
    write('copy.rs', gen_copy(schema, nodes, interfaces))
    with open(os.path.join(OUT, 'mod.rs'), 'w') as f:
        f.write(HEADER + '\npub mod children;\npub mod copy;\npub mod nodes;\npub mod visitor;\n')
    print('%d node kinds' % len(nodes))


if __name__ == '__main__':
    main()
