#!/usr/bin/env python3
# Dart source: pkg/analyzer/lib/src/lint/linter_visitor.g.dart
# Dart source: pkg/linter/lib/src/rules.dart
"""Generate lint subscriptions and registry metadata from the pinned sources."""
import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SDK = ROOT / 'third_party/dart-sdk'
OUT = ROOT / 'crates/dartr_lints/src'

def snake(name):
    return re.sub(r'(?<!^)(?=[A-Z])', '_', name).lower()

def quote(value):
    return json.dumps(value, ensure_ascii=False)

schema = json.loads((ROOT / 'crates/dartr_ast/schema/ast.json').read_text())
lines = ['// Dart source: pkg/analyzer/lib/src/lint/linter_visitor.g.dart',
         '// Generated by tools/codegen/gen_lints.py; do not edit.',
         'use crate::{NodeProcessor, RuleVisitorRegistry};',
         'use dartr_ast::NodeKind;', 'impl RuleVisitorRegistry {']
kinds = set(re.findall(r'^    (\w+),', (ROOT / 'crates/dartr_ast/src/generated/nodes.rs').read_text(), re.M))
for node in schema['nodes']:
    name = node['name']
    if name not in kinds:
        continue
    lines.extend([f'    pub fn add_{snake(name)}(&mut self, rule: &\'static str, processor: NodeProcessor) {{',
                  f'        self.add(NodeKind::{name}, rule, processor);', '    }'])
lines.append('}')
(OUT / 'subscriptions.rs').write_text('\n'.join(lines) + '\n')

rules_file = (SDK / 'pkg/linter/lib/src/rules.dart').read_text()
files = re.findall(r"import 'rules/([^']+)\.dart';", rules_file)
symbols = {}
for filename in files:
    text = (SDK / f'pkg/linter/lib/src/rules/{filename}.dart').read_text()
    for symbol in re.findall(r'(?:class|final)\s+(\w+)', text):
        if not symbol.startswith('_'):
            symbols[symbol] = filename
registered = re.findall(r'registerLintRule\((\w+)(?:\(\))?\)', rules_file)
ordered_files = [symbols[symbol] for symbol in registered]
assert len(ordered_files) == len(files) and set(ordered_files) == set(files)
files = ordered_files
lines = ['// Dart source: pkg/linter/lib/src/rules.dart',
         '// Generated by tools/codegen/gen_lints.py; do not edit.',
         'use crate::{AnalysisRule, RuleState, RuleStateType};',
         'pub static ALL_RULES: &[AnalysisRule] = &[']
for filename in files:
    text = (SDK / f'pkg/linter/lib/src/rules/{filename}.dart').read_text()
    name_match = re.search(r'name:\s*LintNames\.(\w+)', text)
    if not name_match:
        name_match = re.search(r"(?:name:|ruleName\s*=)\s*'([^']+)'", text)
    if not name_match:
        raise ValueError(f'No rule name in {filename}')
    name = name_match[1]
    state = re.search(r'(?:RuleState|state:\s*)\.(\w+)\((.*?)\)', text, re.S)
    state_type, since, replaced = 'Stable', 'None', 'None'
    if state:
        state_type = state[1].title()
        since_match = re.search(r'since:\s*(?:(?:Version|\.new)\((\d+),\s*(\d+),\s*(\d+)|(dart2_12|dart3_3|dart3))', state[2])
        if since_match:
            parts = since_match.groups()
            version = tuple(map(int, parts[:3])) if parts[0] else {'dart2_12': (2,12,0), 'dart3_3': (3,3,0), 'dart3': (3,0,0)}[parts[3]]
            since = f'Some(({version[0]}, {version[1]}, {version[2]}))'
        replaced_match = re.search(r"replacedBy:\s*'([^']*)'", state[2])
        if replaced_match:
            replaced = f'Some({quote(replaced_match[1])})'
    if 'RemovedAnalysisRule(' in text:
        state_type = 'Removed'
        since_match = re.search(r'since:\s*(?:(?:Version|\.new)\((\d+),\s*(\d+),\s*(\d+)|(dart2_12|dart3_3|dart3))', text)
        if since_match:
            parts = since_match.groups()
            version = tuple(map(int, parts[:3])) if parts[0] else {'dart2_12': (2,12,0), 'dart3_3': (3,3,0), 'dart3': (3,0,0)}[parts[3]]
            since = f'Some(({version[0]}, {version[1]}, {version[2]}))'
        replacement = re.search(r"replacedBy:\s*'([^']*)'", text)
        if replacement:
            replaced = f'Some({quote(replacement[1])})'
    literal_pattern = r"r?(?:\"\"\".*?\"\"\"|'''.*?'''|\"(?:\\.|[^\"\\])*\"|'(?:\\.|[^'\\])*')"
    desc_expression = re.search(r"(?:const|final)\s+_?desc\s*=\s*((?:" + literal_pattern + r"\s*)+);", text, re.S)
    literals = re.findall(literal_pattern, desc_expression[1]) if desc_expression else []
    if not literals:
        desc_match = re.search(r"description:\s*(" + literal_pattern + r")", text, re.S)
        literals = [desc_match[1]] if desc_match else []
    description = ''
    for literal in literals:
        raw = literal.startswith('r')
        literal = literal[1:] if raw else literal
        delimiter = 3 if literal[:3] in ('\"\"\"', "\'\'\'") else 1
        part = literal[delimiter:-delimiter]
        if not raw:
            part = part.replace("\\'", "'").replace('\\"', '"').replace('\\n', '\n')
        description += part
    codes_expression = re.search(r'get diagnosticCodes?\s*=>\s*(.*?);', text, re.S)
    code_names = re.findall(r'\bdiag\.(\w+)', codes_expression[1]) if codes_expression else []
    codes = list(dict.fromkeys(code_names or re.findall(r'\bdiag\.(\w+)', text)))
    incompat = re.search(r'get incompatibleRules\s*=>\s*(?:const\s+)?\[(.*?)\]', text, re.S)
    incompatible = [m[0] or m[1] for m in re.findall(r"LintNames\.(\w+)|'([^']+)'", incompat[1])] if incompat else []
    lines.append(f'    AnalysisRule {{ name: {quote(name)}, description: {quote(description)}, state: RuleState {{ kind: RuleStateType::{state_type}, since: {since}, replaced_by: {replaced} }}, diagnostic_names: &[{", ".join(map(quote, codes))}], can_use_parsed_result: {str(bool(re.search(r'get canUseParsedResult\s*=>\s*true', text))).lower()}, incompatible_rules: &[{", ".join(map(quote, incompatible))}] }},')
lines.append('];')
(OUT / 'rule_metadata.rs').write_text('\n'.join(lines) + '\n')
print(f'Generated {sum(node['name'] in kinds for node in schema['nodes'])} subscription methods and {len(files)} rule records')

subprocess.run(['rustfmt', '--edition', '2024', '--config', 'skip_children=true', str(OUT / 'subscriptions.rs'), str(OUT / 'rule_metadata.rs')], check=True)
