#!/usr/bin/env python3
"""Generates the fix kinds and the fix registry of dartr_server from the pinned
analysis server sources:

- `DartFixKind` of `pkg/analysis_server/lib/src/services/correction/fix.dart`
  -> `crates/dartr_server/src/correction/generated/fix_kinds.rs`
- the producer lists of `pkg/analysis_server/lib/src/services/correction/fix_internal.dart`
  -> `crates/dartr_server/src/correction/generated/fix_registry.rs`

Run: python3 tools/codegen/gen_fixes.py
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(ROOT, 'third_party/dart-sdk/pkg/analysis_server/lib/src/services/correction')
OUT = os.path.join(ROOT, 'crates/dartr_server/src/correction/generated')

PRIORITY = {'standard': 50, 'inFile': 40, 'ignore': 30}


def dart_string(s):
    s = s.strip()
    parts = re.findall(r"'((?:[^'\\]|\\.)*)'|\"((?:[^\"\\]|\\.)*)\"", s)
    out = ''
    for a, b in parts:
        t = a if a else b
        out += t.replace("\\'", "'").replace('\\"', '"').replace('\\$', '$')
    return out


def snake(name):
    return re.sub(r'(?<!^)(?=[A-Z])', '_', name).upper()


def gen_kinds():
    text = open(os.path.join(SRC, 'fix.dart')).read()
    body = text[text.index('abstract final class DartFixKind'):]
    kinds = []
    for m in re.finditer(r"static const (\w+) = FixKind\((.*?)\);", body, re.S):
        name, args = m.group(1), m.group(2)
        # Split the three arguments at top-level commas.
        items, depth, cur, quote = [], 0, '', None
        for ch in args:
            if quote:
                cur += ch
                if ch == quote and not cur.endswith('\\' + quote):
                    quote = None
                continue
            if ch in '\'"':
                quote = ch
                cur += ch
                continue
            if ch == ',' and depth == 0:
                items.append(cur)
                cur = ''
                continue
            cur += ch
        if cur.strip():
            items.append(cur)
        fid = dart_string(items[0])
        prio = items[1].strip()
        pm = re.match(r'DartFixKindPriority\.(\w+)\s*(?:([+-])\s*(\d+))?', prio)
        value = PRIORITY[pm.group(1)]
        if pm.group(2):
            value = value + int(pm.group(3)) if pm.group(2) == '+' else value - int(pm.group(3))
        message = dart_string(items[2])
        kinds.append((name, fid, value, message))
    lines = [
        '// Generated by tools/codegen/gen_fixes.py from',
        '// pkg/analysis_server/lib/src/services/correction/fix.dart (DartFixKind). Do not edit.',
        '',
        '#![allow(dead_code)]',
        '',
        'use crate::correction::fix_kind::FixKind;',
        '',
    ]
    for name, fid, value, message in kinds:
        lines.append(f'/// Dart `DartFixKind.{name}`.')
        lines.append(f'pub const {snake(name)}: FixKind = FixKind {{ id: {fid!r}, priority: {value}, message: {rust_str(message)} }};'.replace("id: '", 'id: "').replace("', priority", '", priority'))
    lines.append('')
    lines.append('/// All kinds, by Dart name.')
    lines.append('pub const ALL: &[(&str, &FixKind)] = &[')
    for name, *_ in kinds:
        lines.append(f'    ("{name}", &{snake(name)}),')
    lines.append('];')
    open(os.path.join(OUT, 'fix_kinds.rs'), 'w').write('\n'.join(lines) + '\n')
    return len(kinds)


def rust_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def parse_map(text, var):
    start = text.index(var)
    start = text.index('{', start)
    depth = 0
    for i in range(start, len(text)):
        if text[i] == '{':
            depth += 1
        elif text[i] == '}':
            depth -= 1
            if depth == 0:
                end = i
                break
    body = text[start + 1:end]
    body = re.sub(r'//[^\n]*', '', body)
    entries = []
    for m in re.finditer(r'diag\.(\w+)\s*:\s*\[(.*?)\]', body, re.S):
        producers = [p.strip() for p in m.group(2).split(',') if p.strip()]
        entries.append((m.group(1), producers))
    return entries


def gen_registry():
    text = open(os.path.join(SRC, 'fix_internal.dart')).read()
    maps = [
        ('LINT_PRODUCERS', '_builtInLintGenerators = '),
        ('LINT_MULTI_PRODUCERS', '_builtInLintMultiGenerators = '),
        ('WARNING_PRODUCERS', '_builtInNonLintGenerators = '),
        ('WARNING_MULTI_PRODUCERS', '_builtInNonLintMultiGenerators = '),
        ('PARSE_LINT_PRODUCERS', '_builtInParseLintGenerators = '),
    ]
    lines = [
        '// Generated by tools/codegen/gen_fixes.py from',
        '// pkg/analysis_server/lib/src/services/correction/fix_internal.dart. Do not edit.',
        '',
        '//! The producers of each diagnostic code (by Dart `camelCaseName` of',
        '//! the code), in Dart order. A producer is named like the Dart',
        '//! generator (`AddConst.new`, `ImportLibrary.forType`).',
        '',
    ]
    total = 0
    for const, var in maps:
        entries = parse_map(text, var)
        total += len(entries)
        lines.append(f'pub const {const}: &[(&str, &[&str])] = &[')
        for code, producers in entries:
            ps = ', '.join(rust_str(p) for p in producers)
            lines.append(f'    ({rust_str(code)}, &[{ps}]),')
        lines.append('];')
        lines.append('')
    open(os.path.join(OUT, 'fix_registry.rs'), 'w').write('\n'.join(lines))
    return total


if __name__ == '__main__':
    print('kinds', gen_kinds())
    print('registry entries', gen_registry())
