#!/usr/bin/env python3
"""Generates the node dispatch of crates/dartr_resolver from the AST schema.

Input: crates/dartr_ast/schema/ast.json (see tools/codegen/gen_ast.py).

Output: crates/dartr_resolver/src/generated/dispatch.rs. Run from the
repository root:

    python3 tools/codegen/gen_resolver_dispatch.py

The Dart `ResolverVisitor` is a `ThrowingAstVisitor`: it has one `visitX`
method per node class, and expressions get a context type
(`ExpressionImpl.resolveExpression(resolver, contextType)` calls
`resolver.visitX(this, contextType: contextType)`). The generated code is the
double dispatch:

- `visit_node(node)`: Dart `node.accept(resolver)`. Expressions get the
  context type `UnknownInferredType` (the Dart default value of the named
  parameter `contextType`).
- `resolve_expression_dispatch(node, context)`: Dart
  `node.resolveExpression(resolver, contextType)`.
- `resolve_collection_element_dispatch(node, context)`: Dart
  `CollectionElementImpl.resolveElement(resolver, context)`.
- `resolve_pattern_dispatch` / `compute_pattern_schema_dispatch`: Dart
  `DartPatternImpl.resolvePattern` / `computePatternSchema`.

Every `visit_x` method is hand-written in `src/resolver/*.rs`.
"""
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SCHEMA = os.path.join(ROOT, 'crates/dartr_ast/schema/ast.json')
OUT = os.path.join(ROOT, 'crates/dartr_resolver/src/generated/dispatch.rs')

# Nodes that are not part of the syntax tree (see tools/codegen/gen_ast.py).
SKIP_NODES = {'ConstantContextForExpression'}


def snake(name):
    s = re.sub(r'(?<=[a-z0-9])([A-Z])', r'_\1', name)
    s = re.sub(r'([A-Z]+)([A-Z][a-z])', r'\1_\2', s)
    return s.lower()


def main():
    schema = json.load(open(SCHEMA))
    nodes = sorted((n for n in schema['nodes'] if n['name'] not in SKIP_NODES), key=lambda n: n['name'])
    expressions = [n['name'] for n in nodes if 'ExpressionImpl' in n['impl_supertypes']]
    patterns = [n['name'] for n in nodes if 'DartPatternImpl' in n['impl_supertypes']]
    # The collection elements that are not expressions (Dart classes that
    # mix in `CollectionElementImpl`; the schema does not list mixins).
    collection_elements = ['ForElement', 'IfElement', 'MapLiteralEntry', 'NullAwareElement', 'SpreadElement']

    out = []
    w = out.append
    w('// GENERATED FILE. DO NOT EDIT.')
    w('// Generated by tools/codegen/gen_resolver_dispatch.py from crates/dartr_ast/schema/ast.json.')
    w('// Dart source: pkg/analyzer/lib/src/dart/ast/ast.dart (accept, resolveExpression,')
    w('// resolveElement, resolvePattern, computePatternSchema)')
    w('')
    w('//! The double dispatch of [`ResolverVisitor`] over the node kinds.')
    w('')
    w('#![allow(clippy::all)]')
    w('')
    w('use dartr_ast::{CollectionElement, DartPattern, Expression, Id, NodeId, NodeKind};')
    w('use dartr_element::TypeId;')
    w('')
    w('use crate::resolver::{CollectionLiteralContext, PatternResultOf, ResolverVisitor, SchemaOf, SharedMatchContext};')
    w('')
    w('/// The node kinds that are expressions (Dart `ExpressionImpl` subclasses).')
    w('pub const EXPRESSION_KINDS: [NodeKind; %d] = [' % len(expressions))
    for e in expressions:
        w('    NodeKind::%s,' % e)
    w('];')
    w('')
    w('/// The node kinds that are patterns (Dart `DartPatternImpl` subclasses).')
    w('pub const PATTERN_KINDS: [NodeKind; %d] = [' % len(patterns))
    for e in patterns:
        w('    NodeKind::%s,' % e)
    w('];')
    w('')
    w("impl<'a> ResolverVisitor<'a> {")
    w('    /// Dart `node.accept(resolver)`: calls the `visit_x` method of the')
    w('    /// kind of [node]. Expressions get the context type `_`')
    w('    /// (`UnknownInferredType`).')
    w('    pub fn visit_node(&mut self, node: NodeId) {')
    w('        match self.ast.kind(node) {')
    for n in nodes:
        name = n['name']
        if name in expressions:
            w('            NodeKind::%s => self.visit_%s(Id::from_raw(node), TypeId::UNKNOWN),' % (name, snake(name)))
        else:
            w('            NodeKind::%s => self.visit_%s(Id::from_raw(node)),' % (name, snake(name)))
    w('        }')
    w('    }')
    w('')
    w('    /// Dart `ExpressionImpl.resolveExpression(resolver, contextType)`.')
    w('    pub(crate) fn resolve_expression_dispatch(&mut self, node: Id<Expression>, context: TypeId) {')
    w('        let raw = node.raw();')
    w('        match self.ast.kind(raw) {')
    for name in expressions:
        w('            NodeKind::%s => self.visit_%s(Id::from_raw(raw), context),' % (name, snake(name)))
    w('            kind => unreachable!("not an expression: {kind:?}"),')
    w('        }')
    w('    }')
    w('')
    w('    /// Dart `CollectionElementImpl.resolveElement(resolver, context)`.')
    w('    pub(crate) fn resolve_collection_element_dispatch(')
    w('        &mut self,')
    w('        node: Id<CollectionElement>,')
    w('        context: Option<CollectionLiteralContext>,')
    w('    ) {')
    w('        let raw = node.raw();')
    w('        match self.ast.kind(raw) {')
    for name in collection_elements:
        w('            NodeKind::%s => self.resolve_element_%s(Id::from_raw(raw), context),' % (name, snake(name)))
    w('            _ => self.resolve_element_expression(Id::from_raw(raw), context),')
    w('        }')
    w('    }')
    w('')
    w('    /// Dart `DartPatternImpl.resolvePattern(resolver, context)`.')
    w('    pub(crate) fn resolve_pattern_dispatch(')
    w('        &mut self,')
    w('        node: Id<DartPattern>,')
    w('        context: &SharedMatchContext,')
    w("    ) -> PatternResultOf {")
    w('        let raw = node.raw();')
    w('        match self.ast.kind(raw) {')
    for name in patterns:
        w('            NodeKind::%s => self.resolve_pattern_%s(Id::from_raw(raw), context),' % (name, snake(name)))
    w('            kind => unreachable!("not a pattern: {kind:?}"),')
    w('        }')
    w('    }')
    w('')
    w('    /// Dart `DartPatternImpl.computePatternSchema(resolver)`.')
    w('    pub(crate) fn compute_pattern_schema_dispatch(&mut self, node: Id<DartPattern>) -> SchemaOf {')
    w('        let raw = node.raw();')
    w('        match self.ast.kind(raw) {')
    for name in patterns:
        w('            NodeKind::%s => self.compute_pattern_schema_%s(Id::from_raw(raw)),' % (name, snake(name)))
    w('            kind => unreachable!("not a pattern: {kind:?}"),')
    w('        }')
    w('    }')
    w('}')
    w('')
    w('/// Whether [kind] is an expression kind.')
    w('pub fn is_expression_kind(kind: NodeKind) -> bool {')
    w('    EXPRESSION_KINDS.contains(&kind)')
    w('}')
    w('')
    w('/// The unused raw id helper keeps `NodeId` imported for the match arms.')
    w('#[allow(dead_code)]')
    w('fn _raw(id: NodeId) -> NodeId {')
    w('    id')
    w('}')
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w') as f:
        f.write('\n'.join(out) + '\n')


if __name__ == '__main__':
    main()
