// Generated by extract.py from pkg/analyzer/test/src/diagnostics/*_test.dart
// (assertErrorsInCode / assertNoErrorsInCode cases with a single file).

pub static CASES: &[Case] = &[
    Case {
        file: "assignment_to_const_test.dart",
        name: "test_instanceVariable",
        source: r####"class A {
  static const v = 0;
}
f() {
  A.v = 1;
}"####,
        expected: &[("assignmentToConst", 44, 1)],
    },
    Case {
        file: "assignment_to_const_test.dart",
        name: "test_instanceVariable_plusEq",
        source: r####"class A {
  static const v = 0;
}
f() {
  A.v += 1;
}"####,
        expected: &[("assignmentToConst", 44, 1)],
    },
    Case {
        file: "assignment_to_const_test.dart",
        name: "test_localVariable",
        source: r####"f() {
  const x = 0;
  x = 1;
}"####,
        expected: &[("assignmentToConst", 23, 1)],
    },
    Case {
        file: "assignment_to_const_test.dart",
        name: "test_localVariable_plusEq",
        source: r####"f() {
  const x = 0;
  x += 1;
}"####,
        expected: &[("assignmentToConst", 23, 1)],
    },
    Case {
        file: "assignment_to_final_no_setter_test.dart",
        name: "test_prefixedIdentifier_class_instanceGetter",
        source: r####"class A {
  int get x => 0;
}

void f(A a) {
  a.x = 0;
  a.x += 0;
  ++a.x;
  a.x++;
}
"####,
        expected: &[("assignmentToFinalNoSetter", 49, 1), ("assignmentToFinalNoSetter", 60, 1), ("assignmentToFinalNoSetter", 74, 1), ("assignmentToFinalNoSetter", 81, 1)],
    },
    Case {
        file: "assignment_to_final_no_setter_test.dart",
        name: "test_propertyAccess_class_instanceGetter",
        source: r####"class A {
  int get x => 0;
}

void f(A a) {
  (a).x = 0;
  (a).x += 0;
  ++(a).x;
  (a).x++;
}
"####,
        expected: &[("assignmentToFinalNoSetter", 51, 1), ("assignmentToFinalNoSetter", 64, 1), ("assignmentToFinalNoSetter", 80, 1), ("assignmentToFinalNoSetter", 89, 1)],
    },
    Case {
        file: "assignment_to_final_no_setter_test.dart",
        name: "test_propertyAccess_extension_instanceGetter",
        source: r####"extension E on int {
  int get x => 0;
}

void f() {
  0.x = 0;
  0.x += 0;
  ++0.x;
  0.x++;
}
"####,
        expected: &[("assignmentToFinalNoSetter", 57, 1), ("assignmentToFinalNoSetter", 68, 1), ("assignmentToFinalNoSetter", 82, 1), ("assignmentToFinalNoSetter", 89, 1)],
    },
    Case {
        file: "assignment_to_final_test.dart",
        name: "test_prefixedIdentifier_instanceField",
        source: r####"class A {
  var x = 0;
}

void f(A a) {
  a.x = 0;
  a.x += 0;
  ++a.x;
  a.x++;
}
"####,
        expected: &[],
    },
    Case {
        file: "assignment_to_final_test.dart",
        name: "test_prefixedIdentifier_instanceField_abstract",
        source: r####"abstract class A {
  abstract int x;
}

void f(A a) {
  a.x = 0;
  a.x += 0;
  ++a.x;
  a.x++;
}
"####,
        expected: &[],
    },
    Case {
        file: "assignment_to_final_test.dart",
        name: "test_prefixedIdentifier_instanceField_abstractFinal",
        source: r####"abstract class A {
  abstract final int x;
}

void f(A a) {
  a.x = 0;
  a.x += 0;
  ++a.x;
  a.x++;
}
"####,
        expected: &[("assignmentToFinal", 64, 1), ("assignmentToFinal", 75, 1), ("assignmentToFinal", 89, 1), ("assignmentToFinal", 96, 1)],
    },
    Case {
        file: "assignment_to_final_test.dart",
        name: "test_prefixedIdentifier_instanceField_external",
        source: r####"abstract class A {
  external int x;
}

void f(A a) {
  a.x = 0;
  a.x += 0;
  ++a.x;
  a.x++;
}
"####,
        expected: &[],
    },
    Case {
        file: "assignment_to_final_test.dart",
        name: "test_prefixedIdentifier_instanceField_externalFinal",
        source: r####"abstract class A {
  external final int x;
}

void f(A a) {
  a.x = 0;
  a.x += 0;
  ++a.x;
  a.x++;
}
"####,
        expected: &[("assignmentToFinal", 64, 1), ("assignmentToFinal", 75, 1), ("assignmentToFinal", 89, 1), ("assignmentToFinal", 96, 1)],
    },
    Case {
        file: "assignment_to_final_test.dart",
        name: "test_prefixedIdentifier_instanceField_final",
        source: r####"class A {
  final x = 0;
}

void f(A a) {
  a.x = 0;
  a.x += 0;
  ++a.x;
  a.x++;
}
"####,
        expected: &[("assignmentToFinal", 46, 1), ("assignmentToFinal", 57, 1), ("assignmentToFinal", 71, 1), ("assignmentToFinal", 78, 1)],
    },
    Case {
        file: "assignment_to_final_test.dart",
        name: "test_prefixedIdentifier_instanceField_lateFinal",
        source: r####"abstract class A {
  late final int x;
}

void f(A a) {
  a.x = 0;
  a.x += 0;
  ++a.x;
  a.x++;
}
"####,
        expected: &[],
    },
    Case {
        file: "assignment_to_final_test.dart",
        name: "test_prefixedIdentifier_instanceField_lateFinal_hasInitializer",
        source: r####"abstract class A {
  late final int x = 0;
}

void f(A a) {
  a.x = 0;
  a.x += 0;
  ++a.x;
  a.x++;
}
"####,
        expected: &[("assignmentToFinal", 64, 1), ("assignmentToFinal", 75, 1), ("assignmentToFinal", 89, 1), ("assignmentToFinal", 96, 1)],
    },
    Case {
        file: "assignment_to_final_test.dart",
        name: "test_prefixedIdentifier_staticField_externalFinal",
        source: r####"abstract class A {
  external static final int x;
}

void f() {
  A.x = 0;
  A.x += 0;
  ++A.x;
  A.x++;
}
"####,
        expected: &[("assignmentToFinal", 68, 1), ("assignmentToFinal", 79, 1), ("assignmentToFinal", 93, 1), ("assignmentToFinal", 100, 1)],
    },
    Case {
        file: "assignment_to_final_test.dart",
        name: "test_prefixedIdentifier_staticField_lateFinal",
        source: r####"abstract class A {
  static late final int x;
}

void f() {
  A.x = 0;
  A.x += 0;
  ++A.x;
  A.x++;
}
"####,
        expected: &[],
    },
    Case {
        file: "assignment_to_final_test.dart",
        name: "test_prefixedIdentifier_staticField_lateFinal_hasInitializer",
        source: r####"abstract class A {
  static late final int x = 0;
}

void f() {
  A.x = 0;
  A.x += 0;
  ++A.x;
  A.x++;
}
"####,
        expected: &[("assignmentToFinal", 68, 1), ("assignmentToFinal", 79, 1), ("assignmentToFinal", 93, 1), ("assignmentToFinal", 100, 1)],
    },
    Case {
        file: "assignment_to_final_test.dart",
        name: "test_propertyAccess_instanceField_lateFinal",
        source: r####"abstract class A {
  late final int x;
}

void f(A a) {
  (a).x = 0;
  (a).x += 0;
  ++(a).x;
  (a).x++;
}
"####,
        expected: &[],
    },
    Case {
        file: "assignment_to_final_test.dart",
        name: "test_propertyAccess_instanceField_lateFinal_hasInitializer",
        source: r####"abstract class A {
  late final int x = 0;
}

void f(A a) {
  (a).x = 0;
  (a).x += 0;
  ++(a).x;
  (a).x++;
}
"####,
        expected: &[("assignmentToFinal", 66, 1), ("assignmentToFinal", 79, 1), ("assignmentToFinal", 95, 1), ("assignmentToFinal", 104, 1)],
    },
    Case {
        file: "assignment_to_final_test.dart",
        name: "test_simpleIdentifier_topLevelGetter",
        source: r####"int get x => 0;

void f() {
  x = 0;
  x += 0;
  ++x;
  x++;
}
"####,
        expected: &[("assignmentToFinal", 30, 1), ("assignmentToFinal", 39, 1), ("assignmentToFinal", 51, 1), ("assignmentToFinal", 56, 1)],
    },
    Case {
        file: "assignment_to_final_test.dart",
        name: "test_simpleIdentifier_topLevelVariable",
        source: r####"var x = 0;

void f() {
  x = 0;
  x += 0;
  ++x;
  x++;
}
"####,
        expected: &[],
    },
    Case {
        file: "assignment_to_final_test.dart",
        name: "test_simpleIdentifier_topLevelVariable_external",
        source: r####"external int x;

void f() {
  x = 0;
  x += 0;
  ++x;
  x++;
}
"####,
        expected: &[],
    },
    Case {
        file: "assignment_to_final_test.dart",
        name: "test_simpleIdentifier_topLevelVariable_externalFinal",
        source: r####"external final x;

void f() {
  x = 0;
  x += 0;
  ++x;
  x++;
}
"####,
        expected: &[("assignmentToFinal", 32, 1), ("assignmentToFinal", 41, 1), ("assignmentToFinal", 53, 1), ("assignmentToFinal", 58, 1)],
    },
    Case {
        file: "assignment_to_final_test.dart",
        name: "test_simpleIdentifier_topLevelVariable_final",
        source: r####"final x = 0;

void f() {
  x = 0;
  x += 0;
  ++x;
  x++;
}
"####,
        expected: &[("assignmentToFinal", 27, 1), ("assignmentToFinal", 36, 1), ("assignmentToFinal", 48, 1), ("assignmentToFinal", 53, 1)],
    },
    Case {
        file: "assignment_to_final_test.dart",
        name: "test_simpleIdentifier_topLevelVariable_lateFinal",
        source: r####"late final int x;

void f() {
  x = 0;
  x += 0;
  ++x;
  x++;
}
"####,
        expected: &[],
    },
    Case {
        file: "assignment_to_final_test.dart",
        name: "test_simpleIdentifier_topLevelVariable_lateFinal_hasInitializer",
        source: r####"late final int x = 0;

void f() {
  x = 0;
  x += 0;
  ++x;
  x++;
}
"####,
        expected: &[("assignmentToFinal", 36, 1), ("assignmentToFinal", 45, 1), ("assignmentToFinal", 57, 1), ("assignmentToFinal", 62, 1)],
    },
    Case {
        file: "assignment_to_function_test.dart",
        name: "test_function",
        source: r####"f() {}
main() {
  f = null;
}"####,
        expected: &[("assignmentToFunction", 18, 1)],
    },
    Case {
        file: "assignment_to_method_test.dart",
        name: "test_instance_extendedHasMethod_extensionHasSetter",
        source: r####"class C {
  void foo() {}
}

extension E on C {
  void set foo(int _) {}
}

void f(C c) {
  c.foo = 0;
  c.foo += 1;
  c.foo++;
  --c.foo;
}
"####,
        expected: &[("assignmentToMethod", 94, 3), ("assignmentToMethod", 107, 3), ("assignmentToMethod", 121, 3), ("assignmentToMethod", 134, 3)],
    },
    Case {
        file: "assignment_to_method_test.dart",
        name: "test_prefixedIdentifier_instanceMethod",
        source: r####"class A {
  void foo() {}
}

void f(A a) {
  a.foo = 0;
  a.foo += 1;
  a.foo++;
  ++a.foo;
}
"####,
        expected: &[("assignmentToMethod", 47, 3), ("assignmentToMethod", 60, 3), ("assignmentToMethod", 74, 3), ("assignmentToMethod", 87, 3)],
    },
    Case {
        file: "assignment_to_method_test.dart",
        name: "test_propertyAccess_instanceMethod",
        source: r####"class A {
  void foo() {}
}

void f(A a) {
  (a).foo = 0;
  (a).foo += 1;
  (a).foo++;
  ++(a).foo;
}
"####,
        expected: &[("assignmentToMethod", 49, 3), ("assignmentToMethod", 64, 3), ("assignmentToMethod", 80, 3), ("assignmentToMethod", 95, 3)],
    },
    Case {
        file: "assignment_to_type_test.dart",
        name: "test_class",
        source: r####"class C {}
main() {
  C = null;
}
"####,
        expected: &[("assignmentToType", 22, 1)],
    },
    Case {
        file: "assignment_to_type_test.dart",
        name: "test_dynamic",
        source: r####"void f() {
  dynamic = 1;
}
"####,
        expected: &[("assignmentToType", 13, 7)],
    },
    Case {
        file: "assignment_to_type_test.dart",
        name: "test_enum",
        source: r####"enum E { e }
main() {
  E = null;
}
"####,
        expected: &[("assignmentToType", 24, 1)],
    },
    Case {
        file: "assignment_to_type_test.dart",
        name: "test_typedef_functionType",
        source: r####"typedef void F();
main() {
  F = null;
}
"####,
        expected: &[("assignmentToType", 29, 1)],
    },
    Case {
        file: "assignment_to_type_test.dart",
        name: "test_typedef_interfaceType",
        source: r####"typedef F = List<int>;

void f() {
  F = null;
}
"####,
        expected: &[("assignmentToType", 37, 1)],
    },
    Case {
        file: "expected_one_list_type_arguments_test.dart",
        name: "test_one_type_argument",
        source: r####"main() {
  <int> [];
}
"####,
        expected: &[],
    },
    Case {
        file: "expected_one_list_type_arguments_test.dart",
        name: "test_two_type_arguments",
        source: r####"main() {
  <int, int>[];
}"####,
        expected: &[("expectedOneListTypeArguments", 11, 10)],
    },
    Case {
        file: "expected_one_set_type_arguments_test.dart",
        name: "test_multiple_type_arguments",
        source: r####"main() {
  <int, int, int>{2, 3};
}"####,
        expected: &[("expectedOneSetTypeArguments", 11, 15)],
    },
    Case {
        file: "expected_two_map_type_arguments_test.dart",
        name: "test_three_type_arguments_ambiguous",
        source: r####"main() {
  <int, int, int>{};
}"####,
        expected: &[("expectedTwoMapTypeArguments", 11, 15)],
    },
    Case {
        file: "expected_two_map_type_arguments_test.dart",
        name: "test_three_type_arguments_map",
        source: r####"main() {
  <int, int, int>{1: 2};
}"####,
        expected: &[("expectedTwoMapTypeArguments", 11, 15)],
    },
    Case {
        file: "expected_two_map_type_arguments_test.dart",
        name: "test_two_type_arguments",
        source: r####"main() {
  <int, int> {};
}
"####,
        expected: &[],
    },
    Case {
        file: "expression_in_map_test.dart",
        name: "test_map",
        source: r####"var m = <String, int>{'a', 'b' : 2};
"####,
        expected: &[("expressionInMap", 22, 3)],
    },
    Case {
        file: "expression_in_map_test.dart",
        name: "test_map_const",
        source: r####"const m = <String, int>{'a', 'b' : 2};
"####,
        expected: &[("expressionInMap", 24, 3)],
    },
    Case {
        file: "illegal_async_generator_return_type_test.dart",
        name: "test_function_nonStream",
        source: r####"int f() async* {}
"####,
        expected: &[("illegalAsyncGeneratorReturnType", 0, 3)],
    },
    Case {
        file: "illegal_async_generator_return_type_test.dart",
        name: "test_function_stream",
        source: r####"Stream<void> f() async* {}
"####,
        expected: &[],
    },
    Case {
        file: "illegal_async_generator_return_type_test.dart",
        name: "test_function_subtypeOfStream",
        source: r####"abstract class SubStream<T> implements Stream<T> {}
SubStream<int> f() async* {}
"####,
        expected: &[("illegalAsyncGeneratorReturnType", 52, 14)],
    },
    Case {
        file: "illegal_async_generator_return_type_test.dart",
        name: "test_function_void",
        source: r####"void f() async* {}
"####,
        expected: &[("illegalAsyncGeneratorReturnType", 0, 4)],
    },
    Case {
        file: "illegal_async_generator_return_type_test.dart",
        name: "test_method_nonStream",
        source: r####"class C {
  int f() async* {}
}
"####,
        expected: &[("illegalAsyncGeneratorReturnType", 12, 3)],
    },
    Case {
        file: "illegal_async_generator_return_type_test.dart",
        name: "test_method_subtypeOfStream",
        source: r####"abstract class SubStream<T> implements Stream<T> {}
class C {
  SubStream<int> f() async* {}
}
"####,
        expected: &[("illegalAsyncGeneratorReturnType", 64, 14)],
    },
    Case {
        file: "illegal_async_generator_return_type_test.dart",
        name: "test_method_void",
        source: r####"class C {
  void f() async* {}
}
"####,
        expected: &[("illegalAsyncGeneratorReturnType", 12, 4)],
    },
    Case {
        file: "illegal_async_return_type_test.dart",
        name: "test_function_nonFuture",
        source: r####"int f() async {
  return 1;
}
"####,
        expected: &[("illegalAsyncReturnType", 0, 3)],
    },
    Case {
        file: "illegal_async_return_type_test.dart",
        name: "test_function_nonFuture_void",
        source: r####"void f() async {}
"####,
        expected: &[],
    },
    Case {
        file: "illegal_async_return_type_test.dart",
        name: "test_function_nonFuture_withReturn",
        source: r####"int f() async {
  return 2;
}
"####,
        expected: &[("illegalAsyncReturnType", 0, 3)],
    },
    Case {
        file: "illegal_async_return_type_test.dart",
        name: "test_function_subtypeOfFuture",
        source: r####"abstract class SubFuture<T> implements Future<T> {}
SubFuture<int> f() async {
  return 0;
}
"####,
        expected: &[("illegalAsyncReturnType", 52, 14)],
    },
    Case {
        file: "illegal_async_return_type_test.dart",
        name: "test_method_nonFuture_void",
        source: r####"class C {
  void m() async {}
}
"####,
        expected: &[],
    },
    Case {
        file: "illegal_sync_generator_return_type_test.dart",
        name: "test_function_iterator",
        source: r####"Iterable<void> f() sync* {}
"####,
        expected: &[],
    },
    Case {
        file: "illegal_sync_generator_return_type_test.dart",
        name: "test_function_nonIterator",
        source: r####"int f() sync* {}
"####,
        expected: &[("illegalSyncGeneratorReturnType", 0, 3)],
    },
    Case {
        file: "illegal_sync_generator_return_type_test.dart",
        name: "test_function_subclassOfIterator",
        source: r####"abstract class SubIterator<T> implements Iterator<T> {}
SubIterator<int> f() sync* {}
"####,
        expected: &[("illegalSyncGeneratorReturnType", 56, 16)],
    },
    Case {
        file: "illegal_sync_generator_return_type_test.dart",
        name: "test_function_void",
        source: r####"void f() sync* {}
"####,
        expected: &[("illegalSyncGeneratorReturnType", 0, 4)],
    },
    Case {
        file: "illegal_sync_generator_return_type_test.dart",
        name: "test_method_nonIterator",
        source: r####"class C {
  int f() sync* {}
}
"####,
        expected: &[("illegalSyncGeneratorReturnType", 12, 3)],
    },
    Case {
        file: "illegal_sync_generator_return_type_test.dart",
        name: "test_method_subclassOfIterator",
        source: r####"abstract class SubIterator<T> implements Iterator<T> {}
class C {
  SubIterator<int> f() sync* {}
}
"####,
        expected: &[("illegalSyncGeneratorReturnType", 68, 16)],
    },
    Case {
        file: "illegal_sync_generator_return_type_test.dart",
        name: "test_method_void",
        source: r####"class C {
  void f() sync* {}
}
"####,
        expected: &[("illegalSyncGeneratorReturnType", 12, 4)],
    },
    Case {
        file: "list_element_type_not_assignable_test.dart",
        name: "test_const_intInt",
        source: r####"var v1 = <int> [42];
var v2 = const <int> [42];
"####,
        expected: &[],
    },
    Case {
        file: "missing_required_param_test.dart",
        name: "test_annotation_noImportPrefix_named",
        source: r####"class A {
  const A.named({required int a});
}

@A.named()
void f() {}
"####,
        expected: &[("missingRequiredArgument", 51, 5)],
    },
    Case {
        file: "missing_required_param_test.dart",
        name: "test_annotation_noImportPrefix_unnamed",
        source: r####"class A {
  const A({required int a});
}

@A()
void f() {}
"####,
        expected: &[("missingRequiredArgument", 43, 1)],
    },
    Case {
        file: "missing_required_param_test.dart",
        name: "test_constructor_argumentGiven",
        source: r####"class C {
  C({required int a}) {}
}

main() {
  new C(a: 2);
}
"####,
        expected: &[],
    },
    Case {
        file: "missing_required_param_test.dart",
        name: "test_constructor_missingArgument",
        source: r####"class C {
  C({required int a}) {}
}
main() {
  new C();
}
"####,
        expected: &[("missingRequiredArgument", 52, 1)],
    },
    Case {
        file: "missing_required_param_test.dart",
        name: "test_constructor_redirectingConstructorCall",
        source: r####"class C {
  C({required int x});
  C.named() : this();
}
"####,
        expected: &[("missingRequiredArgument", 47, 6)],
    },
    Case {
        file: "missing_required_param_test.dart",
        name: "test_constructor_superCall",
        source: r####"class C {
  C({required int a}) {}
}

class D extends C {
  D() : super();
}
"####,
        expected: &[("missingRequiredArgument", 66, 7)],
    },
    Case {
        file: "missing_required_param_test.dart",
        name: "test_constructor_superFormalParameter",
        source: r####"class A {
  A({required int a});
}

class B extends A {
  B({required super.a}) : super();
}
"####,
        expected: &[],
    },
    Case {
        file: "missing_required_param_test.dart",
        name: "test_enumConstant_withArguments",
        source: r####"enum E {
  v();
  const E({required int a});
}
"####,
        expected: &[("missingRequiredArgument", 11, 1)],
    },
    Case {
        file: "missing_required_param_test.dart",
        name: "test_enumConstant_withoutArguments",
        source: r####"enum E {
  v;
  const E({required int a});
}
"####,
        expected: &[("missingRequiredArgument", 11, 1)],
    },
    Case {
        file: "missing_required_param_test.dart",
        name: "test_function",
        source: r####"void f({required int a}) {}

main() {
  f();
}
"####,
        expected: &[("missingRequiredArgument", 40, 1)],
    },
    Case {
        file: "missing_required_param_test.dart",
        name: "test_function_call",
        source: r####"void f({required int a}) {}

main() {
  f.call();
}
"####,
        expected: &[("missingRequiredArgument", 46, 2)],
    },
    Case {
        file: "missing_required_param_test.dart",
        name: "test_functionInvocation",
        source: r####"void Function({required int a}) f() => throw '';
g() {
  f()();
}
"####,
        expected: &[("missingRequiredArgument", 57, 5)],
    },
    Case {
        file: "missing_required_param_test.dart",
        name: "test_method",
        source: r####"class A {
  void m({required int a}) {}
}
f() {
  new A().m();
}
"####,
        expected: &[("missingRequiredArgument", 58, 1)],
    },
    Case {
        file: "missing_required_param_test.dart",
        name: "test_typedef_function",
        source: r####"String test(C c) => c.m()();

typedef String F({required String x});

class C {
  F m() => ({required String x}) => throw '';
}
"####,
        expected: &[("missingRequiredArgument", 20, 7)],
    },
    Case {
        file: "positional_super_formal_parameter_with_positional_argument_test.dart",
        name: "test_primaryConstructor_notReported",
        source: r####"class A {
  A(int a);
}

class B(super.a) extends A {
  this : super();
}
"####,
        expected: &[],
    },
    Case {
        file: "positional_super_formal_parameter_with_positional_argument_test.dart",
        name: "test_primaryConstructor_reported",
        source: r####"class A {
  A(int a, int b);
}

class B(super.a) extends A {
  this : super(0);
}
"####,
        expected: &[("positionalSuperFormalParameterWithPositionalArgument", 46, 1)],
    },
    Case {
        file: "positional_super_formal_parameter_with_positional_argument_test.dart",
        name: "test_secondaryConstructor_notReported",
        source: r####"class A {
  A(int a);
}

class B extends A {
  B(super.a) : super();
}
"####,
        expected: &[],
    },
    Case {
        file: "positional_super_formal_parameter_with_positional_argument_test.dart",
        name: "test_secondaryConstructor_reported",
        source: r####"class A {
  A(int a, int b);
}

class B extends A {
  B(super.b) : super(0);
}
"####,
        expected: &[("positionalSuperFormalParameterWithPositionalArgument", 62, 1)],
    },
    Case {
        file: "record_literal_one_positional_no_trailing_comma_test.dart",
        name: "test_argument_parenthesized",
        source: r####"void f((int,) i) {
  f((1));
}
"####,
        expected: &[("recordLiteralOnePositionalNoTrailingCommaByType", 23, 3)],
    },
    Case {
        file: "record_literal_one_positional_no_trailing_comma_test.dart",
        name: "test_argument_valid",
        source: r####"void f((int,) i) {
  f((1,));
}
"####,
        expected: &[],
    },
    Case {
        file: "record_literal_one_positional_no_trailing_comma_test.dart",
        name: "test_assignment_parenthesized",
        source: r####"void f((int,) r) {
  r = (1);
}
"####,
        expected: &[("recordLiteralOnePositionalNoTrailingCommaByType", 25, 3)],
    },
    Case {
        file: "record_literal_one_positional_no_trailing_comma_test.dart",
        name: "test_assignment_valid",
        source: r####"void f((int,) r) {
  r = (1,);
}
"####,
        expected: &[],
    },
    Case {
        file: "record_literal_one_positional_no_trailing_comma_test.dart",
        name: "test_declaration",
        source: r####"(int,) r = (1);
"####,
        expected: &[("recordLiteralOnePositionalNoTrailingCommaByType", 11, 3)],
    },
    Case {
        file: "record_literal_one_positional_no_trailing_comma_test.dart",
        name: "test_declaration_valid",
        source: r####"(int,) r = (1,);
"####,
        expected: &[],
    },
    Case {
        file: "record_literal_one_positional_no_trailing_comma_test.dart",
        name: "test_return_blockBody_notParenthesized",
        source: r####"(int,) f() {
  return 1;
}
"####,
        expected: &[("returnOfInvalidTypeFromFunction", 22, 1)],
    },
    Case {
        file: "record_literal_one_positional_no_trailing_comma_test.dart",
        name: "test_return_blockBody_parenthesized",
        source: r####"(int,) f() {
  return (1);
}
"####,
        expected: &[("recordLiteralOnePositionalNoTrailingCommaByType", 22, 3)],
    },
    Case {
        file: "record_literal_one_positional_no_trailing_comma_test.dart",
        name: "test_return_expressionBody_invalid",
        source: r####"(int,) f() => ('');
"####,
        expected: &[("returnOfInvalidTypeFromFunction", 14, 4)],
    },
    Case {
        file: "record_literal_one_positional_no_trailing_comma_test.dart",
        name: "test_return_expressionBody_notParenthesized",
        source: r####"(int,) f() => 1;
"####,
        expected: &[("returnOfInvalidTypeFromFunction", 14, 1)],
    },
    Case {
        file: "record_literal_one_positional_no_trailing_comma_test.dart",
        name: "test_return_expressionBody_parenthesized",
        source: r####"(int,) f() => (1);
"####,
        expected: &[("recordLiteralOnePositionalNoTrailingCommaByType", 14, 3)],
    },
    Case {
        file: "record_literal_one_positional_no_trailing_comma_test.dart",
        name: "test_return_invalid",
        source: r####"(int,) f() { return (''); }
"####,
        expected: &[("returnOfInvalidTypeFromFunction", 20, 4)],
    },
    Case {
        file: "record_literal_one_positional_no_trailing_comma_test.dart",
        name: "test_return_valid",
        source: r####"(int,) f() { return (1,); }
"####,
        expected: &[],
    },
    Case {
        file: "return_in_generative_constructor_test.dart",
        name: "test_blockBody",
        source: r####"class A {
  A() { return 0; }
}
"####,
        expected: &[("returnInGenerativeConstructor", 25, 1)],
    },
    Case {
        file: "return_in_generative_constructor_test.dart",
        name: "test_expressionFunctionBody",
        source: r####"class A {
  A() => A();
}
"####,
        expected: &[("returnInGenerativeConstructor", 16, 7)],
    },
    Case {
        file: "return_in_generative_constructor_test.dart",
        name: "test_return_without_value",
        source: r####"class A {
  A() { return; }
}
"####,
        expected: &[],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_closure",
        source: r####"typedef Td = int Function();
Td f() {
  return () => "hello";
}
"####,
        expected: &[("returnOfInvalidTypeFromClosure", 53, 7)],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_factoryConstructor_named",
        source: r####"class C {
  factory C.named() => 7;
}
"####,
        expected: &[("returnOfInvalidTypeFromConstructor", 33, 1)],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_factoryConstructor_unnamed",
        source: r####"class C {
  factory C() => 7;
}
"####,
        expected: &[("returnOfInvalidTypeFromConstructor", 27, 1)],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_function_async_block__to_Future_void",
        source: r####"Future<void> f1() async {}
Future<void> f2() async { return; }
Future<void> f3() async { return null; }
Future<void> f4() async { return g1(); }
Future<void> f5() async { return g2(); }
g1() {}
void g2() {}
"####,
        expected: &[],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_function_async_block_Future_Future_int__to_Future_int",
        source: r####"Future<int> f(Future<Future<int>> a) async {
  return a;
}
"####,
        expected: &[("returnOfInvalidTypeFromFunction", 54, 1)],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_function_async_block_Future_String__to_Future_int",
        source: r####"Future<int> f(Future<String> a) async {
  return a;
}
"####,
        expected: &[("returnOfInvalidTypeFromFunction", 49, 1)],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_function_async_block_Future_void",
        source: r####"void f1(Future<void> a) async { return a; }
dynamic f2(Future<void> a) async { return a; }
"####,
        expected: &[],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_function_async_block_illegalReturnType",
        source: r####"int f() async {
  return 5;
}
"####,
        expected: &[("illegalAsyncReturnType", 0, 3)],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_function_async_block_int__to_Future_int",
        source: r####"Future<int> f() async {
  return 0;
}
"####,
        expected: &[],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_function_async_block_int__to_Future_num",
        source: r####"Future<num> f() async {
  return 0;
}
"####,
        expected: &[],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_function_async_block_int__to_Future_String",
        source: r####"Future<String> f() async {
  return 5;
}
"####,
        expected: &[("returnOfInvalidTypeFromFunction", 36, 1)],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_function_async_block_int__to_Future_void",
        source: r####"Future<void> f() async {
  return 0;
}
"####,
        expected: &[("returnOfInvalidTypeFromFunction", 34, 1)],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_function_async_block_int__to_void",
        source: r####"void f() async {
  return 5;
}
"####,
        expected: &[("returnOfInvalidTypeFromFunction", 26, 1)],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_function_async_block_void__to_dynamic",
        source: r####"dynamic f(void a) async {
  return a;
}
"####,
        expected: &[],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_function_async_block_void__to_Future_int",
        source: r####"Future<int> f(void a) async {
  return a;
}
"####,
        expected: &[("returnOfInvalidTypeFromFunction", 39, 1)],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_function_async_block_void__to_Future_Null",
        source: r####"Future<Null> f(void a) async {
  return a;
}
"####,
        expected: &[("returnOfInvalidTypeFromFunction", 40, 1)],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_function_async_block_void__to_FutureOr_ObjectQ",
        source: r####"import 'dart:async';

FutureOr<Object?> f(void a) async {
  return a;
}
"####,
        expected: &[("returnOfInvalidTypeFromFunction", 67, 1)],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_function_async_block_void__to_void",
        source: r####"void f(void a) async {
  return a;
}
"####,
        expected: &[],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_function_async_expression_dynamic__to_Future_int",
        source: r####"Future<int> f(dynamic a) async => a;
"####,
        expected: &[],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_function_sync_block__to_void",
        source: r####"void f1() {}
void f2() { return; }
void f3() { return null; }
void f4() { return g1(); }
void f5() { return g2(); }
g1() {}
void g2() {}
"####,
        expected: &[],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_function_sync_block_genericFunction__to_genericFunction",
        source: r####"U Function<U>(U) foo(T Function<T>(T a) f) {
  return f;
}
"####,
        expected: &[],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_function_sync_block_genericFunction__to_genericFunction_notAssignable",
        source: r####"U Function<U>(U, int) foo(T Function<T>(T a) f) {
  return f;
}
"####,
        expected: &[("returnOfInvalidTypeFromFunction", 59, 1)],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_function_sync_block_genericFunction__to_nonGenericFunction",
        source: r####"int Function(int) foo(T Function<T>(T a) f) {
  return f;
}
"####,
        expected: &[],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_function_sync_block_genericFunction__to_nonGenericFunction_notAssignable",
        source: r####"int Function(int, int) foo(T Function<T>(T a) f) {
  return f;
}
"####,
        expected: &[("returnOfInvalidTypeFromFunction", 60, 1)],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_function_sync_block_int__to_num",
        source: r####"num f(int a) {
  return a;
}
"####,
        expected: &[],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_function_sync_block_int__to_void",
        source: r####"void f() {
  return 42;
}
"####,
        expected: &[("returnOfInvalidTypeFromFunction", 20, 2)],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_function_sync_block_num__to_int",
        source: r####"int f(num a) {
  return a;
}
"####,
        expected: &[("returnOfInvalidTypeFromFunction", 24, 1)],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_function_sync_block_String__to_int",
        source: r####"int f() {
  return '0';
}
"####,
        expected: &[("returnOfInvalidTypeFromFunction", 19, 3)],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_function_sync_block_typeParameter__to_Type",
        source: r####"class Foo<T> {
  Type get t => T;
}
"####,
        expected: &[],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_function_sync_block_void__to_dynamic",
        source: r####"dynamic f(void a) {
  return a;
}
"####,
        expected: &[],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_function_sync_block_void__to_int",
        source: r####"int f(void a) {
  return a;
}
"####,
        expected: &[("returnOfInvalidTypeFromFunction", 25, 1)],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_function_sync_block_void__to_Null",
        source: r####"Null f(void a) {
  return a;
}
"####,
        expected: &[("returnOfInvalidTypeFromFunction", 26, 1)],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_function_sync_block_void__to_void",
        source: r####"void f(void a) {
  return a;
}
"####,
        expected: &[],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_function_sync_expression_genericFunction__to_genericFunction",
        source: r####"U Function<U>(U) foo(T Function<T>(T a) f) => f;
"####,
        expected: &[],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_function_sync_expression_genericFunction__to_genericFunction_notAssignable",
        source: r####"U Function<U>(U, int) foo(T Function<T>(T a) f) => f;
"####,
        expected: &[("returnOfInvalidTypeFromFunction", 51, 1)],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_function_sync_expression_genericFunction__to_nonGenericFunction",
        source: r####"int Function(int) foo(T Function<T>(T a) f) => f;
"####,
        expected: &[],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_function_sync_expression_genericFunction__to_nonGenericFunction_notAssignable",
        source: r####"int Function(int, int) foo(T Function<T>(T a) f) => f;
"####,
        expected: &[("returnOfInvalidTypeFromFunction", 52, 1)],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_function_sync_expression_int__to_void",
        source: r####"void f() => 42;
"####,
        expected: &[],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_function_sync_expression_String__to_int",
        source: r####"int f() => '0';
"####,
        expected: &[("returnOfInvalidTypeFromFunction", 11, 3)],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_functionExpression_async_futureOr_void__to_Object",
        source: r####"void a = null;

Object Function() f = () async {
  return a;
};
"####,
        expected: &[],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_functionExpression_async_futureQ_void__to_Object",
        source: r####"Future<void>? a = (throw 0);

Object Function() f = () async {
  return a;
};
"####,
        expected: &[],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_functionExpression_async_void__to_FutureOr_ObjectQ",
        source: r####"import 'dart:async';

void a = (throw 0);

FutureOr<Object?> Function() f = () async {
  return a;
};
"####,
        expected: &[],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_getter_sync_block_String__to_int",
        source: r####"int get g {
  return '0';
}
"####,
        expected: &[("returnOfInvalidTypeFromFunction", 21, 3)],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_getter_sync_expression_String__to_int",
        source: r####"int get g => '0';
"####,
        expected: &[("returnOfInvalidTypeFromFunction", 13, 3)],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_method_async_block_callable_class",
        source: r####"typedef Fn = void Function(String s);

class CanFn {
  void call(String s) => print(s);
}

Future<Fn> f() async {
  return CanFn();
}
"####,
        expected: &[],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_method_sync_expression_generic",
        source: r####"abstract class F<T>  {
  T get value;
}

abstract class G<U> {
  U test(F<U> arg) => arg.value;
}
"####,
        expected: &[],
    },
    Case {
        file: "return_of_invalid_type_test.dart",
        name: "test_method_sync_expression_String__to_int",
        source: r####"class A {
  int f() => '0';
}
"####,
        expected: &[("returnOfInvalidTypeFromMethod", 23, 3)],
    },
    Case {
        file: "return_without_value_test.dart",
        name: "test_async_futureInt",
        source: r####"Future<int> f() async {
  return;
}
"####,
        expected: &[("returnWithoutValue", 26, 6)],
    },
    Case {
        file: "return_without_value_test.dart",
        name: "test_async_futureObject",
        source: r####"Future<Object> f() async {
  return;
}
"####,
        expected: &[("returnWithoutValue", 29, 6)],
    },
    Case {
        file: "return_without_value_test.dart",
        name: "test_catchError_futureOfVoid",
        source: r####"void f(Future<void> future) {
  future.catchError((e) {
    return;
  });
}
"####,
        expected: &[],
    },
    Case {
        file: "return_without_value_test.dart",
        name: "test_function",
        source: r####"int f() {
  return;
}
"####,
        expected: &[("returnWithoutValue", 12, 6)],
    },
    Case {
        file: "return_without_value_test.dart",
        name: "test_function_async_block_empty__to_dynamic",
        source: r####"dynamic f() async {
  return;
}
"####,
        expected: &[],
    },
    Case {
        file: "return_without_value_test.dart",
        name: "test_function_Null",
        source: r####"Null f() {
  return;
}
"####,
        expected: &[],
    },
    Case {
        file: "return_without_value_test.dart",
        name: "test_function_sync_block_empty__to_dynamic",
        source: r####"dynamic f() {
  return;
}
"####,
        expected: &[],
    },
    Case {
        file: "return_without_value_test.dart",
        name: "test_function_sync_block_empty__to_Null",
        source: r####"Null f() {
  return;
}
"####,
        expected: &[],
    },
    Case {
        file: "return_without_value_test.dart",
        name: "test_function_void",
        source: r####"void f() {
  return;
}
"####,
        expected: &[],
    },
    Case {
        file: "return_without_value_test.dart",
        name: "test_functionExpression",
        source: r####"f() {
  return (int y) {
    if (y < 0) {
      return;
    }
    return 0;
  };
}
"####,
        expected: &[("returnWithoutValue", 48, 6)],
    },
    Case {
        file: "return_without_value_test.dart",
        name: "test_functionExpression_async_block_empty__to_Object",
        source: r####"Object Function() f = () async {
  return;
};
"####,
        expected: &[],
    },
    Case {
        file: "set_element_type_not_assignable_test.dart",
        name: "test_const_ifElement_thenElseFalse_intInt",
        source: r####"const dynamic a = 0;
const dynamic b = 0;
var v = const <int>{if (1 < 0) a else b};
"####,
        expected: &[],
    },
    Case {
        file: "set_element_type_not_assignable_test.dart",
        name: "test_const_ifElement_thenElseFalse_intString",
        source: r####"const dynamic a = 0;
const dynamic b = 'b';
var v = const <int>{if (1 < 0) a else b};
"####,
        expected: &[("setElementTypeNotAssignable", 82, 1)],
    },
    Case {
        file: "set_element_type_not_assignable_test.dart",
        name: "test_const_ifElement_thenFalse_intString",
        source: r####"var v = const <int>{if (1 < 0) 'a'};
"####,
        expected: &[("setElementTypeNotAssignable", 31, 3)],
    },
    Case {
        file: "set_element_type_not_assignable_test.dart",
        name: "test_const_ifElement_thenFalse_intString_dynamic",
        source: r####"const dynamic a = 'a';
var v = const <int>{if (1 < 0) a};
"####,
        expected: &[],
    },
    Case {
        file: "set_element_type_not_assignable_test.dart",
        name: "test_const_ifElement_thenTrue_intInt",
        source: r####"const dynamic a = 0;
var v = const <int>{if (true) a};
"####,
        expected: &[],
    },
    Case {
        file: "set_element_type_not_assignable_test.dart",
        name: "test_const_ifElement_thenTrue_intString",
        source: r####"const dynamic a = 'a';
var v = const <int>{if (true) a};
"####,
        expected: &[("setElementTypeNotAssignable", 53, 1)],
    },
    Case {
        file: "set_element_type_not_assignable_test.dart",
        name: "test_const_intInt_dynamic",
        source: r####"const dynamic a = 42;
var v = const <int>{a};
"####,
        expected: &[],
    },
    Case {
        file: "set_element_type_not_assignable_test.dart",
        name: "test_const_intInt_value",
        source: r####"var v = const <int>{42};
"####,
        expected: &[],
    },
    Case {
        file: "set_element_type_not_assignable_test.dart",
        name: "test_const_intNull_dynamic",
        source: r####"const a = null;
var v = const <int>{a};
"####,
        expected: &[("setElementTypeNotAssignableNullability", 36, 1)],
    },
    Case {
        file: "set_element_type_not_assignable_test.dart",
        name: "test_const_intNull_value",
        source: r####"var v = const <int>{null};
"####,
        expected: &[("setElementTypeNotAssignableNullability", 20, 4)],
    },
    Case {
        file: "set_element_type_not_assignable_test.dart",
        name: "test_const_intString_dynamic",
        source: r####"const dynamic x = 'abc';
var v = const <int>{x};
"####,
        expected: &[("setElementTypeNotAssignable", 45, 1)],
    },
    Case {
        file: "set_element_type_not_assignable_test.dart",
        name: "test_const_intString_value",
        source: r####"var v = const <int>{'abc'};
"####,
        expected: &[("setElementTypeNotAssignable", 20, 5)],
    },
    Case {
        file: "set_element_type_not_assignable_test.dart",
        name: "test_const_spread_intInt",
        source: r####"var v = const <int>{...[0, 1]};
"####,
        expected: &[],
    },
    Case {
        file: "set_element_type_not_assignable_test.dart",
        name: "test_const_stringQuestion_null_dynamic",
        source: r####"const a = null;
var v = const <String?>{a};
"####,
        expected: &[],
    },
    Case {
        file: "set_element_type_not_assignable_test.dart",
        name: "test_const_stringQuestion_null_value",
        source: r####"var v = const <String?>{null};
"####,
        expected: &[],
    },
    Case {
        file: "set_element_type_not_assignable_test.dart",
        name: "test_nonConst_ifElement_thenElseFalse_intDynamic",
        source: r####"const dynamic a = 'a';
const dynamic b = 'b';
var v = <int>{if (1 < 0) a else b};
"####,
        expected: &[],
    },
    Case {
        file: "set_element_type_not_assignable_test.dart",
        name: "test_nonConst_ifElement_thenElseFalse_intInt",
        source: r####"const dynamic a = 0;
const dynamic b = 0;
var v = <int>{if (1 < 0) a else b};
"####,
        expected: &[],
    },
    Case {
        file: "set_element_type_not_assignable_test.dart",
        name: "test_nonConst_ifElement_thenFalse_intString",
        source: r####"var v = <int>[if (1 < 0) 'a'];
"####,
        expected: &[("listElementTypeNotAssignable", 25, 3)],
    },
    Case {
        file: "set_element_type_not_assignable_test.dart",
        name: "test_nonConst_ifElement_thenTrue_intDynamic",
        source: r####"const dynamic a = 'a';
var v = <int>{if (true) a};
"####,
        expected: &[],
    },
    Case {
        file: "set_element_type_not_assignable_test.dart",
        name: "test_nonConst_ifElement_thenTrue_intInt",
        source: r####"const dynamic a = 0;
var v = <int>{if (true) a};
"####,
        expected: &[],
    },
    Case {
        file: "set_element_type_not_assignable_test.dart",
        name: "test_nonConst_spread_intInt",
        source: r####"var v = <int>{...[0, 1]};
"####,
        expected: &[],
    },
    Case {
        file: "set_element_type_not_assignable_test.dart",
        name: "test_notConst_intString_dynamic",
        source: r####"const dynamic x = 'abc';
var v = <int>{x};
"####,
        expected: &[],
    },
    Case {
        file: "set_element_type_not_assignable_test.dart",
        name: "test_notConst_intString_value",
        source: r####"var v = <int>{'abc'};
"####,
        expected: &[("setElementTypeNotAssignable", 14, 5)],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_classTypeAlias",
        source: r####"class A {}
class B {}
mixin C {}
class G<E extends A> {}
class D = G<B> with C;
"####,
        expected: &[("typeArgumentNotMatchingBounds", 69, 1)],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_const",
        source: r####"class A {}
class B {}
class G<E extends A> {
  const G();
}
f() { return const G<B>(); }
"####,
        expected: &[("typeArgumentNotMatchingBounds", 81, 1)],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_const_matching",
        source: r####"class A {}
class B extends A {}
class G<E extends A> {
  const G();
}
f() { return const G<B>(); }
"####,
        expected: &[],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_extends",
        source: r####"class A {}
class B {}
class G<E extends A> {}
class C extends G<B>{}
"####,
        expected: &[("typeArgumentNotMatchingBounds", 64, 1)],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_extends_regressionInIssue18468Fix",
        source: r####"class X<T extends Type> {}
class Y<U> extends X<U> {}
"####,
        expected: &[("typeArgumentNotMatchingBounds", 48, 1)],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_extensionOverride_hasTypeArguments",
        source: r####"extension E<T extends num> on int {
  void foo() {}
}

void f() {
  E<String>(0).foo();
}
"####,
        expected: &[("typeArgumentNotMatchingBounds", 70, 6)],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_extensionOverride_hasTypeArguments_call",
        source: r####"extension E<T extends num> on int {
  void call() {}
}

void f() {
  E<String>(0)();
}
"####,
        expected: &[("typeArgumentNotMatchingBounds", 71, 6)],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_fieldFormalParameter",
        source: r####"class A {}
class B {}
class G<E extends A> {}
class C {
  var f;
  C(G<B> this.f) {}
}
"####,
        expected: &[("typeArgumentNotMatchingBounds", 71, 1)],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_functionExpressionInvocation",
        source: r####"void f() {
  (<T extends num>() {})<String>();
}
"####,
        expected: &[("typeArgumentNotMatchingBounds", 36, 6)],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_functionExpressionInvocation_implicitCall",
        source: r####"class C {
  void call<T extends num>() {}
}

void f(C c) {
  c<String>();
}
"####,
        expected: &[("typeArgumentNotMatchingBounds", 63, 6)],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_functionReturnType",
        source: r####"class A {}
class B {}
class G<E extends A> {}
G<B> f() => throw 0;
"####,
        expected: &[("typeArgumentNotMatchingBounds", 48, 1)],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_functionTypeAlias",
        source: r####"class A {}
class B {}
class G<E extends A> {}
typedef G<B> f();
"####,
        expected: &[("typeArgumentNotMatchingBounds", 56, 1)],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_functionTypedFormalParameter",
        source: r####"class A {}
class B {}
class G<E extends A> {}
f(G<B> h()) {}
"####,
        expected: &[("typeArgumentNotMatchingBounds", 50, 1)],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_genericFunctionTypeArgument_invariant",
        source: r####"typedef F = T Function<T>(T);
typedef FB<T extends F> = S Function<S extends T>(S);
class CB<T extends F> {}
void f(CB<FB<F>> a) {}
"####,
        expected: &[("typeArgumentNotMatchingBounds", 119, 5)],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_genericFunctionTypeArgument_regularBounded",
        source: r####"typedef F1 = T Function<T>(T);
typedef F2 = S Function<S>(S);
class CB<T extends F1> {}
void f(CB<F2> a) {}
"####,
        expected: &[],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_implements",
        source: r####"class A {}
class B {}
class G<E extends A> {}
class C implements G<B>{}
"####,
        expected: &[("typeArgumentNotMatchingBounds", 67, 1)],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_is",
        source: r####"class A {}
class B {}
class G<E extends A> {}
var b = 1 is G<B>;
"####,
        expected: &[("typeArgumentNotMatchingBounds", 61, 1)],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_metadata_matching",
        source: r####"class A<T extends num> {
  const A();
}

@A<int>()
void f() {}
"####,
        expected: &[],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_metadata_notMatching",
        source: r####"class A<T extends num> {
  const A();
}

@A<String>()
void f() {}
"####,
        expected: &[("typeArgumentNotMatchingBounds", 44, 6)],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_metadata_notMatching_viaTypeAlias",
        source: r####"class A<T> {
  const A();
}

typedef B<T extends num> = A<T>;

@B<String>()
void f() {}
"####,
        expected: &[("typeArgumentNotMatchingBounds", 66, 6)],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_methodInvocation_genericFunctionTypeArgument_match",
        source: r####"typedef F = void Function<T extends num>();
void f<T extends void Function<X extends num>()>() {}
void g() {
  f<F>();
}
"####,
        expected: &[],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_methodInvocation_genericFunctionTypeArgument_mismatch",
        source: r####"class A {}
class B {}
typedef F = void Function<T extends A>();
void f<T extends void Function<U extends B>()>() {}
void g() {
  f<F>();
}
"####,
        expected: &[("typeArgumentNotMatchingBounds", 131, 1)],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_methodInvocation_topLevelFunction",
        source: r####"class Point<T extends num> {
  Point(T x, T y);
}

Point<T> f<T extends num>(T x, T y) {
  return new Point<T>(x, y);
}

main() {
  print(f<String>('hello', 'world'));
}
"####,
        expected: &[("typeArgumentNotMatchingBounds", 140, 6)],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_methodReturnType",
        source: r####"class A {}
class B {}
class G<E extends A> {}
class C {
  G<B> m() => throw 0;
}
"####,
        expected: &[("typeArgumentNotMatchingBounds", 60, 1)],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_new",
        source: r####"class A {}
class B {}
class G<E extends A> {}
f() { return new G<B>(); }
"####,
        expected: &[("typeArgumentNotMatchingBounds", 65, 1)],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_new_matching",
        source: r####"class A {}
class B extends A {}
class G<E extends A> {}
f() { return new G<B>(); }
"####,
        expected: &[],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_new_superTypeOfUpperBound",
        source: r####"class A {}
class B extends A {}
class C extends B {}
class G<E extends B> {}
f() { return new G<A>(); }
"####,
        expected: &[("typeArgumentNotMatchingBounds", 96, 1)],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_nonFunctionTypeAlias_body_typeArgument_mismatch",
        source: r####"class A {}
class B {}
class G<T extends A> {}
typedef X = G<B>;
"####,
        expected: &[("typeArgumentNotMatchingBounds", 60, 1)],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_nonFunctionTypeAlias_body_typeArgument_regularBounded",
        source: r####"class A {}
class B extends A {}
class G<T extends A> {}
typedef X = G<B>;
"####,
        expected: &[],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_nonFunctionTypeAlias_body_typeArgument_superBounded",
        source: r####"class A<T extends A<T>> {}
typedef X = List<A>;
"####,
        expected: &[],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_nonFunctionTypeAlias_interfaceType_body_mismatch",
        source: r####"class A {}
class B {}
class G<T extends A> {}
typedef X = G<B>;
"####,
        expected: &[("typeArgumentNotMatchingBounds", 60, 1)],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_nonFunctionTypeAlias_interfaceType_body_regularBounded",
        source: r####"class A<T> {}
typedef X<T> = A;
"####,
        expected: &[],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_nonFunctionTypeAlias_interfaceType_body_superBounded",
        source: r####"class A<T extends A<T>> {}
typedef X<T> = A;
"####,
        expected: &[("typeArgumentNotMatchingBounds", 42, 1)],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_nonFunctionTypeAlias_interfaceType_parameter",
        source: r####"class A {}
typedef X<T extends A> = Map<int, T>;
void f(X<String> a) {}
"####,
        expected: &[("typeArgumentNotMatchingBounds", 58, 6)],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_nonFunctionTypeAlias_interfaceType_parameter_regularBounded",
        source: r####"class A {}
class B extends A {}
typedef X<T extends A> = Map<int, T>;
void f(X<B> a) {}
"####,
        expected: &[],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_notRegularBounded_notSuperBounded_parameter_invariant",
        source: r####"typedef A<X> = X Function(X);
typedef G<X extends A<X>> = void Function<Y extends X>();
foo(G g) {}
"####,
        expected: &[("typeArgumentNotMatchingBounds", 92, 1)],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_ofFunctionTypeAlias",
        source: r####"class A {}
class B {}
typedef F<T extends A>();
F<B> fff = (throw 42);
"####,
        expected: &[("typeArgumentNotMatchingBounds", 50, 1)],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_ofFunctionTypeAlias_hasBound2_matching",
        source: r####"class MyClass<T> {}
typedef MyFunction<T, P extends MyClass<T>>();
class A<T, P extends MyClass<T>> {
  MyFunction<T, P> f = (throw 0);
}
"####,
        expected: &[],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_ofFunctionTypeAlias_hasBound_matching",
        source: r####"class A {}
class B extends A {}
typedef F<T extends A>();
F<A> fa = (throw 0);
F<B> fb = (throw 0);
"####,
        expected: &[],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_ofFunctionTypeAlias_noBound_matching",
        source: r####"typedef F<T>();
F<int> f1 = (throw 0);
F<String> f2 = (throw 0);
"####,
        expected: &[],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_parameter",
        source: r####"class A {}
class B {}
class G<E extends A> {}
f(G<B> g) {}
"####,
        expected: &[("typeArgumentNotMatchingBounds", 50, 1)],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_redirectingConstructor",
        source: r####"class A {}
class B {}
class X<T extends A> {
  X(int x, int y) {}
  factory X.name(int x, int y) = X<B>;
}
"####,
        expected: &[("typeArgumentNotMatchingBounds", 101, 1)],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_regression_42196",
        source: r####"typedef G<X> = Function(X);
class A<X extends G<A<X,Y>>, Y extends X> {}

test<X>() { print("OK"); }

main() {
  test<A<G<A<Never, Never>>, dynamic>>();
}
"####,
        expected: &[],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_regression_42196_object",
        source: r####"typedef G<X> = Function(X);
class A<X extends G<A<X, Y>>, Y extends Never> {}

test<X>() { print("OK"); }

main() {
  test<A<G<A<Never, Never>>, Object?>>();
}
"####,
        expected: &[],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_regression_42196_void",
        source: r####"typedef G<X> = Function(X);
class A<X extends G<A<X, Y>>, Y extends Never> {}

test<X>() { print("OK"); }

main() {
  test<A<G<A<Never, Never>>, void>>();
}
"####,
        expected: &[],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_superBounded",
        source: r####"class A<X extends A<X>> {}

A get foo => throw 0;
"####,
        expected: &[],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_typeArgumentList",
        source: r####"class A {}
class B {}
class C<E> {}
class D<E extends A> {}
C<D<B>> c = (throw 0);
"####,
        expected: &[("typeArgumentNotMatchingBounds", 64, 1)],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_typeParameter",
        source: r####"class A {}
class B {}
class C {}
class G<E extends A> {}
class D<F extends G<B>> {}
"####,
        expected: &[("typeArgumentNotMatchingBounds", 77, 1)],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_variableDeclaration",
        source: r####"class A {}
class B {}
class G<E extends A> {}
G<B> g = (throw 0);
"####,
        expected: &[("typeArgumentNotMatchingBounds", 48, 1)],
    },
    Case {
        file: "type_argument_not_matching_bounds_test.dart",
        name: "test_with",
        source: r####"class A {}
class B {}
mixin G<E extends A> {}
class C extends Object with G<B>{}
"####,
        expected: &[("typeArgumentNotMatchingBounds", 76, 1)],
    },
    Case {
        file: "wrong_number_of_type_arguments_enum_test.dart",
        name: "test_tooFew",
        source: r####"enum E<T, U> {
  v<int>()
}
"####,
        expected: &[("wrongNumberOfTypeArgumentsEnum", 18, 5)],
    },
    Case {
        file: "wrong_number_of_type_arguments_enum_test.dart",
        name: "test_tooMany",
        source: r####"enum E<T> {
  v<int, int>()
}
"####,
        expected: &[("wrongNumberOfTypeArgumentsEnum", 15, 10)],
    },
    Case {
        file: "base_mixin_implemented_outside_of_library_test.dart",
        name: "test_class_inside",
        source: r####"base mixin Foo {}
base class Bar implements Foo {}
"####,
        expected: &[],
    },
    Case {
        file: "base_mixin_implemented_outside_of_library_test.dart",
        name: "test_enum_inside",
        source: r####"base mixin Foo {}
enum Bar implements Foo { bar }
"####,
        expected: &[],
    },
    Case {
        file: "base_mixin_implemented_outside_of_library_test.dart",
        name: "test_mixin_inside",
        source: r####"base mixin Foo {}
base mixin Bar implements Foo {}
"####,
        expected: &[],
    },
    Case {
        file: "base_class_implemented_outside_of_library_test.dart",
        name: "test_class_inside",
        source: r####"base class Foo {}
base class Bar implements Foo {}
"####,
        expected: &[],
    },
    Case {
        file: "base_class_implemented_outside_of_library_test.dart",
        name: "test_classTypeAlias_inside",
        source: r####"base class A {}
sealed class B extends A {}
mixin M {}
base class C = Object with M implements B;
"####,
        expected: &[],
    },
    Case {
        file: "base_class_implemented_outside_of_library_test.dart",
        name: "test_enum_inside",
        source: r####"base class Foo {}
enum Bar implements Foo { bar }
"####,
        expected: &[],
    },
    Case {
        file: "base_class_implemented_outside_of_library_test.dart",
        name: "test_mixin_inside",
        source: r####"base class Foo {}
base mixin Bar implements Foo {}
"####,
        expected: &[],
    },
    Case {
        file: "invalid_type_argument_in_const_map_test.dart",
        name: "test_asDefaultValue",
        source: r####"class A<E> {
  final Map<String, List<E Function()>> x;
  const A([this.x = const <String, List<E Function()>>{}]);
}
"####,
        expected: &[("invalidTypeArgumentInConstMap", 96, 1)],
    },
    Case {
        file: "mixin_subtype_of_base_is_not_base_test.dart",
        name: "test_class_implements",
        source: r####"base class A {}
mixin B implements A {}
"####,
        expected: &[("mixinSubtypeOfBaseIsNotBase", 22, 1)],
    },
    Case {
        file: "mixin_subtype_of_base_is_not_base_test.dart",
        name: "test_class_implements_indirect",
        source: r####"base class A {}
sealed class B implements A {}
mixin C implements B {}
"####,
        expected: &[("mixinSubtypeOfBaseIsNotBase", 53, 1)],
    },
    Case {
        file: "mixin_subtype_of_base_is_not_base_test.dart",
        name: "test_class_on",
        source: r####"base class A {}
mixin B on A {}
"####,
        expected: &[("mixinSubtypeOfBaseIsNotBase", 22, 1)],
    },
    Case {
        file: "mixin_subtype_of_base_is_not_base_test.dart",
        name: "test_mixin_implements",
        source: r####"base mixin A {}
mixin B implements A {}
"####,
        expected: &[("mixinSubtypeOfBaseIsNotBase", 22, 1)],
    },
    Case {
        file: "mixin_subtype_of_final_is_not_base_test.dart",
        name: "test_implements",
        source: r####"final class A {}
mixin B implements A {}
"####,
        expected: &[("mixinSubtypeOfFinalIsNotBase", 23, 1)],
    },
    Case {
        file: "mixin_subtype_of_final_is_not_base_test.dart",
        name: "test_implements_indirect",
        source: r####"final class A {}
sealed class B implements A {}
mixin C implements B {}
"####,
        expected: &[("mixinSubtypeOfFinalIsNotBase", 54, 1)],
    },
    Case {
        file: "mixin_subtype_of_final_is_not_base_test.dart",
        name: "test_on",
        source: r####"final class A {}
mixin B on A {}
"####,
        expected: &[("mixinSubtypeOfFinalIsNotBase", 23, 1)],
    },
    Case {
        file: "subtype_of_base_is_not_base_final_or_sealed_test.dart",
        name: "test_class_extends",
        source: r####"base class A {}
class B extends A {}
"####,
        expected: &[("subtypeOfBaseIsNotBaseFinalOrSealed", 22, 1)],
    },
    Case {
        file: "subtype_of_base_is_not_base_final_or_sealed_test.dart",
        name: "test_class_extends_multiple",
        source: r####"base class A {}
base class B extends A {}
class C extends A {}
"####,
        expected: &[("subtypeOfBaseIsNotBaseFinalOrSealed", 48, 1)],
    },
    Case {
        file: "subtype_of_base_is_not_base_final_or_sealed_test.dart",
        name: "test_class_implements",
        source: r####"base class A {}
class B implements A {}
"####,
        expected: &[("subtypeOfBaseIsNotBaseFinalOrSealed", 22, 1)],
    },
    Case {
        file: "subtype_of_base_is_not_base_final_or_sealed_test.dart",
        name: "test_class_sealed_extends",
        source: r####"base class A {}
sealed class B extends A {}
class C extends B {}
"####,
        expected: &[("subtypeOfBaseIsNotBaseFinalOrSealed", 50, 1)],
    },
    Case {
        file: "subtype_of_base_is_not_base_final_or_sealed_test.dart",
        name: "test_class_sealed_extends_interface_implements_base",
        source: r####"base class A {}
interface class B {}
sealed class C extends B implements A {}
class D extends C {}
"####,
        expected: &[("subtypeOfBaseIsNotBaseFinalOrSealed", 84, 1)],
    },
    Case {
        file: "subtype_of_base_is_not_base_final_or_sealed_test.dart",
        name: "test_class_sealed_extends_interface_with_base",
        source: r####"base mixin A {}
interface class B {}
sealed class C extends B with A {}
class D extends C {}
"####,
        expected: &[("subtypeOfBaseIsNotBaseFinalOrSealed", 78, 1)],
    },
    Case {
        file: "subtype_of_base_is_not_base_final_or_sealed_test.dart",
        name: "test_class_sealed_extends_multiple",
        source: r####"base class A {}
sealed class B extends A {}
sealed class C extends B {}
class D extends C {}
"####,
        expected: &[("subtypeOfBaseIsNotBaseFinalOrSealed", 78, 1)],
    },
    Case {
        file: "subtype_of_base_is_not_base_final_or_sealed_test.dart",
        name: "test_class_sealed_extends_unordered",
        source: r####"class C extends B {}
sealed class B extends A {}
base class A {}
"####,
        expected: &[("subtypeOfBaseIsNotBaseFinalOrSealed", 6, 1)],
    },
    Case {
        file: "subtype_of_base_is_not_base_final_or_sealed_test.dart",
        name: "test_class_sealed_implements",
        source: r####"base class A {}
sealed class B implements A {}
class C implements B {}
"####,
        expected: &[("subtypeOfBaseIsNotBaseFinalOrSealed", 53, 1)],
    },
    Case {
        file: "subtype_of_base_is_not_base_final_or_sealed_test.dart",
        name: "test_classTypeAlias",
        source: r####"base class A {}
mixin B {}
class C = Object with B implements A;
"####,
        expected: &[("subtypeOfBaseIsNotBaseFinalOrSealed", 33, 1)],
    },
    Case {
        file: "subtype_of_base_is_not_base_final_or_sealed_test.dart",
        name: "test_classTypeAlias_interface",
        source: r####"base class A {}
mixin B {}
interface class C = Object with B implements A;
"####,
        expected: &[("subtypeOfBaseIsNotBaseFinalOrSealed", 43, 1)],
    },
    Case {
        file: "subtype_of_base_is_not_base_final_or_sealed_test.dart",
        name: "test_classTypeAlias_sealed",
        source: r####"base class A {}
sealed class AA extends A {}
mixin B {}
class C = Object with B implements AA;
"####,
        expected: &[("subtypeOfBaseIsNotBaseFinalOrSealed", 62, 1)],
    },
    Case {
        file: "subtype_of_base_is_not_base_final_or_sealed_test.dart",
        name: "test_classTypeAlias_sealed_interface",
        source: r####"base class A {}
sealed class AA extends A {}
mixin B {}
interface class C = Object with B implements AA;
"####,
        expected: &[("subtypeOfBaseIsNotBaseFinalOrSealed", 72, 1)],
    },
    Case {
        file: "subtype_of_base_is_not_base_final_or_sealed_test.dart",
        name: "test_mixinClass_sealed",
        source: r####"base mixin class A {}
sealed class B with A {}
class C extends B {}
"####,
        expected: &[("subtypeOfBaseIsNotBaseFinalOrSealed", 53, 1)],
    },
    Case {
        file: "subtype_of_base_is_not_base_final_or_sealed_test.dart",
        name: "test_mixinClass_with",
        source: r####"base mixin class A {}
class B with A {}
"####,
        expected: &[("subtypeOfBaseIsNotBaseFinalOrSealed", 28, 1)],
    },
    Case {
        file: "subtype_of_final_is_not_base_final_or_sealed_test.dart",
        name: "test_class_extends",
        source: r####"final class A {}
class B extends A {}
"####,
        expected: &[("subtypeOfFinalIsNotBaseFinalOrSealed", 23, 1)],
    },
    Case {
        file: "subtype_of_final_is_not_base_final_or_sealed_test.dart",
        name: "test_class_extends_inAugmentation",
        source: r####"final class A {}
class B {}
augment class B extends A {}
"####,
        expected: &[("subtypeOfFinalIsNotBaseFinalOrSealed", 23, 1)],
    },
    Case {
        file: "subtype_of_final_is_not_base_final_or_sealed_test.dart",
        name: "test_class_implements",
        source: r####"final class A {}
class B implements A {}
"####,
        expected: &[("subtypeOfFinalIsNotBaseFinalOrSealed", 23, 1)],
    },
    Case {
        file: "subtype_of_final_is_not_base_final_or_sealed_test.dart",
        name: "test_class_sealed_extends",
        source: r####"final class A {}
sealed class B extends A {}
class C extends B {}
"####,
        expected: &[("subtypeOfFinalIsNotBaseFinalOrSealed", 51, 1)],
    },
    Case {
        file: "subtype_of_final_is_not_base_final_or_sealed_test.dart",
        name: "test_class_sealed_extends_multiple",
        source: r####"final class A {}
sealed class B extends A {}
sealed class C extends B {}
class D extends C {}
"####,
        expected: &[("subtypeOfFinalIsNotBaseFinalOrSealed", 79, 1)],
    },
    Case {
        file: "subtype_of_final_is_not_base_final_or_sealed_test.dart",
        name: "test_class_sealed_extends_unordered",
        source: r####"class C extends B {}
sealed class B extends A {}
final class A {}
"####,
        expected: &[("subtypeOfFinalIsNotBaseFinalOrSealed", 6, 1)],
    },
    Case {
        file: "subtype_of_final_is_not_base_final_or_sealed_test.dart",
        name: "test_class_sealed_implements",
        source: r####"final class A {}
sealed class B implements A {}
class C implements B {}
"####,
        expected: &[("subtypeOfFinalIsNotBaseFinalOrSealed", 54, 1)],
    },
    Case {
        file: "subtype_of_final_is_not_base_final_or_sealed_test.dart",
        name: "test_class_sealed_with_extends",
        source: r####"mixin A {}
final class B {}
sealed class C extends B with A {}
class D extends C {}
"####,
        expected: &[("subtypeOfFinalIsNotBaseFinalOrSealed", 69, 1)],
    },
    Case {
        file: "subtype_of_final_is_not_base_final_or_sealed_test.dart",
        name: "test_classTypeAlias",
        source: r####"final class A {}
mixin B {}
class C = Object with B implements A;
"####,
        expected: &[("subtypeOfFinalIsNotBaseFinalOrSealed", 34, 1)],
    },
    Case {
        file: "subtype_of_final_is_not_base_final_or_sealed_test.dart",
        name: "test_classTypeAlias_interface",
        source: r####"final class A {}
mixin B {}
interface class C = Object with B implements A;
"####,
        expected: &[("subtypeOfFinalIsNotBaseFinalOrSealed", 44, 1)],
    },
    Case {
        file: "subtype_of_final_is_not_base_final_or_sealed_test.dart",
        name: "test_classTypeAlias_sealed",
        source: r####"final class A {}
sealed class AA extends A {}
mixin B {}
class C = Object with B implements AA;
"####,
        expected: &[("subtypeOfFinalIsNotBaseFinalOrSealed", 63, 1)],
    },
    Case {
        file: "subtype_of_final_is_not_base_final_or_sealed_test.dart",
        name: "test_classTypeAlias_sealed_interface",
        source: r####"final class A {}
sealed class AA extends A {}
mixin B {}
interface class C = Object with B implements AA;
"####,
        expected: &[("subtypeOfFinalIsNotBaseFinalOrSealed", 73, 1)],
    },
    Case {
        file: "variable_not_initialized_test.dart",
        name: "test_class_instanceField1_final_functionTypedFieldFormal",
        source: r####"class A {
  final Function v;
  A(int this.v()) {}
}
"####,
        expected: &[],
    },
    Case {
        file: "variable_not_initialized_test.dart",
        name: "test_class_instanceField1_notFinal_typeInt_hasInitializer_primaryConstructor_fieldFormalParameter_constructorInitializer",
        source: r####"class A(this.v) {
  int v = 0;
  this : v = 0;
}
"####,
        expected: &[("fieldInitializedInDeclarationAndParameterOfPrimaryConstructor", 13, 1), ("fieldInitializedInParameterAndInitializer", 40, 1)],
    },
    Case {
        file: "variable_not_initialized_test.dart",
        name: "test_class_instanceField1_notFinal_typeInt_hasInitializer_secondaryConstructor_constructorInitializer2",
        source: r####"class A {
  int v = 0;
  A() : v = 0, v = 0 {}
}
"####,
        expected: &[("fieldInitializedByMultipleInitializers", 38, 1)],
    },
    Case {
        file: "variable_not_initialized_test.dart",
        name: "test_class_instanceField1_notFinal_typeInt_hasInitializer_secondaryConstructor_fieldFormalParameter_constructorInitializer",
        source: r####"class A {
  int v = 0;
  A(this.v) : v = 0 {}
}
"####,
        expected: &[("fieldInitializedInParameterAndInitializer", 37, 1)],
    },
    Case {
        file: "variable_not_initialized_test.dart",
        name: "test_class_instanceField1_notFinal_typeInt_noInitializer_primaryConstructor_constructorInitializer2",
        source: r####"class A() {
  int v;
  this : v = 0, v = 0;
}
"####,
        expected: &[("fieldInitializedByMultipleInitializers", 37, 1)],
    },
    Case {
        file: "variable_not_initialized_test.dart",
        name: "test_class_instanceField1_notFinal_typeInt_noInitializer_primaryConstructor_constructorInitializer3",
        source: r####"class A() {
  int v;
  this : v = 0, v = 0, v = 0;
}
"####,
        expected: &[("fieldInitializedByMultipleInitializers", 37, 1), ("fieldInitializedByMultipleInitializers", 44, 1)],
    },
    Case {
        file: "variable_not_initialized_test.dart",
        name: "test_class_instanceField1_notFinal_typeInt_noInitializer_secondaryConstructor_constructorInitializer2",
        source: r####"class A {
  int v;
  A() : v = 0, v = 0 {}
}
"####,
        expected: &[("fieldInitializedByMultipleInitializers", 34, 1)],
    },
    Case {
        file: "variable_not_initialized_test.dart",
        name: "test_class_instanceField1_notFinal_typeInt_noInitializer_secondaryConstructor_constructorInitializer3",
        source: r####"class A {
  int v;
  A() : v = 0, v = 0, v = 0 {}
}
"####,
        expected: &[("fieldInitializedByMultipleInitializers", 34, 1), ("fieldInitializedByMultipleInitializers", 41, 1)],
    },
    Case {
        file: "variable_not_initialized_test.dart",
        name: "test_class_instanceField1_notFinal_typeInt_noInitializer_secondaryConstructor_fieldFormalParameter_constructorInitializer",
        source: r####"class A {
  int v;
  A(this.v) : v = 0 {}
}
"####,
        expected: &[("fieldInitializedInParameterAndInitializer", 33, 1)],
    },
    Case {
        file: "variable_not_initialized_test.dart",
        name: "test_class_instanceField2_notFinal_typeInt_noInitializer_primaryConstructor_constructorInitializer2",
        source: r####"class A() {
  int v1;
  int v2;
  this : v1 = 0, v1 = 0, v2 = 0, v2 = 0;
}
"####,
        expected: &[("fieldInitializedByMultipleInitializers", 49, 2), ("fieldInitializedByMultipleInitializers", 65, 2)],
    },
    Case {
        file: "variable_not_initialized_test.dart",
        name: "test_class_instanceField2_notFinal_typeInt_noInitializer_secondaryConstructor_constructorInitializer",
        source: r####"class A {
  int v1;
  int v2;
  A() : v1 = 0, v2 = 0 {}
}
"####,
        expected: &[],
    },
    Case {
        file: "variable_not_initialized_test.dart",
        name: "test_class_instanceField2_notFinal_typeInt_noInitializer_secondaryConstructor_constructorInitializer2",
        source: r####"class A {
  int v1;
  int v2;
  A() : v1 = 0, v1 = 0, v2 = 0, v2 = 0 {}
}
"####,
        expected: &[("fieldInitializedByMultipleInitializers", 46, 2), ("fieldInitializedByMultipleInitializers", 62, 2)],
    },
    Case {
        file: "variable_not_initialized_test.dart",
        name: "test_class_staticField1_const_hasInitializer",
        source: r####"class A {
  static const int v = 0;
}
"####,
        expected: &[],
    },
    Case {
        file: "variable_not_initialized_test.dart",
        name: "test_enum_instanceField1_final_noInitializer_secondaryConstructor_constructorInitializer2",
        source: r####"enum A {
  e;
  final int v;
  const A() : v = 0, v = 0;
}
"####,
        expected: &[("fieldInitializedByMultipleInitializers", 50, 1)],
    },
    Case {
        file: "variable_not_initialized_test.dart",
        name: "test_enum_instanceField1_final_noInitializer_secondaryConstructor_fieldFormalParameter_constructorInitializer",
        source: r####"enum A {
  e(0);
  final int v;
  const A(this.v) : v = 0;
}
"####,
        expected: &[("fieldInitializedInParameterAndInitializer", 52, 1)],
    },
    Case {
        file: "variable_not_initialized_test.dart",
        name: "test_enum_instanceField2_final_noInitializer_secondaryConstructor_constructorInitializer",
        source: r####"enum A {
  e;
  final int v1;
  final int v2;
  const A() : v1 = 0, v2 = 0;
}
"####,
        expected: &[],
    },
    Case {
        file: "variable_not_initialized_test.dart",
        name: "test_extensionType_instanceField1_final_noInitializer_secondaryConstructor_fieldFormalParameter_constructorInitializer",
        source: r####"extension type A(int it) {
  A.named(this.it) : it = 0;
}
"####,
        expected: &[("fieldInitializedInParameterAndInitializer", 48, 2)],
    },
    Case {
        file: "variable_not_initialized_test.dart",
        name: "test_mixin_instanceField1_final_hasInitializer",
        source: r####"mixin A {
  final int v = 0;
}
"####,
        expected: &[],
    },
    Case {
        file: "generic_function_type_cannot_be_bound_test.dart",
        name: "test_class",
        source: r####"class C<T extends S Function<S>(S)> {
}
"####,
        expected: &[],
    },
    Case {
        file: "generic_function_type_cannot_be_bound_test.dart",
        name: "test_genericFunction",
        source: r####"late T Function<T extends S Function<S>(S)>(T) fun;
"####,
        expected: &[],
    },
    Case {
        file: "generic_function_type_cannot_be_bound_test.dart",
        name: "test_genericFunctionTypedef",
        source: r####"typedef foo = T Function<T extends S Function<S>(S)>(T t);
"####,
        expected: &[],
    },
    Case {
        file: "generic_function_type_cannot_be_bound_test.dart",
        name: "test_parameterOfFunction",
        source: r####"class C<T extends void Function(S Function<S>(S))> {}
"####,
        expected: &[],
    },
    Case {
        file: "generic_function_type_cannot_be_bound_test.dart",
        name: "test_typedef",
        source: r####"typedef T foo<T extends S Function<S>(S)>(T t);
"####,
        expected: &[],
    },
    Case {
        file: "generic_function_type_cannot_be_bound_test.dart",
        name: "test_parameterOfFunction",
        source: r####"class C<T extends void Function(S Function<S>(S))> {}
"####,
        expected: &[],
    },
    Case {
        file: "constructor_body_test.dart",
        name: "test_class_secondaryConstructor_constFactory_expressionBody",
        source: r####"class C {
  const factory C() => null;
}
"####,
        expected: &[("returnOfInvalidTypeFromConstructor", 33, 4)],
    },
    Case {
        file: "constructor_body_test.dart",
        name: "test_class_secondaryConstructor_constFactory_external_expressionBody",
        source: r####"class C {
  external const factory C() => null;
}
"####,
        expected: &[("returnOfInvalidTypeFromConstructor", 42, 4)],
    },
    Case {
        file: "constructor_body_test.dart",
        name: "test_class_secondaryConstructor_constGenerative_expressionBody",
        source: r####"class C {
  const C();
  const C.named() => C();
}
"####,
        expected: &[("returnInGenerativeConstructor", 41, 7)],
    },
    Case {
        file: "constructor_body_test.dart",
        name: "test_class_secondaryConstructor_constGenerative_external_expressionBody",
        source: r####"class C {
  external const C() => null;
}
"####,
        expected: &[("returnInGenerativeConstructor", 31, 8), ("returnOfInvalidTypeFromConstructor", 34, 4)],
    },
    Case {
        file: "constructor_body_test.dart",
        name: "test_class_secondaryConstructor_constGenerativeRedirecting_expressionBody",
        source: r####"class C {
  const C();
  const C.named() : this() => null;
}
"####,
        expected: &[("returnInGenerativeConstructor", 50, 8), ("returnOfInvalidTypeFromConstructor", 53, 4)],
    },
    Case {
        file: "constructor_body_test.dart",
        name: "test_class_secondaryConstructor_factory_external_expressionBody",
        source: r####"class C {
  external factory C() => null;
}
"####,
        expected: &[("returnOfInvalidTypeFromConstructor", 36, 4)],
    },
    Case {
        file: "constructor_body_test.dart",
        name: "test_class_secondaryConstructor_generative_external_expressionBody",
        source: r####"class C {
  external C() => null;
}
"####,
        expected: &[("returnInGenerativeConstructor", 25, 8), ("returnOfInvalidTypeFromConstructor", 28, 4)],
    },
    Case {
        file: "constructor_body_test.dart",
        name: "test_enum_secondaryConstructor_constFactory_expressionBody",
        source: r####"enum E {
  v;
  const E();
  const factory E.named() => null;
}
"####,
        expected: &[("returnOfInvalidTypeFromConstructor", 56, 4)],
    },
    Case {
        file: "constructor_body_test.dart",
        name: "test_enum_secondaryConstructor_constFactory_external_expressionBody",
        source: r####"enum E {
  v;
  const E();
  external const factory E.named() => null;
}
"####,
        expected: &[("returnOfInvalidTypeFromConstructor", 65, 4)],
    },
    Case {
        file: "constructor_body_test.dart",
        name: "test_enum_secondaryConstructor_constGenerative_expressionBody",
        source: r####"enum E {
  v;
  const E();
  const E.named() => null;
}
"####,
        expected: &[("returnInGenerativeConstructor", 45, 8), ("returnOfInvalidTypeFromConstructor", 48, 4)],
    },
    Case {
        file: "constructor_body_test.dart",
        name: "test_enum_secondaryConstructor_constGenerative_external_expressionBody",
        source: r####"enum E {
  v;
  external const E() => null;
}
"####,
        expected: &[("returnInGenerativeConstructor", 35, 8), ("returnOfInvalidTypeFromConstructor", 38, 4)],
    },
    Case {
        file: "constructor_body_test.dart",
        name: "test_enum_secondaryConstructor_constGenerativeRedirecting_expressionBody",
        source: r####"enum E {
  v1, v2.named();
  const E();
  const E.named() : this() => null;
}
"####,
        expected: &[("returnInGenerativeConstructor", 67, 8), ("returnOfInvalidTypeFromConstructor", 70, 4)],
    },
    Case {
        file: "constructor_body_test.dart",
        name: "test_enum_secondaryConstructor_factory_external_expressionBody",
        source: r####"enum E {
  v;
  const E();
  external factory E.named() => null;
}
"####,
        expected: &[("returnOfInvalidTypeFromConstructor", 59, 4)],
    },
    Case {
        file: "constructor_body_test.dart",
        name: "test_extensionType_secondaryConstructor_constFactory_expressionBody",
        source: r####"extension type const E(int it) {
  const factory E.named() => null;
}
"####,
        expected: &[("returnOfInvalidTypeFromConstructor", 62, 4)],
    },
    Case {
        file: "constructor_body_test.dart",
        name: "test_extensionType_secondaryConstructor_constFactory_external_expressionBody",
        source: r####"extension type const E(int it) {
  external const factory E.named() => null;
}
"####,
        expected: &[("returnOfInvalidTypeFromConstructor", 71, 4)],
    },
    Case {
        file: "constructor_body_test.dart",
        name: "test_extensionType_secondaryConstructor_constGenerative_expressionBody",
        source: r####"extension type const E(int it) {
  const E.named() : it = 0 => E(0);
}
"####,
        expected: &[("returnInGenerativeConstructor", 60, 8)],
    },
    Case {
        file: "constructor_body_test.dart",
        name: "test_extensionType_secondaryConstructor_constGenerative_external_expressionBody",
        source: r####"extension type const E(int it) {
  external const E.named() => null;
}
"####,
        expected: &[("returnInGenerativeConstructor", 60, 8), ("returnOfInvalidTypeFromConstructor", 63, 4)],
    },
    Case {
        file: "constructor_body_test.dart",
        name: "test_extensionType_secondaryConstructor_constGenerativeRedirecting_expressionBody",
        source: r####"extension type const E(int it) {
  const E.named() : this(0) => null;
}
"####,
        expected: &[("returnInGenerativeConstructor", 61, 8), ("returnOfInvalidTypeFromConstructor", 64, 4)],
    },
    Case {
        file: "constructor_body_test.dart",
        name: "test_extensionType_secondaryConstructor_factory_external_expressionBody",
        source: r####"extension type const E(int it) {
  external factory E.named() => null;
}
"####,
        expected: &[("returnOfInvalidTypeFromConstructor", 65, 4)],
    },
    Case {
        file: "constructor_body_test.dart",
        name: "test_extensionType_secondaryConstructor_generative_external_expressionBody",
        source: r####"extension type E(int it) {
  external E.named() => null;
}
"####,
        expected: &[("returnInGenerativeConstructor", 48, 8), ("returnOfInvalidTypeFromConstructor", 51, 4)],
    },
    Case {
        file: "could_not_infer_test.dart",
        name: "test_constructors_inferenceFBounded",
        source: r####"class C<T> {}

class P<T extends C<T>, U extends C<U>> {
  T t;
  U u;
  P(this.t, this.u);
  P._();
  P<U, T> get reversed => new P(u, t);
}

main() {
  P._();
}
"####,
        expected: &[("notInitializedNonNullableInstanceFieldConstructor", 94, 3), ("notInitializedNonNullableInstanceFieldConstructor", 94, 3), ("typeArgumentNotMatchingBounds", 154, 1), ("typeArgumentNotMatchingBounds", 154, 1)],
    },
    Case {
        file: "could_not_infer_test.dart",
        name: "test_constructors_inferFromArguments_argumentNotAssignable",
        source: r####"class A {}

typedef T F<T>();

class C<T extends A> {
  C(F<T> f);
}

class NotA {}
NotA myF() => null;

main() {
  var x = C(myF);
}
"####,
        expected: &[("returnOfInvalidTypeFromFunction", 98, 4)],
    },
    Case {
        file: "could_not_infer_test.dart",
        name: "test_function",
        source: r####"T f<T>(T t) => null;
main() { f(<S>(S s) => s); }
"####,
        expected: &[("returnOfInvalidTypeFromFunction", 15, 4)],
    },
    Case {
        file: "could_not_infer_test.dart",
        name: "test_method",
        source: r####"class C {
  T f<T>(T t) => null;
}
main() { new C().f(<S>(S s) => s); }
"####,
        expected: &[("returnOfInvalidTypeFromMethod", 27, 4)],
    },
    Case {
        file: "extension_type_constructor_with_super_invocation_test.dart",
        name: "test_notLast",
        source: r####"extension type const E._(int it) {
  const E(int it) : super._(it), assert(it >= 0);
}
"####,
        expected: &[("finalNotInitializedConstructor1", 43, 1)],
    },
    Case {
        file: "invalid_reference_to_this_test.dart",
        name: "test_extensionType_primaryConstructor_fieldInitializer",
        source: r####"extension type E(int it) {
  this : it = this.hashCode;
}
"####,
        expected: &[("fieldInitializedInParameterAndInitializer", 36, 2)],
    },
    Case {
        file: "wrong_number_of_type_arguments_test.dart",
        name: "test_messageText_enum",
        source: r####"enum E<T, U> {
  v<int>()
}
"####,
        expected: &[("wrongNumberOfTypeArgumentsEnum", 18, 5)],
    },
];
