// Dart source: pkg/analyzer/lib/src/lint/linter_visitor.g.dart
// Generated by tools/codegen/gen_lints.py; do not edit.
use crate::{NodeProcessor, RuleVisitorRegistry};
use dartr_ast::NodeKind;
impl RuleVisitorRegistry {
    pub fn add_adjacent_strings(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::AdjacentStrings, rule, processor);
    }
    pub fn add_annotation(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::Annotation, rule, processor);
    }
    pub fn add_anonymous_block_body(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::AnonymousBlockBody, rule, processor);
    }
    pub fn add_anonymous_expression_body(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::AnonymousExpressionBody, rule, processor);
    }
    pub fn add_anonymous_method_invocation(
        &mut self,
        rule: &'static str,
        processor: NodeProcessor,
    ) {
        self.add(NodeKind::AnonymousMethodInvocation, rule, processor);
    }
    pub fn add_argument_list(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::ArgumentList, rule, processor);
    }
    pub fn add_as_expression(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::AsExpression, rule, processor);
    }
    pub fn add_assert_initializer(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::AssertInitializer, rule, processor);
    }
    pub fn add_assert_statement(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::AssertStatement, rule, processor);
    }
    pub fn add_assigned_variable_pattern(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::AssignedVariablePattern, rule, processor);
    }
    pub fn add_assignment_expression(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::AssignmentExpression, rule, processor);
    }
    pub fn add_await_expression(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::AwaitExpression, rule, processor);
    }
    pub fn add_binary_expression(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::BinaryExpression, rule, processor);
    }
    pub fn add_block_class_body(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::BlockClassBody, rule, processor);
    }
    pub fn add_block_enum_body(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::BlockEnumBody, rule, processor);
    }
    pub fn add_block_function_body(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::BlockFunctionBody, rule, processor);
    }
    pub fn add_block(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::Block, rule, processor);
    }
    pub fn add_boolean_literal(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::BooleanLiteral, rule, processor);
    }
    pub fn add_break_statement(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::BreakStatement, rule, processor);
    }
    pub fn add_cascade_expression(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::CascadeExpression, rule, processor);
    }
    pub fn add_case_clause(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::CaseClause, rule, processor);
    }
    pub fn add_cast_pattern(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::CastPattern, rule, processor);
    }
    pub fn add_catch_clause(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::CatchClause, rule, processor);
    }
    pub fn add_catch_clause_parameter(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::CatchClauseParameter, rule, processor);
    }
    pub fn add_class_declaration(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::ClassDeclaration, rule, processor);
    }
    pub fn add_class_type_alias(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::ClassTypeAlias, rule, processor);
    }
    pub fn add_comment(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::Comment, rule, processor);
    }
    pub fn add_comment_reference(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::CommentReference, rule, processor);
    }
    pub fn add_compilation_unit(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::CompilationUnit, rule, processor);
    }
    pub fn add_conditional_expression(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::ConditionalExpression, rule, processor);
    }
    pub fn add_configuration(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::Configuration, rule, processor);
    }
    pub fn add_constant_pattern(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::ConstantPattern, rule, processor);
    }
    pub fn add_constructor_declaration(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::ConstructorDeclaration, rule, processor);
    }
    pub fn add_constructor_field_initializer(
        &mut self,
        rule: &'static str,
        processor: NodeProcessor,
    ) {
        self.add(NodeKind::ConstructorFieldInitializer, rule, processor);
    }
    pub fn add_constructor_name(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::ConstructorName, rule, processor);
    }
    pub fn add_constructor_reference(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::ConstructorReference, rule, processor);
    }
    pub fn add_constructor_selector(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::ConstructorSelector, rule, processor);
    }
    pub fn add_continue_statement(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::ContinueStatement, rule, processor);
    }
    pub fn add_declared_identifier(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::DeclaredIdentifier, rule, processor);
    }
    pub fn add_declared_variable_pattern(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::DeclaredVariablePattern, rule, processor);
    }
    pub fn add_do_statement(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::DoStatement, rule, processor);
    }
    pub fn add_dot_shorthand_constructor_invocation(
        &mut self,
        rule: &'static str,
        processor: NodeProcessor,
    ) {
        self.add(NodeKind::DotShorthandConstructorInvocation, rule, processor);
    }
    pub fn add_dot_shorthand_invocation(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::DotShorthandInvocation, rule, processor);
    }
    pub fn add_dot_shorthand_property_access(
        &mut self,
        rule: &'static str,
        processor: NodeProcessor,
    ) {
        self.add(NodeKind::DotShorthandPropertyAccess, rule, processor);
    }
    pub fn add_dotted_name(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::DottedName, rule, processor);
    }
    pub fn add_double_literal(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::DoubleLiteral, rule, processor);
    }
    pub fn add_empty_class_body(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::EmptyClassBody, rule, processor);
    }
    pub fn add_empty_enum_body(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::EmptyEnumBody, rule, processor);
    }
    pub fn add_empty_function_body(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::EmptyFunctionBody, rule, processor);
    }
    pub fn add_empty_statement(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::EmptyStatement, rule, processor);
    }
    pub fn add_enum_constant_arguments(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::EnumConstantArguments, rule, processor);
    }
    pub fn add_enum_constant_declaration(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::EnumConstantDeclaration, rule, processor);
    }
    pub fn add_enum_declaration(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::EnumDeclaration, rule, processor);
    }
    pub fn add_export_directive(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::ExportDirective, rule, processor);
    }
    pub fn add_expression_function_body(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::ExpressionFunctionBody, rule, processor);
    }
    pub fn add_expression_statement(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::ExpressionStatement, rule, processor);
    }
    pub fn add_extends_clause(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::ExtendsClause, rule, processor);
    }
    pub fn add_extension_declaration(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::ExtensionDeclaration, rule, processor);
    }
    pub fn add_extension_on_clause(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::ExtensionOnClause, rule, processor);
    }
    pub fn add_extension_override(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::ExtensionOverride, rule, processor);
    }
    pub fn add_extension_type_declaration(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::ExtensionTypeDeclaration, rule, processor);
    }
    pub fn add_field_declaration(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::FieldDeclaration, rule, processor);
    }
    pub fn add_field_formal_parameter(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::FieldFormalParameter, rule, processor);
    }
    pub fn add_for_each_parts_with_declaration(
        &mut self,
        rule: &'static str,
        processor: NodeProcessor,
    ) {
        self.add(NodeKind::ForEachPartsWithDeclaration, rule, processor);
    }
    pub fn add_for_each_parts_with_identifier(
        &mut self,
        rule: &'static str,
        processor: NodeProcessor,
    ) {
        self.add(NodeKind::ForEachPartsWithIdentifier, rule, processor);
    }
    pub fn add_for_each_parts_with_pattern(
        &mut self,
        rule: &'static str,
        processor: NodeProcessor,
    ) {
        self.add(NodeKind::ForEachPartsWithPattern, rule, processor);
    }
    pub fn add_for_element(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::ForElement, rule, processor);
    }
    pub fn add_formal_parameter_default_clause(
        &mut self,
        rule: &'static str,
        processor: NodeProcessor,
    ) {
        self.add(NodeKind::FormalParameterDefaultClause, rule, processor);
    }
    pub fn add_formal_parameter_list(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::FormalParameterList, rule, processor);
    }
    pub fn add_for_parts_with_declarations(
        &mut self,
        rule: &'static str,
        processor: NodeProcessor,
    ) {
        self.add(NodeKind::ForPartsWithDeclarations, rule, processor);
    }
    pub fn add_for_parts_with_expression(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::ForPartsWithExpression, rule, processor);
    }
    pub fn add_for_parts_with_pattern(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::ForPartsWithPattern, rule, processor);
    }
    pub fn add_for_statement(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::ForStatement, rule, processor);
    }
    pub fn add_function_declaration(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::FunctionDeclaration, rule, processor);
    }
    pub fn add_function_declaration_statement(
        &mut self,
        rule: &'static str,
        processor: NodeProcessor,
    ) {
        self.add(NodeKind::FunctionDeclarationStatement, rule, processor);
    }
    pub fn add_function_expression(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::FunctionExpression, rule, processor);
    }
    pub fn add_function_expression_invocation(
        &mut self,
        rule: &'static str,
        processor: NodeProcessor,
    ) {
        self.add(NodeKind::FunctionExpressionInvocation, rule, processor);
    }
    pub fn add_function_reference(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::FunctionReference, rule, processor);
    }
    pub fn add_function_type_alias(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::FunctionTypeAlias, rule, processor);
    }
    pub fn add_function_typed_formal_parameter_suffix(
        &mut self,
        rule: &'static str,
        processor: NodeProcessor,
    ) {
        self.add(
            NodeKind::FunctionTypedFormalParameterSuffix,
            rule,
            processor,
        );
    }
    pub fn add_generic_function_type(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::GenericFunctionType, rule, processor);
    }
    pub fn add_generic_type_alias(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::GenericTypeAlias, rule, processor);
    }
    pub fn add_guarded_pattern(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::GuardedPattern, rule, processor);
    }
    pub fn add_hide_combinator(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::HideCombinator, rule, processor);
    }
    pub fn add_if_element(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::IfElement, rule, processor);
    }
    pub fn add_if_statement(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::IfStatement, rule, processor);
    }
    pub fn add_implements_clause(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::ImplementsClause, rule, processor);
    }
    pub fn add_implicit_call_reference(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::ImplicitCallReference, rule, processor);
    }
    pub fn add_import_directive(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::ImportDirective, rule, processor);
    }
    pub fn add_import_prefix_reference(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::ImportPrefixReference, rule, processor);
    }
    pub fn add_index_expression(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::IndexExpression, rule, processor);
    }
    pub fn add_instance_creation_expression(
        &mut self,
        rule: &'static str,
        processor: NodeProcessor,
    ) {
        self.add(NodeKind::InstanceCreationExpression, rule, processor);
    }
    pub fn add_integer_literal(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::IntegerLiteral, rule, processor);
    }
    pub fn add_interpolation_expression(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::InterpolationExpression, rule, processor);
    }
    pub fn add_interpolation_string(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::InterpolationString, rule, processor);
    }
    pub fn add_is_expression(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::IsExpression, rule, processor);
    }
    pub fn add_labeled_statement(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::LabeledStatement, rule, processor);
    }
    pub fn add_label(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::Label, rule, processor);
    }
    pub fn add_label_reference(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::LabelReference, rule, processor);
    }
    pub fn add_library_directive(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::LibraryDirective, rule, processor);
    }
    pub fn add_list_literal(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::ListLiteral, rule, processor);
    }
    pub fn add_list_pattern(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::ListPattern, rule, processor);
    }
    pub fn add_logical_and_pattern(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::LogicalAndPattern, rule, processor);
    }
    pub fn add_logical_or_pattern(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::LogicalOrPattern, rule, processor);
    }
    pub fn add_map_literal_entry(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::MapLiteralEntry, rule, processor);
    }
    pub fn add_map_pattern_entry(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::MapPatternEntry, rule, processor);
    }
    pub fn add_map_pattern(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::MapPattern, rule, processor);
    }
    pub fn add_method_declaration(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::MethodDeclaration, rule, processor);
    }
    pub fn add_method_invocation(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::MethodInvocation, rule, processor);
    }
    pub fn add_mixin_declaration(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::MixinDeclaration, rule, processor);
    }
    pub fn add_mixin_on_clause(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::MixinOnClause, rule, processor);
    }
    pub fn add_named_argument(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::NamedArgument, rule, processor);
    }
    pub fn add_named_type(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::NamedType, rule, processor);
    }
    pub fn add_name_with_type_parameters(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::NameWithTypeParameters, rule, processor);
    }
    pub fn add_native_clause(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::NativeClause, rule, processor);
    }
    pub fn add_native_function_body(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::NativeFunctionBody, rule, processor);
    }
    pub fn add_null_assert_pattern(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::NullAssertPattern, rule, processor);
    }
    pub fn add_null_aware_element(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::NullAwareElement, rule, processor);
    }
    pub fn add_null_check_pattern(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::NullCheckPattern, rule, processor);
    }
    pub fn add_null_literal(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::NullLiteral, rule, processor);
    }
    pub fn add_object_pattern(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::ObjectPattern, rule, processor);
    }
    pub fn add_parenthesized_expression(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::ParenthesizedExpression, rule, processor);
    }
    pub fn add_parenthesized_pattern(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::ParenthesizedPattern, rule, processor);
    }
    pub fn add_part_directive(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::PartDirective, rule, processor);
    }
    pub fn add_part_of_directive(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::PartOfDirective, rule, processor);
    }
    pub fn add_pattern_assignment(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::PatternAssignment, rule, processor);
    }
    pub fn add_pattern_field(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::PatternField, rule, processor);
    }
    pub fn add_pattern_field_name(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::PatternFieldName, rule, processor);
    }
    pub fn add_pattern_variable_declaration(
        &mut self,
        rule: &'static str,
        processor: NodeProcessor,
    ) {
        self.add(NodeKind::PatternVariableDeclaration, rule, processor);
    }
    pub fn add_pattern_variable_declaration_statement(
        &mut self,
        rule: &'static str,
        processor: NodeProcessor,
    ) {
        self.add(
            NodeKind::PatternVariableDeclarationStatement,
            rule,
            processor,
        );
    }
    pub fn add_postfix_expression(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::PostfixExpression, rule, processor);
    }
    pub fn add_prefixed_identifier(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::PrefixedIdentifier, rule, processor);
    }
    pub fn add_prefix_expression(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::PrefixExpression, rule, processor);
    }
    pub fn add_primary_constructor_body(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::PrimaryConstructorBody, rule, processor);
    }
    pub fn add_primary_constructor_declaration(
        &mut self,
        rule: &'static str,
        processor: NodeProcessor,
    ) {
        self.add(NodeKind::PrimaryConstructorDeclaration, rule, processor);
    }
    pub fn add_primary_constructor_name(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::PrimaryConstructorName, rule, processor);
    }
    pub fn add_property_access(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::PropertyAccess, rule, processor);
    }
    pub fn add_record_literal(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::RecordLiteral, rule, processor);
    }
    pub fn add_record_literal_named_field(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::RecordLiteralNamedField, rule, processor);
    }
    pub fn add_record_pattern(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::RecordPattern, rule, processor);
    }
    pub fn add_record_type_annotation(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::RecordTypeAnnotation, rule, processor);
    }
    pub fn add_record_type_annotation_named_field(
        &mut self,
        rule: &'static str,
        processor: NodeProcessor,
    ) {
        self.add(NodeKind::RecordTypeAnnotationNamedField, rule, processor);
    }
    pub fn add_record_type_annotation_named_fields(
        &mut self,
        rule: &'static str,
        processor: NodeProcessor,
    ) {
        self.add(NodeKind::RecordTypeAnnotationNamedFields, rule, processor);
    }
    pub fn add_record_type_annotation_positional_field(
        &mut self,
        rule: &'static str,
        processor: NodeProcessor,
    ) {
        self.add(
            NodeKind::RecordTypeAnnotationPositionalField,
            rule,
            processor,
        );
    }
    pub fn add_redirecting_constructor_invocation(
        &mut self,
        rule: &'static str,
        processor: NodeProcessor,
    ) {
        self.add(NodeKind::RedirectingConstructorInvocation, rule, processor);
    }
    pub fn add_regular_formal_parameter(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::RegularFormalParameter, rule, processor);
    }
    pub fn add_relational_pattern(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::RelationalPattern, rule, processor);
    }
    pub fn add_rest_pattern_element(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::RestPatternElement, rule, processor);
    }
    pub fn add_rethrow_expression(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::RethrowExpression, rule, processor);
    }
    pub fn add_return_statement(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::ReturnStatement, rule, processor);
    }
    pub fn add_script_tag(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::ScriptTag, rule, processor);
    }
    pub fn add_set_or_map_literal(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::SetOrMapLiteral, rule, processor);
    }
    pub fn add_show_combinator(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::ShowCombinator, rule, processor);
    }
    pub fn add_simple_identifier(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::SimpleIdentifier, rule, processor);
    }
    pub fn add_simple_string_literal(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::SimpleStringLiteral, rule, processor);
    }
    pub fn add_spread_element(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::SpreadElement, rule, processor);
    }
    pub fn add_string_interpolation(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::StringInterpolation, rule, processor);
    }
    pub fn add_super_constructor_invocation(
        &mut self,
        rule: &'static str,
        processor: NodeProcessor,
    ) {
        self.add(NodeKind::SuperConstructorInvocation, rule, processor);
    }
    pub fn add_super_expression(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::SuperExpression, rule, processor);
    }
    pub fn add_super_formal_parameter(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::SuperFormalParameter, rule, processor);
    }
    pub fn add_switch_case(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::SwitchCase, rule, processor);
    }
    pub fn add_switch_default(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::SwitchDefault, rule, processor);
    }
    pub fn add_switch_expression_case(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::SwitchExpressionCase, rule, processor);
    }
    pub fn add_switch_expression(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::SwitchExpression, rule, processor);
    }
    pub fn add_switch_pattern_case(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::SwitchPatternCase, rule, processor);
    }
    pub fn add_switch_statement(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::SwitchStatement, rule, processor);
    }
    pub fn add_symbol_literal(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::SymbolLiteral, rule, processor);
    }
    pub fn add_this_expression(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::ThisExpression, rule, processor);
    }
    pub fn add_throw_expression(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::ThrowExpression, rule, processor);
    }
    pub fn add_top_level_variable_declaration(
        &mut self,
        rule: &'static str,
        processor: NodeProcessor,
    ) {
        self.add(NodeKind::TopLevelVariableDeclaration, rule, processor);
    }
    pub fn add_try_statement(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::TryStatement, rule, processor);
    }
    pub fn add_type_argument_list(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::TypeArgumentList, rule, processor);
    }
    pub fn add_type_literal(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::TypeLiteral, rule, processor);
    }
    pub fn add_type_parameter(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::TypeParameter, rule, processor);
    }
    pub fn add_type_parameter_list(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::TypeParameterList, rule, processor);
    }
    pub fn add_variable_declaration(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::VariableDeclaration, rule, processor);
    }
    pub fn add_variable_declaration_list(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::VariableDeclarationList, rule, processor);
    }
    pub fn add_variable_declaration_statement(
        &mut self,
        rule: &'static str,
        processor: NodeProcessor,
    ) {
        self.add(NodeKind::VariableDeclarationStatement, rule, processor);
    }
    pub fn add_when_clause(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::WhenClause, rule, processor);
    }
    pub fn add_while_statement(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::WhileStatement, rule, processor);
    }
    pub fn add_wildcard_pattern(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::WildcardPattern, rule, processor);
    }
    pub fn add_with_clause(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::WithClause, rule, processor);
    }
    pub fn add_yield_statement(&mut self, rule: &'static str, processor: NodeProcessor) {
        self.add(NodeKind::YieldStatement, rule, processor);
    }
}
