// Generated by tools/codegen/gen_legacy_protocol.py. DO NOT EDIT.
// Dart source: pkg/analysis_server/tool/spec/spec_input.html

use serde::{Deserialize, Serialize};

pub const PROTOCOL_VERSION: &str = "1.40.1";
pub const DOMAIN_COUNT: usize = 10;
pub const REQUEST_COUNT: usize = 59;
pub const NOTIFICATION_COUNT: usize = 22;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct DomainMetadata {
    pub name: &'static str,
    pub request_count: usize,
    pub notification_count: usize,
}

pub const DOMAINS: &[DomainMetadata] = &[
    DomainMetadata {
        name: "server",
        request_count: 7,
        notification_count: 5,
    },
    DomainMetadata {
        name: "analysis",
        request_count: 14,
        notification_count: 12,
    },
    DomainMetadata {
        name: "completion",
        request_count: 3,
        notification_count: 1,
    },
    DomainMetadata {
        name: "search",
        request_count: 6,
        notification_count: 1,
    },
    DomainMetadata {
        name: "edit",
        request_count: 14,
        notification_count: 0,
    },
    DomainMetadata {
        name: "execution",
        request_count: 5,
        notification_count: 1,
    },
    DomainMetadata {
        name: "diagnostic",
        request_count: 2,
        notification_count: 0,
    },
    DomainMetadata {
        name: "analytics",
        request_count: 4,
        notification_count: 0,
    },
    DomainMetadata {
        name: "flutter",
        request_count: 3,
        notification_count: 1,
    },
    DomainMetadata {
        name: "lsp",
        request_count: 1,
        notification_count: 1,
    },
];

pub const REQUEST_METHODS: &[&str] = &[
    "server.getVersion",
    "server.shutdown",
    "server.setSubscriptions",
    "server.cancelRequest",
    "server.setClientCapabilities",
    "server.openUrlRequest",
    "server.showMessageRequest",
    "analysis.getErrors",
    "analysis.getHover",
    "analysis.getImportedElements",
    "analysis.getLibraryDependencies",
    "analysis.getNavigation",
    "analysis.getReachableSources",
    "analysis.getSignature",
    "analysis.reanalyze",
    "analysis.setAnalysisRoots",
    "analysis.setGeneralSubscriptions",
    "analysis.setPriorityFiles",
    "analysis.setSubscriptions",
    "analysis.updateContent",
    "analysis.updateOptions",
    "completion.getSuggestions2",
    "completion.registerLibraryPaths",
    "completion.getSuggestionDetails2",
    "search.findElementReferences",
    "search.findMemberDeclarations",
    "search.findMemberReferences",
    "search.findTopLevelDeclarations",
    "search.getElementDeclarations",
    "search.getTypeHierarchy",
    "edit.format",
    "edit.formatIfEnabled",
    "edit.getAssists",
    "edit.getAvailableRefactorings",
    "edit.bulkFixes",
    "edit.getFixes",
    "edit.getPostfixCompletion",
    "edit.getRefactoring",
    "edit.getStatementCompletion",
    "edit.isPostfixCompletionApplicable",
    "edit.listPostfixCompletionTemplates",
    "edit.importElements",
    "edit.sortMembers",
    "edit.organizeDirectives",
    "execution.createContext",
    "execution.deleteContext",
    "execution.getSuggestions",
    "execution.mapUri",
    "execution.setSubscriptions",
    "diagnostic.getDiagnostics",
    "diagnostic.getServerPort",
    "analytics.isEnabled",
    "analytics.enable",
    "analytics.sendEvent",
    "analytics.sendTiming",
    "flutter.getWidgetDescription",
    "flutter.setWidgetPropertyValue",
    "flutter.setSubscriptions",
    "lsp.handle",
];

pub const NOTIFICATION_EVENTS: &[&str] = &[
    "server.connected",
    "server.error",
    "server.pluginError",
    "server.log",
    "server.status",
    "analysis.analyzedFiles",
    "analysis.closingLabels",
    "analysis.errors",
    "analysis.flushResults",
    "analysis.folding",
    "analysis.highlights",
    "analysis.implemented",
    "analysis.invalidate",
    "analysis.navigation",
    "analysis.occurrences",
    "analysis.outline",
    "analysis.overrides",
    "completion.existingImports",
    "search.results",
    "execution.launchData",
    "flutter.outline",
    "lsp.notification",
];

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddContentOverlay {
    #[serde(rename = "type")]
    pub type_: AddContentOverlayType,
    pub content: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub version: Option<i64>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalysisError {
    pub severity: AnalysisErrorSeverity,
    #[serde(rename = "type")]
    pub type_: AnalysisErrorType,
    pub location: Location,
    pub message: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub correction: Option<String>,
    pub code: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "contextMessages", skip_serializing_if = "Option::is_none")]
    pub context_messages: Option<Vec<DiagnosticMessage>>,
    #[serde(rename = "hasFix", skip_serializing_if = "Option::is_none")]
    pub has_fix: Option<bool>,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum AnalysisErrorSeverity {
    #[serde(rename = "INFO")]
    INFO,
    #[serde(rename = "WARNING")]
    WARNING,
    #[serde(rename = "ERROR")]
    ERROR,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum AnalysisErrorType {
    #[serde(rename = "CHECKED_MODE_COMPILE_TIME_ERROR")]
    CheckedModeCompileTimeError,
    #[serde(rename = "COMPILE_TIME_ERROR")]
    CompileTimeError,
    #[serde(rename = "HINT")]
    HINT,
    #[serde(rename = "LINT")]
    LINT,
    #[serde(rename = "STATIC_TYPE_WARNING")]
    StaticTypeWarning,
    #[serde(rename = "STATIC_WARNING")]
    StaticWarning,
    #[serde(rename = "SYNTACTIC_ERROR")]
    SyntacticError,
    #[serde(rename = "TODO")]
    TODO,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssistDescription {
    pub id: String,
    pub message: String,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangeContentOverlay {
    #[serde(rename = "type")]
    pub type_: ChangeContentOverlayType,
    pub edits: Vec<SourceEdit>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub version: Option<i64>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompletionSuggestion {
    pub kind: CompletionSuggestionKind,
    pub relevance: i64,
    pub completion: String,
    #[serde(rename = "displayText", skip_serializing_if = "Option::is_none")]
    pub display_text: Option<String>,
    #[serde(rename = "replacementOffset", skip_serializing_if = "Option::is_none")]
    pub replacement_offset: Option<i64>,
    #[serde(rename = "replacementLength", skip_serializing_if = "Option::is_none")]
    pub replacement_length: Option<i64>,
    #[serde(rename = "selectionOffset")]
    pub selection_offset: i64,
    #[serde(rename = "selectionLength")]
    pub selection_length: i64,
    #[serde(rename = "isDeprecated")]
    pub is_deprecated: bool,
    #[serde(rename = "isPotential")]
    pub is_potential: bool,
    #[serde(rename = "docSummary", skip_serializing_if = "Option::is_none")]
    pub doc_summary: Option<String>,
    #[serde(rename = "docComplete", skip_serializing_if = "Option::is_none")]
    pub doc_complete: Option<String>,
    #[serde(rename = "declaringType", skip_serializing_if = "Option::is_none")]
    pub declaring_type: Option<String>,
    #[serde(
        rename = "defaultArgumentListString",
        skip_serializing_if = "Option::is_none"
    )]
    pub default_argument_list_string: Option<String>,
    #[serde(
        rename = "defaultArgumentListTextRanges",
        skip_serializing_if = "Option::is_none"
    )]
    pub default_argument_list_text_ranges: Option<Vec<i64>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub element: Option<Element>,
    #[serde(rename = "returnType", skip_serializing_if = "Option::is_none")]
    pub return_type: Option<String>,
    #[serde(rename = "parameterNames", skip_serializing_if = "Option::is_none")]
    pub parameter_names: Option<Vec<String>>,
    #[serde(rename = "parameterTypes", skip_serializing_if = "Option::is_none")]
    pub parameter_types: Option<Vec<String>>,
    #[serde(
        rename = "requiredParameterCount",
        skip_serializing_if = "Option::is_none"
    )]
    pub required_parameter_count: Option<i64>,
    #[serde(rename = "hasNamedParameters", skip_serializing_if = "Option::is_none")]
    pub has_named_parameters: Option<bool>,
    #[serde(rename = "parameterName", skip_serializing_if = "Option::is_none")]
    pub parameter_name: Option<String>,
    #[serde(rename = "parameterType", skip_serializing_if = "Option::is_none")]
    pub parameter_type: Option<String>,
    #[serde(rename = "libraryUri", skip_serializing_if = "Option::is_none")]
    pub library_uri: Option<String>,
    #[serde(rename = "isNotImported", skip_serializing_if = "Option::is_none")]
    pub is_not_imported: Option<bool>,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum CompletionSuggestionKind {
    #[serde(rename = "ARGUMENT_LIST")]
    ArgumentList,
    #[serde(rename = "IMPORT")]
    IMPORT,
    #[serde(rename = "IDENTIFIER")]
    IDENTIFIER,
    #[serde(rename = "INVOCATION")]
    INVOCATION,
    #[serde(rename = "KEYWORD")]
    KEYWORD,
    #[serde(rename = "NAMED_ARGUMENT")]
    NamedArgument,
    #[serde(rename = "OPTIONAL_ARGUMENT")]
    OptionalArgument,
    #[serde(rename = "OVERRIDE")]
    OVERRIDE,
    #[serde(rename = "PARAMETER")]
    PARAMETER,
    #[serde(rename = "PACKAGE_NAME")]
    PackageName,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiagnosticMessage {
    pub message: String,
    pub location: Location,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Element {
    pub kind: ElementKind,
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location: Option<Location>,
    pub flags: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parameters: Option<String>,
    #[serde(rename = "returnType", skip_serializing_if = "Option::is_none")]
    pub return_type: Option<String>,
    #[serde(rename = "typeParameters", skip_serializing_if = "Option::is_none")]
    pub type_parameters: Option<String>,
    #[serde(rename = "aliasedType", skip_serializing_if = "Option::is_none")]
    pub aliased_type: Option<String>,
    #[serde(rename = "extendedType", skip_serializing_if = "Option::is_none")]
    pub extended_type: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum ElementKind {
    #[serde(rename = "CLASS")]
    CLASS,
    #[serde(rename = "CLASS_TYPE_ALIAS")]
    ClassTypeAlias,
    #[serde(rename = "COMPILATION_UNIT")]
    CompilationUnit,
    #[serde(rename = "CONSTRUCTOR")]
    CONSTRUCTOR,
    #[serde(rename = "CONSTRUCTOR_INVOCATION")]
    ConstructorInvocation,
    #[serde(rename = "ENUM")]
    ENUM,
    #[serde(rename = "ENUM_CONSTANT")]
    EnumConstant,
    #[serde(rename = "EXTENSION")]
    EXTENSION,
    #[serde(rename = "EXTENSION_TYPE")]
    ExtensionType,
    #[serde(rename = "FIELD")]
    FIELD,
    #[serde(rename = "FILE")]
    FILE,
    #[serde(rename = "FUNCTION")]
    FUNCTION,
    #[serde(rename = "FUNCTION_INVOCATION")]
    FunctionInvocation,
    #[serde(rename = "FUNCTION_TYPE_ALIAS")]
    FunctionTypeAlias,
    #[serde(rename = "GETTER")]
    GETTER,
    #[serde(rename = "LABEL")]
    LABEL,
    #[serde(rename = "LIBRARY")]
    LIBRARY,
    #[serde(rename = "LOCAL_VARIABLE")]
    LocalVariable,
    #[serde(rename = "METHOD")]
    METHOD,
    #[serde(rename = "MIXIN")]
    MIXIN,
    #[serde(rename = "PARAMETER")]
    PARAMETER,
    #[serde(rename = "PREFIX")]
    PREFIX,
    #[serde(rename = "SETTER")]
    SETTER,
    #[serde(rename = "TOP_LEVEL_VARIABLE")]
    TopLevelVariable,
    #[serde(rename = "TYPE_ALIAS")]
    TypeAlias,
    #[serde(rename = "TYPE_PARAMETER")]
    TypeParameter,
    #[serde(rename = "UNIT_TEST_GROUP")]
    UnitTestGroup,
    #[serde(rename = "UNIT_TEST_TEST")]
    UnitTestTest,
    #[serde(rename = "UNKNOWN")]
    UNKNOWN,
}

pub type FilePath = String;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FixDescription {
    pub id: String,
    pub message: String,
    pub codes: Vec<String>,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum FoldingKind {
    #[serde(rename = "ANNOTATIONS")]
    ANNOTATIONS,
    #[serde(rename = "BLOCK")]
    BLOCK,
    #[serde(rename = "CLASS_BODY")]
    ClassBody,
    #[serde(rename = "COMMENT")]
    COMMENT,
    #[serde(rename = "DIRECTIVES")]
    DIRECTIVES,
    #[serde(rename = "DOCUMENTATION_COMMENT")]
    DocumentationComment,
    #[serde(rename = "FILE_HEADER")]
    FileHeader,
    #[serde(rename = "FUNCTION_BODY")]
    FunctionBody,
    #[serde(rename = "INVOCATION")]
    INVOCATION,
    #[serde(rename = "LITERAL")]
    LITERAL,
    #[serde(rename = "PARAMETERS")]
    PARAMETERS,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FoldingRegion {
    pub kind: FoldingKind,
    pub offset: i64,
    pub length: i64,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct HighlightRegion {
    #[serde(rename = "type")]
    pub type_: HighlightRegionType,
    pub offset: i64,
    pub length: i64,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum HighlightRegionType {
    #[serde(rename = "ANNOTATION")]
    ANNOTATION,
    #[serde(rename = "BUILT_IN")]
    BuiltIn,
    #[serde(rename = "CLASS")]
    CLASS,
    #[serde(rename = "COMMENT_BLOCK")]
    CommentBlock,
    #[serde(rename = "COMMENT_DOCUMENTATION")]
    CommentDocumentation,
    #[serde(rename = "COMMENT_END_OF_LINE")]
    CommentEndOfLine,
    #[serde(rename = "CONSTRUCTOR")]
    CONSTRUCTOR,
    #[serde(rename = "CONSTRUCTOR_TEAR_OFF")]
    ConstructorTearOff,
    #[serde(rename = "DIRECTIVE")]
    DIRECTIVE,
    #[serde(rename = "DYNAMIC_TYPE")]
    DynamicType,
    #[serde(rename = "DYNAMIC_LOCAL_VARIABLE_DECLARATION")]
    DynamicLocalVariableDeclaration,
    #[serde(rename = "DYNAMIC_LOCAL_VARIABLE_REFERENCE")]
    DynamicLocalVariableReference,
    #[serde(rename = "DYNAMIC_PARAMETER_DECLARATION")]
    DynamicParameterDeclaration,
    #[serde(rename = "DYNAMIC_PARAMETER_REFERENCE")]
    DynamicParameterReference,
    #[serde(rename = "ENUM")]
    ENUM,
    #[serde(rename = "ENUM_CONSTANT")]
    EnumConstant,
    #[serde(rename = "EXTENSION")]
    EXTENSION,
    #[serde(rename = "EXTENSION_TYPE")]
    ExtensionType,
    #[serde(rename = "FIELD")]
    FIELD,
    #[serde(rename = "FIELD_STATIC")]
    FieldStatic,
    #[serde(rename = "FUNCTION")]
    FUNCTION,
    #[serde(rename = "FUNCTION_DECLARATION")]
    FunctionDeclaration,
    #[serde(rename = "FUNCTION_TYPE_ALIAS")]
    FunctionTypeAlias,
    #[serde(rename = "GETTER_DECLARATION")]
    GetterDeclaration,
    #[serde(rename = "IDENTIFIER_DEFAULT")]
    IdentifierDefault,
    #[serde(rename = "IMPORT_PREFIX")]
    ImportPrefix,
    #[serde(rename = "INSTANCE_FIELD_DECLARATION")]
    InstanceFieldDeclaration,
    #[serde(rename = "INSTANCE_FIELD_REFERENCE")]
    InstanceFieldReference,
    #[serde(rename = "INSTANCE_GETTER_DECLARATION")]
    InstanceGetterDeclaration,
    #[serde(rename = "INSTANCE_GETTER_REFERENCE")]
    InstanceGetterReference,
    #[serde(rename = "INSTANCE_METHOD_DECLARATION")]
    InstanceMethodDeclaration,
    #[serde(rename = "INSTANCE_METHOD_REFERENCE")]
    InstanceMethodReference,
    #[serde(rename = "INSTANCE_METHOD_TEAR_OFF")]
    InstanceMethodTearOff,
    #[serde(rename = "INSTANCE_SETTER_DECLARATION")]
    InstanceSetterDeclaration,
    #[serde(rename = "INSTANCE_SETTER_REFERENCE")]
    InstanceSetterReference,
    #[serde(rename = "INVALID_STRING_ESCAPE")]
    InvalidStringEscape,
    #[serde(rename = "KEYWORD")]
    KEYWORD,
    #[serde(rename = "LABEL")]
    LABEL,
    #[serde(rename = "LIBRARY_NAME")]
    LibraryName,
    #[serde(rename = "LITERAL_BOOLEAN")]
    LiteralBoolean,
    #[serde(rename = "LITERAL_DOUBLE")]
    LiteralDouble,
    #[serde(rename = "LITERAL_INTEGER")]
    LiteralInteger,
    #[serde(rename = "LITERAL_LIST")]
    LiteralList,
    #[serde(rename = "LITERAL_MAP")]
    LiteralMap,
    #[serde(rename = "LITERAL_RECORD")]
    LiteralRecord,
    #[serde(rename = "LITERAL_STRING")]
    LiteralString,
    #[serde(rename = "LOCAL_FUNCTION_DECLARATION")]
    LocalFunctionDeclaration,
    #[serde(rename = "LOCAL_FUNCTION_REFERENCE")]
    LocalFunctionReference,
    #[serde(rename = "LOCAL_FUNCTION_TEAR_OFF")]
    LocalFunctionTearOff,
    #[serde(rename = "LOCAL_VARIABLE")]
    LocalVariable,
    #[serde(rename = "LOCAL_VARIABLE_DECLARATION")]
    LocalVariableDeclaration,
    #[serde(rename = "LOCAL_VARIABLE_REFERENCE")]
    LocalVariableReference,
    #[serde(rename = "METHOD")]
    METHOD,
    #[serde(rename = "METHOD_DECLARATION")]
    MethodDeclaration,
    #[serde(rename = "METHOD_DECLARATION_STATIC")]
    MethodDeclarationStatic,
    #[serde(rename = "METHOD_STATIC")]
    MethodStatic,
    #[serde(rename = "MIXIN")]
    MIXIN,
    #[serde(rename = "PARAMETER")]
    PARAMETER,
    #[serde(rename = "SETTER_DECLARATION")]
    SetterDeclaration,
    #[serde(rename = "TOP_LEVEL_VARIABLE")]
    TopLevelVariable,
    #[serde(rename = "PARAMETER_DECLARATION")]
    ParameterDeclaration,
    #[serde(rename = "PARAMETER_REFERENCE")]
    ParameterReference,
    #[serde(rename = "STATIC_FIELD_DECLARATION")]
    StaticFieldDeclaration,
    #[serde(rename = "STATIC_GETTER_DECLARATION")]
    StaticGetterDeclaration,
    #[serde(rename = "STATIC_GETTER_REFERENCE")]
    StaticGetterReference,
    #[serde(rename = "STATIC_METHOD_DECLARATION")]
    StaticMethodDeclaration,
    #[serde(rename = "STATIC_METHOD_REFERENCE")]
    StaticMethodReference,
    #[serde(rename = "STATIC_METHOD_TEAR_OFF")]
    StaticMethodTearOff,
    #[serde(rename = "STATIC_SETTER_DECLARATION")]
    StaticSetterDeclaration,
    #[serde(rename = "STATIC_SETTER_REFERENCE")]
    StaticSetterReference,
    #[serde(rename = "TOP_LEVEL_FUNCTION_DECLARATION")]
    TopLevelFunctionDeclaration,
    #[serde(rename = "TOP_LEVEL_FUNCTION_REFERENCE")]
    TopLevelFunctionReference,
    #[serde(rename = "TOP_LEVEL_FUNCTION_TEAR_OFF")]
    TopLevelFunctionTearOff,
    #[serde(rename = "TOP_LEVEL_GETTER_DECLARATION")]
    TopLevelGetterDeclaration,
    #[serde(rename = "TOP_LEVEL_GETTER_REFERENCE")]
    TopLevelGetterReference,
    #[serde(rename = "TOP_LEVEL_SETTER_DECLARATION")]
    TopLevelSetterDeclaration,
    #[serde(rename = "TOP_LEVEL_SETTER_REFERENCE")]
    TopLevelSetterReference,
    #[serde(rename = "TOP_LEVEL_VARIABLE_DECLARATION")]
    TopLevelVariableDeclaration,
    #[serde(rename = "TYPE_ALIAS")]
    TypeAlias,
    #[serde(rename = "TYPE_NAME_DYNAMIC")]
    TypeNameDynamic,
    #[serde(rename = "TYPE_PARAMETER")]
    TypeParameter,
    #[serde(rename = "UNRESOLVED_INSTANCE_MEMBER_REFERENCE")]
    UnresolvedInstanceMemberReference,
    #[serde(rename = "VALID_STRING_ESCAPE")]
    ValidStringEscape,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LinkedEditGroup {
    pub positions: Vec<Position>,
    pub length: i64,
    pub suggestions: Vec<LinkedEditSuggestion>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LinkedEditSuggestion {
    pub value: String,
    pub kind: LinkedEditSuggestionKind,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum LinkedEditSuggestionKind {
    #[serde(rename = "METHOD")]
    METHOD,
    #[serde(rename = "PARAMETER")]
    PARAMETER,
    #[serde(rename = "TYPE")]
    TYPE,
    #[serde(rename = "VARIABLE")]
    VARIABLE,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Location {
    pub file: FilePath,
    pub offset: i64,
    pub length: i64,
    #[serde(rename = "startLine")]
    pub start_line: i64,
    #[serde(rename = "startColumn")]
    pub start_column: i64,
    #[serde(rename = "endLine", skip_serializing_if = "Option::is_none")]
    pub end_line: Option<i64>,
    #[serde(rename = "endColumn", skip_serializing_if = "Option::is_none")]
    pub end_column: Option<i64>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NavigationRegion {
    pub offset: i64,
    pub length: i64,
    pub targets: Vec<i64>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NavigationTarget {
    pub kind: ElementKind,
    #[serde(rename = "fileIndex")]
    pub file_index: i64,
    pub offset: i64,
    pub length: i64,
    #[serde(rename = "startLine")]
    pub start_line: i64,
    #[serde(rename = "startColumn")]
    pub start_column: i64,
    #[serde(rename = "codeOffset", skip_serializing_if = "Option::is_none")]
    pub code_offset: Option<i64>,
    #[serde(rename = "codeLength", skip_serializing_if = "Option::is_none")]
    pub code_length: Option<i64>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Occurrences {
    pub element: Element,
    pub offsets: Vec<i64>,
    pub length: i64,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Outline {
    pub element: Element,
    pub offset: i64,
    pub length: i64,
    #[serde(rename = "codeOffset")]
    pub code_offset: i64,
    #[serde(rename = "codeLength")]
    pub code_length: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub children: Option<Vec<Outline>>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ParameterInfo {
    pub kind: ParameterKind,
    pub name: String,
    #[serde(rename = "type")]
    pub type_: String,
    #[serde(rename = "defaultValue", skip_serializing_if = "Option::is_none")]
    pub default_value: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum ParameterKind {
    #[serde(rename = "OPTIONAL_NAMED")]
    OptionalNamed,
    #[serde(rename = "OPTIONAL_POSITIONAL")]
    OptionalPositional,
    #[serde(rename = "REQUIRED_NAMED")]
    RequiredNamed,
    #[serde(rename = "REQUIRED_POSITIONAL")]
    RequiredPositional,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PluginDetails {
    pub name: String,
    #[serde(rename = "lintRules")]
    pub lint_rules: Vec<String>,
    #[serde(rename = "warningRules")]
    pub warning_rules: Vec<String>,
    pub assists: Vec<AssistDescription>,
    pub fixes: Vec<FixDescription>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PluginPrint {
    #[serde(rename = "pluginName")]
    pub plugin_name: String,
    pub message: String,
    pub timestamp: i64,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Position {
    pub file: FilePath,
    pub offset: i64,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum RefactoringKind {
    #[serde(rename = "CONVERT_GETTER_TO_METHOD")]
    ConvertGetterToMethod,
    #[serde(rename = "CONVERT_METHOD_TO_GETTER")]
    ConvertMethodToGetter,
    #[serde(rename = "EXTRACT_LOCAL_VARIABLE")]
    ExtractLocalVariable,
    #[serde(rename = "EXTRACT_METHOD")]
    ExtractMethod,
    #[serde(rename = "EXTRACT_WIDGET")]
    ExtractWidget,
    #[serde(rename = "INLINE_LOCAL_VARIABLE")]
    InlineLocalVariable,
    #[serde(rename = "INLINE_METHOD")]
    InlineMethod,
    #[serde(rename = "MOVE_FILE")]
    MoveFile,
    #[serde(rename = "RENAME")]
    RENAME,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RefactoringMethodParameter {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    pub kind: RefactoringMethodParameterKind,
    #[serde(rename = "type")]
    pub type_: String,
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parameters: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum RefactoringMethodParameterKind {
    #[serde(rename = "REQUIRED")]
    REQUIRED,
    #[serde(rename = "POSITIONAL")]
    POSITIONAL,
    #[serde(rename = "NAMED")]
    NAMED,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RefactoringProblem {
    pub severity: RefactoringProblemSeverity,
    pub message: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location: Option<Location>,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum RefactoringProblemSeverity {
    #[serde(rename = "INFO")]
    INFO,
    #[serde(rename = "WARNING")]
    WARNING,
    #[serde(rename = "ERROR")]
    ERROR,
    #[serde(rename = "FATAL")]
    FATAL,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemoveContentOverlay {
    #[serde(rename = "type")]
    pub type_: RemoveContentOverlayType,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SourceChange {
    pub message: String,
    pub edits: Vec<SourceFileEdit>,
    #[serde(rename = "linkedEditGroups")]
    pub linked_edit_groups: Vec<LinkedEditGroup>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub selection: Option<Position>,
    #[serde(rename = "selectionLength", skip_serializing_if = "Option::is_none")]
    pub selection_length: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SourceEdit {
    pub offset: i64,
    pub length: i64,
    pub replacement: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SourceFileEdit {
    pub file: FilePath,
    #[serde(rename = "fileStamp")]
    pub file_stamp: i64,
    pub edits: Vec<SourceEdit>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalysisErrorFixes {
    pub error: AnalysisError,
    pub fixes: Vec<SourceChange>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalysisOptions {
    #[serde(rename = "enableAsync", skip_serializing_if = "Option::is_none")]
    pub enable_async: Option<bool>,
    #[serde(
        rename = "enableDeferredLoading",
        skip_serializing_if = "Option::is_none"
    )]
    pub enable_deferred_loading: Option<bool>,
    #[serde(rename = "enableEnums", skip_serializing_if = "Option::is_none")]
    pub enable_enums: Option<bool>,
    #[serde(
        rename = "enableNullAwareOperators",
        skip_serializing_if = "Option::is_none"
    )]
    pub enable_null_aware_operators: Option<bool>,
    #[serde(
        rename = "generateDart2jsHints",
        skip_serializing_if = "Option::is_none"
    )]
    pub generate_dart2js_hints: Option<bool>,
    #[serde(rename = "generateHints", skip_serializing_if = "Option::is_none")]
    pub generate_hints: Option<bool>,
    #[serde(rename = "generateLints", skip_serializing_if = "Option::is_none")]
    pub generate_lints: Option<bool>,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum AnalysisService {
    #[serde(rename = "CLOSING_LABELS")]
    ClosingLabels,
    #[serde(rename = "FOLDING")]
    FOLDING,
    #[serde(rename = "HIGHLIGHTS")]
    HIGHLIGHTS,
    #[serde(rename = "IMPLEMENTED")]
    IMPLEMENTED,
    #[serde(rename = "INVALIDATE")]
    INVALIDATE,
    #[serde(rename = "NAVIGATION")]
    NAVIGATION,
    #[serde(rename = "OCCURRENCES")]
    OCCURRENCES,
    #[serde(rename = "OUTLINE")]
    OUTLINE,
    #[serde(rename = "OVERRIDES")]
    OVERRIDES,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalysisStatus {
    #[serde(rename = "isAnalyzing")]
    pub is_analyzing: bool,
    #[serde(rename = "analysisTarget", skip_serializing_if = "Option::is_none")]
    pub analysis_target: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkFix {
    pub path: FilePath,
    pub fixes: Vec<BulkFixDetail>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkFixDetail {
    pub code: String,
    pub occurrences: i64,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClosingLabel {
    pub offset: i64,
    pub length: i64,
    pub label: String,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContextData {
    pub name: String,
    #[serde(rename = "explicitFileCount")]
    pub explicit_file_count: i64,
    #[serde(rename = "implicitFileCount")]
    pub implicit_file_count: i64,
    #[serde(rename = "workItemQueueLength")]
    pub work_item_queue_length: i64,
    #[serde(rename = "cacheEntryExceptions")]
    pub cache_entry_exceptions: Vec<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ElementDeclaration {
    pub name: String,
    pub kind: ElementKind,
    #[serde(rename = "fileIndex")]
    pub file_index: i64,
    pub offset: i64,
    pub line: i64,
    pub column: i64,
    #[serde(rename = "codeOffset")]
    pub code_offset: i64,
    #[serde(rename = "codeLength")]
    pub code_length: i64,
    #[serde(rename = "className", skip_serializing_if = "Option::is_none")]
    pub class_name: Option<String>,
    #[serde(rename = "mixinName", skip_serializing_if = "Option::is_none")]
    pub mixin_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parameters: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExecutableFile {
    pub file: FilePath,
    pub kind: ExecutableKind,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum ExecutableKind {
    #[serde(rename = "CLIENT")]
    CLIENT,
    #[serde(rename = "EITHER")]
    EITHER,
    #[serde(rename = "NOT_EXECUTABLE")]
    NotExecutable,
    #[serde(rename = "SERVER")]
    SERVER,
}

pub type ExecutionContextId = String;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExistingImport {
    pub uri: i64,
    pub elements: Vec<i64>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExistingImports {
    pub elements: ImportedElementSet,
    pub imports: Vec<ExistingImport>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImportedElementSet {
    pub strings: Vec<String>,
    pub uris: Vec<i64>,
    pub names: Vec<i64>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LibraryPathSet {
    pub scope: FilePath,
    #[serde(rename = "libraryPaths")]
    pub library_paths: Vec<FilePath>,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum CompletionMode {
    #[serde(rename = "BASIC")]
    BASIC,
    #[serde(rename = "SMART")]
    SMART,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum CompletionCaseMatchingMode {
    #[serde(rename = "FIRST_CHAR")]
    FirstChar,
    #[serde(rename = "ALL_CHARS")]
    AllChars,
    #[serde(rename = "NONE")]
    NONE,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageAction {
    pub label: String,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum MessageType {
    #[serde(rename = "ERROR")]
    ERROR,
    #[serde(rename = "WARNING")]
    WARNING,
    #[serde(rename = "INFO")]
    INFO,
    #[serde(rename = "LOG")]
    LOG,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RuntimeCompletionExpression {
    pub offset: i64,
    pub length: i64,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub type_: Option<RuntimeCompletionExpressionType>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RuntimeCompletionVariable {
    pub name: String,
    #[serde(rename = "type")]
    pub type_: RuntimeCompletionExpressionType,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RuntimeCompletionExpressionType {
    #[serde(rename = "libraryPath", skip_serializing_if = "Option::is_none")]
    pub library_path: Option<FilePath>,
    pub kind: RuntimeCompletionExpressionTypeKind,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "typeArguments", skip_serializing_if = "Option::is_none")]
    pub type_arguments: Option<Vec<RuntimeCompletionExpressionType>>,
    #[serde(rename = "returnType", skip_serializing_if = "Option::is_none")]
    pub return_type: Option<Box<RuntimeCompletionExpressionType>>,
    #[serde(rename = "parameterTypes", skip_serializing_if = "Option::is_none")]
    pub parameter_types: Option<Vec<RuntimeCompletionExpressionType>>,
    #[serde(rename = "parameterNames", skip_serializing_if = "Option::is_none")]
    pub parameter_names: Option<Vec<String>>,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum RuntimeCompletionExpressionTypeKind {
    #[serde(rename = "DYNAMIC")]
    DYNAMIC,
    #[serde(rename = "FUNCTION")]
    FUNCTION,
    #[serde(rename = "INTERFACE")]
    INTERFACE,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum ExecutionService {
    #[serde(rename = "LAUNCH_DATA")]
    LaunchData,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum FileKind {
    #[serde(rename = "LIBRARY")]
    LIBRARY,
    #[serde(rename = "PART")]
    PART,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FlutterWidgetProperty {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub documentation: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expression: Option<String>,
    pub id: i64,
    #[serde(rename = "isRequired")]
    pub is_required: bool,
    #[serde(rename = "isSafeToUpdate")]
    pub is_safe_to_update: bool,
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub children: Option<Vec<FlutterWidgetProperty>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub editor: Option<FlutterWidgetPropertyEditor>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub value: Option<FlutterWidgetPropertyValue>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FlutterWidgetPropertyEditor {
    pub kind: FlutterWidgetPropertyEditorKind,
    #[serde(rename = "enumItems", skip_serializing_if = "Option::is_none")]
    pub enum_items: Option<Vec<FlutterWidgetPropertyValueEnumItem>>,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum FlutterWidgetPropertyEditorKind {
    #[serde(rename = "BOOL")]
    BOOL,
    #[serde(rename = "DOUBLE")]
    DOUBLE,
    #[serde(rename = "ENUM")]
    ENUM,
    #[serde(rename = "ENUM_LIKE")]
    EnumLike,
    #[serde(rename = "INT")]
    INT,
    #[serde(rename = "STRING")]
    STRING,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FlutterWidgetPropertyValue {
    #[serde(rename = "boolValue", skip_serializing_if = "Option::is_none")]
    pub bool_value: Option<bool>,
    #[serde(rename = "doubleValue", skip_serializing_if = "Option::is_none")]
    pub double_value: Option<f64>,
    #[serde(rename = "intValue", skip_serializing_if = "Option::is_none")]
    pub int_value: Option<i64>,
    #[serde(rename = "stringValue", skip_serializing_if = "Option::is_none")]
    pub string_value: Option<String>,
    #[serde(rename = "enumValue", skip_serializing_if = "Option::is_none")]
    pub enum_value: Option<FlutterWidgetPropertyValueEnumItem>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expression: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FlutterWidgetPropertyValueEnumItem {
    #[serde(rename = "libraryUri")]
    pub library_uri: String,
    #[serde(rename = "className")]
    pub class_name: String,
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub documentation: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum FlutterService {
    #[serde(rename = "OUTLINE")]
    OUTLINE,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FlutterOutline {
    pub kind: FlutterOutlineKind,
    pub offset: i64,
    pub length: i64,
    #[serde(rename = "codeOffset")]
    pub code_offset: i64,
    #[serde(rename = "codeLength")]
    pub code_length: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "dartElement", skip_serializing_if = "Option::is_none")]
    pub dart_element: Option<Element>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Vec<FlutterOutlineAttribute>>,
    #[serde(rename = "className", skip_serializing_if = "Option::is_none")]
    pub class_name: Option<String>,
    #[serde(
        rename = "parentAssociationLabel",
        skip_serializing_if = "Option::is_none"
    )]
    pub parent_association_label: Option<String>,
    #[serde(rename = "variableName", skip_serializing_if = "Option::is_none")]
    pub variable_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub children: Option<Vec<FlutterOutline>>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FlutterOutlineAttribute {
    pub name: String,
    pub label: String,
    #[serde(
        rename = "literalValueBoolean",
        skip_serializing_if = "Option::is_none"
    )]
    pub literal_value_boolean: Option<bool>,
    #[serde(
        rename = "literalValueInteger",
        skip_serializing_if = "Option::is_none"
    )]
    pub literal_value_integer: Option<i64>,
    #[serde(rename = "literalValueString", skip_serializing_if = "Option::is_none")]
    pub literal_value_string: Option<String>,
    #[serde(rename = "nameLocation", skip_serializing_if = "Option::is_none")]
    pub name_location: Option<Location>,
    #[serde(rename = "valueLocation", skip_serializing_if = "Option::is_none")]
    pub value_location: Option<Location>,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum FlutterOutlineKind {
    #[serde(rename = "DART_ELEMENT")]
    DartElement,
    #[serde(rename = "GENERIC")]
    GENERIC,
    #[serde(rename = "NEW_INSTANCE")]
    NewInstance,
    #[serde(rename = "INVOCATION")]
    INVOCATION,
    #[serde(rename = "VARIABLE")]
    VARIABLE,
    #[serde(rename = "PLACEHOLDER")]
    PLACEHOLDER,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum GeneralAnalysisService {
    #[serde(rename = "ANALYZED_FILES")]
    AnalyzedFiles,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct HoverInformation {
    pub offset: i64,
    pub length: i64,
    #[serde(
        rename = "containingLibraryPath",
        skip_serializing_if = "Option::is_none"
    )]
    pub containing_library_path: Option<String>,
    #[serde(
        rename = "containingLibraryName",
        skip_serializing_if = "Option::is_none"
    )]
    pub containing_library_name: Option<String>,
    #[serde(
        rename = "containingClassDescription",
        skip_serializing_if = "Option::is_none"
    )]
    pub containing_class_description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dartdoc: Option<String>,
    #[serde(rename = "elementDescription", skip_serializing_if = "Option::is_none")]
    pub element_description: Option<String>,
    #[serde(rename = "elementKind", skip_serializing_if = "Option::is_none")]
    pub element_kind: Option<String>,
    #[serde(rename = "isDeprecated", skip_serializing_if = "Option::is_none")]
    pub is_deprecated: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parameter: Option<String>,
    #[serde(rename = "propagatedType", skip_serializing_if = "Option::is_none")]
    pub propagated_type: Option<String>,
    #[serde(rename = "staticType", skip_serializing_if = "Option::is_none")]
    pub static_type: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImplementedClass {
    pub offset: i64,
    pub length: i64,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImplementedMember {
    pub offset: i64,
    pub length: i64,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImportedElements {
    pub path: FilePath,
    pub prefix: String,
    pub elements: Vec<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Override {
    pub offset: i64,
    pub length: i64,
    #[serde(rename = "superclassMember", skip_serializing_if = "Option::is_none")]
    pub superclass_member: Option<OverriddenMember>,
    #[serde(rename = "interfaceMembers", skip_serializing_if = "Option::is_none")]
    pub interface_members: Option<Vec<OverriddenMember>>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct OverriddenMember {
    pub element: Element,
    #[serde(rename = "className")]
    pub class_name: String,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostfixTemplateDescriptor {
    pub name: String,
    pub key: String,
    pub example: String,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PubStatus {
    #[serde(rename = "isListingPackageDirs")]
    pub is_listing_package_dirs: bool,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RefactoringFeedback {}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RefactoringOptions {}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RequestError {
    pub code: RequestErrorCode,
    pub message: String,
    #[serde(rename = "stackTrace", skip_serializing_if = "Option::is_none")]
    pub stack_trace: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum RequestErrorCode {
    #[serde(rename = "CONTENT_MODIFIED")]
    ContentModified,
    #[serde(rename = "DEBUG_PORT_COULD_NOT_BE_OPENED")]
    DebugPortCouldNotBeOpened,
    #[serde(rename = "FILE_NOT_ANALYZED")]
    FileNotAnalyzed,
    #[serde(rename = "FLUTTER_GET_WIDGET_DESCRIPTION_CONTENT_MODIFIED")]
    FlutterGetWidgetDescriptionContentModified,
    #[serde(rename = "FLUTTER_GET_WIDGET_DESCRIPTION_NO_WIDGET")]
    FlutterGetWidgetDescriptionNoWidget,
    #[serde(rename = "FLUTTER_SET_WIDGET_PROPERTY_VALUE_INVALID_EXPRESSION")]
    FlutterSetWidgetPropertyValueInvalidExpression,
    #[serde(rename = "FLUTTER_SET_WIDGET_PROPERTY_VALUE_INVALID_ID")]
    FlutterSetWidgetPropertyValueInvalidId,
    #[serde(rename = "FLUTTER_SET_WIDGET_PROPERTY_VALUE_IS_REQUIRED")]
    FlutterSetWidgetPropertyValueIsRequired,
    #[serde(rename = "FORMAT_INVALID_FILE")]
    FormatInvalidFile,
    #[serde(rename = "FORMAT_WITH_ERRORS")]
    FormatWithErrors,
    #[serde(rename = "GET_ERRORS_INVALID_FILE")]
    GetErrorsInvalidFile,
    #[serde(rename = "GET_FIXES_INVALID_FILE")]
    GetFixesInvalidFile,
    #[serde(rename = "GET_IMPORTED_ELEMENTS_INVALID_FILE")]
    GetImportedElementsInvalidFile,
    #[serde(rename = "GET_NAVIGATION_INVALID_FILE")]
    GetNavigationInvalidFile,
    #[serde(rename = "GET_REACHABLE_SOURCES_INVALID_FILE")]
    GetReachableSourcesInvalidFile,
    #[serde(rename = "GET_SIGNATURE_INVALID_FILE")]
    GetSignatureInvalidFile,
    #[serde(rename = "GET_SIGNATURE_INVALID_OFFSET")]
    GetSignatureInvalidOffset,
    #[serde(rename = "GET_SIGNATURE_UNKNOWN_FUNCTION")]
    GetSignatureUnknownFunction,
    #[serde(rename = "IMPORT_ELEMENTS_INVALID_FILE")]
    ImportElementsInvalidFile,
    #[serde(rename = "INVALID_ANALYSIS_ROOT")]
    InvalidAnalysisRoot,
    #[serde(rename = "INVALID_EXECUTION_CONTEXT")]
    InvalidExecutionContext,
    #[serde(rename = "INVALID_FILE_PATH_FORMAT")]
    InvalidFilePathFormat,
    #[serde(rename = "INVALID_OVERLAY_CHANGE")]
    InvalidOverlayChange,
    #[serde(rename = "INVALID_PARAMETER")]
    InvalidParameter,
    #[serde(rename = "INVALID_REQUEST")]
    InvalidRequest,
    #[serde(rename = "ORGANIZE_DIRECTIVES_ERROR")]
    OrganizeDirectivesError,
    #[serde(rename = "REFACTORING_REQUEST_CANCELLED")]
    RefactoringRequestCancelled,
    #[serde(rename = "SERVER_ALREADY_STARTED")]
    ServerAlreadyStarted,
    #[serde(rename = "SERVER_ERROR")]
    ServerError,
    #[serde(rename = "SORT_MEMBERS_INVALID_FILE")]
    SortMembersInvalidFile,
    #[serde(rename = "SORT_MEMBERS_PARSE_ERRORS")]
    SortMembersParseErrors,
    #[serde(rename = "UNKNOWN_REQUEST")]
    UnknownRequest,
    #[serde(rename = "UNSUPPORTED_FEATURE")]
    UnsupportedFeature,
}

pub type SearchId = String;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchResult {
    pub location: Location,
    pub kind: SearchResultKind,
    #[serde(rename = "isPotential")]
    pub is_potential: bool,
    pub path: Vec<Element>,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum SearchResultKind {
    #[serde(rename = "DECLARATION")]
    DECLARATION,
    #[serde(rename = "INVOCATION")]
    INVOCATION,
    #[serde(rename = "READ")]
    READ,
    #[serde(rename = "READ_WRITE")]
    ReadWrite,
    #[serde(rename = "REFERENCE")]
    REFERENCE,
    #[serde(rename = "UNKNOWN")]
    UNKNOWN,
    #[serde(rename = "WRITE")]
    WRITE,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum ServerService {
    #[serde(rename = "LOG")]
    LOG,
    #[serde(rename = "STATUS")]
    STATUS,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TypeHierarchyItem {
    #[serde(rename = "classElement")]
    pub class_element: Element,
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(rename = "memberElement", skip_serializing_if = "Option::is_none")]
    pub member_element: Option<Element>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub superclass: Option<i64>,
    pub interfaces: Vec<i64>,
    pub mixins: Vec<i64>,
    pub subclasses: Vec<i64>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerLogEntry {
    pub time: i64,
    pub kind: ServerLogEntryKind,
    pub data: String,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum ServerLogEntryKind {
    #[serde(rename = "NOTIFICATION")]
    NOTIFICATION,
    #[serde(rename = "RAW")]
    RAW,
    #[serde(rename = "REQUEST")]
    REQUEST,
    #[serde(rename = "RESPONSE")]
    RESPONSE,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerGetVersionResult {
    pub version: String,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerSetSubscriptionsParams {
    pub subscriptions: Vec<ServerService>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerCancelRequestParams {
    pub id: String,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerSetClientCapabilitiesParams {
    pub requests: Vec<String>,
    #[serde(rename = "supportsUris", skip_serializing_if = "Option::is_none")]
    pub supports_uris: Option<bool>,
    #[serde(rename = "lspCapabilities", skip_serializing_if = "Option::is_none")]
    pub lsp_capabilities: Option<serde_json::Value>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerOpenUrlRequestParams {
    pub url: String,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerShowMessageRequestParams {
    #[serde(rename = "type")]
    pub type_: MessageType,
    pub message: String,
    pub actions: Vec<MessageAction>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerShowMessageRequestResult {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub action: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerConnectedParams {
    pub version: String,
    pub pid: i64,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerErrorParams {
    #[serde(rename = "isFatal")]
    pub is_fatal: bool,
    pub message: String,
    #[serde(rename = "stackTrace")]
    pub stack_trace: String,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerPluginErrorParams {
    pub message: String,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerLogParams {
    pub entry: ServerLogEntry,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerStatusParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub analysis: Option<AnalysisStatus>,
    #[serde(rename = "pub", skip_serializing_if = "Option::is_none")]
    pub pub_: Option<PubStatus>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalysisGetErrorsParams {
    pub file: FilePath,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalysisGetErrorsResult {
    pub errors: Vec<AnalysisError>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalysisGetHoverParams {
    pub file: FilePath,
    pub offset: i64,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalysisGetHoverResult {
    pub hovers: Vec<HoverInformation>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalysisGetImportedElementsParams {
    pub file: FilePath,
    pub offset: i64,
    pub length: i64,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalysisGetImportedElementsResult {
    pub elements: Vec<ImportedElements>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalysisGetLibraryDependenciesResult {
    pub libraries: Vec<FilePath>,
    #[serde(rename = "packageMap")]
    pub package_map:
        std::collections::BTreeMap<String, std::collections::BTreeMap<String, Vec<FilePath>>>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalysisGetNavigationParams {
    pub file: FilePath,
    pub offset: i64,
    pub length: i64,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalysisGetNavigationResult {
    pub files: Vec<FilePath>,
    pub targets: Vec<NavigationTarget>,
    pub regions: Vec<NavigationRegion>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalysisGetReachableSourcesParams {
    pub file: FilePath,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalysisGetReachableSourcesResult {
    pub sources: std::collections::BTreeMap<String, Vec<String>>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalysisGetSignatureParams {
    pub file: FilePath,
    pub offset: i64,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalysisGetSignatureResult {
    pub name: String,
    pub parameters: Vec<ParameterInfo>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dartdoc: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalysisSetAnalysisRootsParams {
    pub included: Vec<FilePath>,
    pub excluded: Vec<FilePath>,
    #[serde(rename = "packageRoots", skip_serializing_if = "Option::is_none")]
    pub package_roots: Option<std::collections::BTreeMap<FilePath, FilePath>>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalysisSetGeneralSubscriptionsParams {
    pub subscriptions: Vec<GeneralAnalysisService>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalysisSetPriorityFilesParams {
    pub files: Vec<FilePath>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalysisSetSubscriptionsParams {
    pub subscriptions: std::collections::BTreeMap<AnalysisService, Vec<FilePath>>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalysisUpdateContentParams {
    pub files: std::collections::BTreeMap<FilePath, AnalysisUpdateContentParamsFilesValue>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalysisUpdateContentResult {}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalysisUpdateOptionsParams {
    pub options: AnalysisOptions,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalysisAnalyzedFilesParams {
    pub directories: Vec<FilePath>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalysisClosingLabelsParams {
    pub file: FilePath,
    pub labels: Vec<ClosingLabel>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalysisErrorsParams {
    pub file: FilePath,
    pub errors: Vec<AnalysisError>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalysisFlushResultsParams {
    pub files: Vec<FilePath>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalysisFoldingParams {
    pub file: FilePath,
    pub regions: Vec<FoldingRegion>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalysisHighlightsParams {
    pub file: FilePath,
    pub regions: Vec<HighlightRegion>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalysisImplementedParams {
    pub file: FilePath,
    pub classes: Vec<ImplementedClass>,
    pub members: Vec<ImplementedMember>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalysisInvalidateParams {
    pub file: FilePath,
    pub offset: i64,
    pub length: i64,
    pub delta: i64,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalysisNavigationParams {
    pub file: FilePath,
    pub regions: Vec<NavigationRegion>,
    pub targets: Vec<NavigationTarget>,
    pub files: Vec<FilePath>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalysisOccurrencesParams {
    pub file: FilePath,
    pub occurrences: Vec<Occurrences>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalysisOutlineParams {
    pub file: FilePath,
    pub kind: FileKind,
    #[serde(rename = "libraryName", skip_serializing_if = "Option::is_none")]
    pub library_name: Option<String>,
    pub outline: Outline,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalysisOverridesParams {
    pub file: FilePath,
    pub overrides: Vec<Override>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompletionGetSuggestions2Params {
    pub file: FilePath,
    pub offset: i64,
    #[serde(rename = "maxResults")]
    pub max_results: i64,
    #[serde(
        rename = "completionCaseMatchingMode",
        skip_serializing_if = "Option::is_none"
    )]
    pub completion_case_matching_mode: Option<CompletionCaseMatchingMode>,
    #[serde(rename = "completionMode", skip_serializing_if = "Option::is_none")]
    pub completion_mode: Option<CompletionMode>,
    #[serde(rename = "invocationCount", skip_serializing_if = "Option::is_none")]
    pub invocation_count: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub timeout: Option<i64>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompletionGetSuggestions2Result {
    #[serde(rename = "replacementOffset")]
    pub replacement_offset: i64,
    #[serde(rename = "replacementLength")]
    pub replacement_length: i64,
    pub suggestions: Vec<CompletionSuggestion>,
    #[serde(rename = "isIncomplete")]
    pub is_incomplete: bool,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompletionRegisterLibraryPathsParams {
    pub paths: Vec<LibraryPathSet>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompletionGetSuggestionDetails2Params {
    pub file: FilePath,
    pub offset: i64,
    pub completion: String,
    #[serde(rename = "libraryUri")]
    pub library_uri: String,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompletionGetSuggestionDetails2Result {
    pub completion: String,
    pub change: SourceChange,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompletionExistingImportsParams {
    pub file: FilePath,
    pub imports: ExistingImports,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchFindElementReferencesParams {
    pub file: FilePath,
    pub offset: i64,
    #[serde(rename = "includePotential")]
    pub include_potential: bool,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchFindElementReferencesResult {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<SearchId>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub element: Option<Element>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchFindMemberDeclarationsParams {
    pub name: String,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchFindMemberDeclarationsResult {
    pub id: SearchId,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchFindMemberReferencesParams {
    pub name: String,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchFindMemberReferencesResult {
    pub id: SearchId,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchFindTopLevelDeclarationsParams {
    pub pattern: String,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchFindTopLevelDeclarationsResult {
    pub id: SearchId,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchGetElementDeclarationsParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub file: Option<FilePath>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pattern: Option<String>,
    #[serde(rename = "maxResults", skip_serializing_if = "Option::is_none")]
    pub max_results: Option<i64>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchGetElementDeclarationsResult {
    pub declarations: Vec<ElementDeclaration>,
    pub files: Vec<FilePath>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchGetTypeHierarchyParams {
    pub file: FilePath,
    pub offset: i64,
    #[serde(rename = "superOnly", skip_serializing_if = "Option::is_none")]
    pub super_only: Option<bool>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchGetTypeHierarchyResult {
    #[serde(rename = "hierarchyItems", skip_serializing_if = "Option::is_none")]
    pub hierarchy_items: Option<Vec<TypeHierarchyItem>>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchResultsParams {
    pub id: SearchId,
    pub results: Vec<SearchResult>,
    #[serde(rename = "isLast")]
    pub is_last: bool,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditFormatParams {
    pub file: FilePath,
    #[serde(rename = "selectionOffset")]
    pub selection_offset: i64,
    #[serde(rename = "selectionLength")]
    pub selection_length: i64,
    #[serde(rename = "lineLength", skip_serializing_if = "Option::is_none")]
    pub line_length: Option<i64>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditFormatResult {
    pub edits: Vec<SourceEdit>,
    #[serde(rename = "selectionOffset")]
    pub selection_offset: i64,
    #[serde(rename = "selectionLength")]
    pub selection_length: i64,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditFormatIfEnabledParams {
    pub directories: Vec<FilePath>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditFormatIfEnabledResult {
    pub edits: Vec<SourceFileEdit>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditGetAssistsParams {
    pub file: FilePath,
    pub offset: i64,
    pub length: i64,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditGetAssistsResult {
    pub assists: Vec<SourceChange>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditGetAvailableRefactoringsParams {
    pub file: FilePath,
    pub offset: i64,
    pub length: i64,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditGetAvailableRefactoringsResult {
    pub kinds: Vec<RefactoringKind>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditBulkFixesParams {
    pub included: Vec<FilePath>,
    #[serde(rename = "inTestMode", skip_serializing_if = "Option::is_none")]
    pub in_test_mode: Option<bool>,
    #[serde(rename = "updatePubspec", skip_serializing_if = "Option::is_none")]
    pub update_pubspec: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub codes: Option<Vec<String>>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditBulkFixesResult {
    pub message: String,
    pub edits: Vec<SourceFileEdit>,
    pub details: Vec<BulkFix>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditGetFixesParams {
    pub file: FilePath,
    pub offset: i64,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditGetFixesResult {
    pub fixes: Vec<AnalysisErrorFixes>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditGetPostfixCompletionParams {
    pub file: FilePath,
    pub key: String,
    pub offset: i64,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditGetPostfixCompletionResult {
    pub change: SourceChange,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditGetRefactoringParams {
    pub kind: RefactoringKind,
    pub file: FilePath,
    pub offset: i64,
    pub length: i64,
    #[serde(rename = "validateOnly")]
    pub validate_only: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub options: Option<RefactoringOptions>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditGetRefactoringResult {
    #[serde(rename = "initialProblems")]
    pub initial_problems: Vec<RefactoringProblem>,
    #[serde(rename = "optionsProblems")]
    pub options_problems: Vec<RefactoringProblem>,
    #[serde(rename = "finalProblems")]
    pub final_problems: Vec<RefactoringProblem>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub feedback: Option<RefactoringFeedback>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub change: Option<SourceChange>,
    #[serde(rename = "potentialEdits", skip_serializing_if = "Option::is_none")]
    pub potential_edits: Option<Vec<String>>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditGetStatementCompletionParams {
    pub file: FilePath,
    pub offset: i64,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditGetStatementCompletionResult {
    pub change: SourceChange,
    #[serde(rename = "whitespaceOnly")]
    pub whitespace_only: bool,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditIsPostfixCompletionApplicableParams {
    pub file: FilePath,
    pub key: String,
    pub offset: i64,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditIsPostfixCompletionApplicableResult {
    pub value: bool,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditListPostfixCompletionTemplatesResult {
    pub templates: Vec<PostfixTemplateDescriptor>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditImportElementsParams {
    pub file: FilePath,
    pub elements: Vec<ImportedElements>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub offset: Option<i64>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditImportElementsResult {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub edit: Option<SourceFileEdit>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditSortMembersParams {
    pub file: FilePath,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditSortMembersResult {
    pub edit: SourceFileEdit,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditOrganizeDirectivesParams {
    pub file: FilePath,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditOrganizeDirectivesResult {
    pub edit: SourceFileEdit,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExecutionCreateContextParams {
    #[serde(rename = "contextRoot")]
    pub context_root: FilePath,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExecutionCreateContextResult {
    pub id: ExecutionContextId,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExecutionDeleteContextParams {
    pub id: ExecutionContextId,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExecutionGetSuggestionsParams {
    pub code: String,
    pub offset: i64,
    #[serde(rename = "contextFile")]
    pub context_file: FilePath,
    #[serde(rename = "contextOffset")]
    pub context_offset: i64,
    pub variables: Vec<RuntimeCompletionVariable>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expressions: Option<Vec<RuntimeCompletionExpression>>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExecutionGetSuggestionsResult {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub suggestions: Option<Vec<CompletionSuggestion>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expressions: Option<Vec<RuntimeCompletionExpression>>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExecutionMapUriParams {
    pub id: ExecutionContextId,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub file: Option<FilePath>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub uri: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExecutionMapUriResult {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub file: Option<FilePath>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub uri: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExecutionSetSubscriptionsParams {
    pub subscriptions: Vec<ExecutionService>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExecutionLaunchDataParams {
    pub file: FilePath,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kind: Option<ExecutableKind>,
    #[serde(rename = "referencedFiles", skip_serializing_if = "Option::is_none")]
    pub referenced_files: Option<Vec<FilePath>>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiagnosticGetDiagnosticsResult {
    pub contexts: Vec<ContextData>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiagnosticGetServerPortResult {
    pub port: i64,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalyticsIsEnabledResult {
    pub enabled: bool,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalyticsEnableParams {
    pub value: bool,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalyticsSendEventParams {
    pub action: String,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalyticsSendTimingParams {
    pub event: String,
    pub millis: i64,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FlutterGetWidgetDescriptionParams {
    pub file: FilePath,
    pub offset: i64,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FlutterGetWidgetDescriptionResult {
    pub properties: Vec<FlutterWidgetProperty>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FlutterSetWidgetPropertyValueParams {
    pub id: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub value: Option<FlutterWidgetPropertyValue>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FlutterSetWidgetPropertyValueResult {
    pub change: SourceChange,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FlutterSetSubscriptionsParams {
    pub subscriptions: std::collections::BTreeMap<FlutterService, Vec<FilePath>>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FlutterOutlineParams {
    pub file: FilePath,
    pub outline: FlutterOutline,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LspHandleParams {
    #[serde(rename = "lspMessage")]
    pub lsp_message: serde_json::Value,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LspHandleResult {
    #[serde(rename = "lspResponse")]
    pub lsp_response: serde_json::Value,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LspNotificationParams {
    #[serde(rename = "lspNotification")]
    pub lsp_notification: serde_json::Value,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExtractLocalVariableFeedback {
    #[serde(
        rename = "coveringExpressionOffsets",
        skip_serializing_if = "Option::is_none"
    )]
    pub covering_expression_offsets: Option<Vec<i64>>,
    #[serde(
        rename = "coveringExpressionLengths",
        skip_serializing_if = "Option::is_none"
    )]
    pub covering_expression_lengths: Option<Vec<i64>>,
    pub names: Vec<String>,
    pub offsets: Vec<i64>,
    pub lengths: Vec<i64>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExtractLocalVariableOptions {
    pub name: String,
    #[serde(rename = "extractAll")]
    pub extract_all: bool,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExtractMethodFeedback {
    pub offset: i64,
    pub length: i64,
    #[serde(rename = "returnType")]
    pub return_type: String,
    pub names: Vec<String>,
    #[serde(rename = "canCreateGetter")]
    pub can_create_getter: bool,
    pub parameters: Vec<RefactoringMethodParameter>,
    pub offsets: Vec<i64>,
    pub lengths: Vec<i64>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExtractMethodOptions {
    #[serde(rename = "returnType")]
    pub return_type: String,
    #[serde(rename = "createGetter")]
    pub create_getter: bool,
    pub name: String,
    pub parameters: Vec<RefactoringMethodParameter>,
    #[serde(rename = "extractAll")]
    pub extract_all: bool,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExtractWidgetFeedback {}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExtractWidgetOptions {
    pub name: String,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineLocalVariableFeedback {
    pub name: String,
    pub occurrences: i64,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineMethodFeedback {
    #[serde(rename = "className", skip_serializing_if = "Option::is_none")]
    pub class_name: Option<String>,
    #[serde(rename = "methodName")]
    pub method_name: String,
    #[serde(rename = "isDeclaration")]
    pub is_declaration: bool,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineMethodOptions {
    #[serde(rename = "deleteSource")]
    pub delete_source: bool,
    #[serde(rename = "inlineAll")]
    pub inline_all: bool,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MoveFileOptions {
    #[serde(rename = "newFile")]
    pub new_file: FilePath,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RENAMEFeedback {
    pub offset: i64,
    pub length: i64,
    #[serde(rename = "elementKindName")]
    pub element_kind_name: String,
    #[serde(rename = "oldName")]
    pub old_name: String,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RENAMEOptions {
    #[serde(rename = "newName")]
    pub new_name: String,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum AddContentOverlayType {
    #[serde(rename = "add")]
    Value,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum ChangeContentOverlayType {
    #[serde(rename = "change")]
    Value,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum RemoveContentOverlayType {
    #[serde(rename = "remove")]
    Value,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AnalysisUpdateContentParamsFilesValue {
    AddContentOverlay(AddContentOverlay),
    ChangeContentOverlay(ChangeContentOverlay),
    RemoveContentOverlay(RemoveContentOverlay),
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn omits_absent_optional_fields() {
        let status = AnalysisStatus {
            is_analyzing: false,
            analysis_target: None,
        };
        assert_eq!(
            serde_json::to_value(status).unwrap(),
            serde_json::json!({"isAnalyzing": false})
        );
    }

    #[test]
    fn request_error_round_trips_wire_names_and_code() {
        let json = serde_json::json!({"code":"UNKNOWN_REQUEST","message":"Unknown request","stackTrace":"trace"});
        let error: RequestError = serde_json::from_value(json.clone()).unwrap();
        assert_eq!(error.code, RequestErrorCode::UnknownRequest);
        assert_eq!(serde_json::to_value(error).unwrap(), json);
    }

    #[test]
    fn content_overlay_union_uses_the_protocol_discriminator() {
        let json = serde_json::json!({"type":"add","content":"void main() {}","version":3});
        let overlay: AnalysisUpdateContentParamsFilesValue =
            serde_json::from_value(json.clone()).unwrap();
        assert!(matches!(
            overlay,
            AnalysisUpdateContentParamsFilesValue::AddContentOverlay(_)
        ));
        assert_eq!(serde_json::to_value(overlay).unwrap(), json);
    }
}
