[package]
name = "dartr_resolver"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dartr_ast.workspace = true
dartr_ast_builder.workspace = true
dartr_diagnostics.workspace = true
dartr_element.workspace = true
dartr_flow.workspace = true
dartr_parser.workspace = true
dartr_syntax.workspace = true
dartr_type_analyzer.workspace = true
dartr_typesystem.workspace = true
indexmap.workspace = true
rayon.workspace = true

[dev-dependencies]
dartr_driver.workspace = true
dartr_link.workspace = true
dartr_project.workspace = true
pretty_assertions.workspace = true
